-- =============================================================================
-- 010_split_menu_data.sql
--
-- Split shop_settings.menu_data jsonb into dedicated relational tables:
--   menu_categories
--   menu_items
--   menu_modifier_groups
--   menu_modifier_options
--   menu_item_modifier_groups
--   menu_discount_rules
--
-- Backfill copies existing menu_data.{categories,categoryOrder,hiddenCategories,
-- modifierGroups,discountRules} into the new tables. Re-runs are no-ops (guarded
-- by NOT EXISTS on menu_categories). After successful backfill the migrated
-- keys are stripped from menu_data so there is one source of truth. The
-- remaining keys (cashiers, posSettings, receiptSettings, loyaltySettings)
-- stay on shop_settings.menu_data.
--
-- This file mirrors the same block embedded in api/install.js and
-- src/components/SetupScreen.jsx. Keep all three in sync.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.menu_categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  sort_order  int  NOT NULL DEFAULT 0,
  is_hidden   bool NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.menu_items (
  id               text PRIMARY KEY,
  category_id      bigint NOT NULL REFERENCES public.menu_categories(id) ON DELETE RESTRICT,
  name             text NOT NULL,
  base_price_cents int  NOT NULL DEFAULT 0,
  price_type       text NOT NULL DEFAULT 'fixed',
  emoji            text NOT NULL DEFAULT '',
  sort_order       int  NOT NULL DEFAULT 0,
  is_hidden        bool NOT NULL DEFAULT false,
  data             jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_menu_items_category ON public.menu_items (category_id);

CREATE TABLE IF NOT EXISTS public.menu_modifier_groups (
  id             text PRIMARY KEY,
  name           text NOT NULL,
  allow_multiple bool NOT NULL DEFAULT false,
  sort_order     int  NOT NULL DEFAULT 0,
  data           jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at     timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.menu_modifier_groups ADD COLUMN IF NOT EXISTS allow_multiple bool NOT NULL DEFAULT false;

-- ON UPDATE CASCADE: group id is a slug derived from display name, so renaming
-- a group changes the id. Cascading keeps options + item links in sync.
CREATE TABLE IF NOT EXISTS public.menu_modifier_options (
  id                text PRIMARY KEY,
  group_id          text NOT NULL REFERENCES public.menu_modifier_groups(id) ON UPDATE CASCADE ON DELETE CASCADE,
  name              text NOT NULL,
  price_delta_cents int  NOT NULL DEFAULT 0,
  sort_order        int  NOT NULL DEFAULT 0,
  data              jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_menu_modifier_options_group ON public.menu_modifier_options (group_id);

CREATE TABLE IF NOT EXISTS public.menu_item_modifier_groups (
  item_id     text NOT NULL REFERENCES public.menu_items(id) ON UPDATE CASCADE ON DELETE CASCADE,
  group_id    text NOT NULL REFERENCES public.menu_modifier_groups(id) ON UPDATE CASCADE ON DELETE CASCADE,
  sort_order  int  NOT NULL DEFAULT 0,
  PRIMARY KEY (item_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.menu_discount_rules (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL DEFAULT '',
  rule_type   text NOT NULL DEFAULT '',
  payload     jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active   bool NOT NULL DEFAULT true,
  sort_order  int  NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.menu_categories           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_modifier_groups      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_modifier_options     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_item_modifier_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_discount_rules       ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Hardware can access menu_categories"           ON public.menu_categories;
DROP POLICY IF EXISTS "Hardware can access menu_items"                ON public.menu_items;
DROP POLICY IF EXISTS "Hardware can access menu_modifier_groups"      ON public.menu_modifier_groups;
DROP POLICY IF EXISTS "Hardware can access menu_modifier_options"     ON public.menu_modifier_options;
DROP POLICY IF EXISTS "Hardware can access menu_item_modifier_groups" ON public.menu_item_modifier_groups;
DROP POLICY IF EXISTS "Hardware can access menu_discount_rules"       ON public.menu_discount_rules;

CREATE POLICY "Hardware can access menu_categories"           ON public.menu_categories           FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Hardware can access menu_items"                ON public.menu_items                FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Hardware can access menu_modifier_groups"      ON public.menu_modifier_groups      FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Hardware can access menu_modifier_options"     ON public.menu_modifier_options     FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Hardware can access menu_item_modifier_groups" ON public.menu_item_modifier_groups FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Hardware can access menu_discount_rules"       ON public.menu_discount_rules       FOR ALL TO authenticated USING (true) WITH CHECK (true);

DO $menu_split$
DECLARE
  v_menu   jsonb;
  v_order  jsonb;
  v_hidden jsonb;
BEGIN
  IF EXISTS (SELECT 1 FROM public.menu_categories) THEN RETURN; END IF;

  SELECT menu_data INTO v_menu FROM public.shop_settings WHERE id = 1;
  IF v_menu IS NULL THEN RETURN; END IF;

  v_order  := COALESCE(v_menu->'categoryOrder',    '[]'::jsonb);
  v_hidden := COALESCE(v_menu->'hiddenCategories', '[]'::jsonb);

  WITH ordered AS (
    SELECT key, ord
    FROM jsonb_array_elements_text(v_order) WITH ORDINALITY AS o(key, ord)
  )
  INSERT INTO public.menu_categories (name, sort_order, is_hidden)
  SELECT k,
         COALESCE((SELECT ord FROM ordered WHERE key = k)::int, 1000),
         (v_hidden ? k)
  FROM jsonb_object_keys(COALESCE(v_menu->'categories','{}'::jsonb)) AS k
  ON CONFLICT (name) DO NOTHING;

  INSERT INTO public.menu_items (id, category_id, name, base_price_cents, price_type, emoji, sort_order, data)
  SELECT
    item->>'id',
    mc.id,
    COALESCE(item->>'name', ''),
    COALESCE((item->>'basePrice')::int, 0),
    COALESCE(item->>'priceType', 'fixed'),
    COALESCE(item->>'emoji', ''),
    (it.ord - 1)::int,
    (item - 'id' - 'name' - 'basePrice' - 'priceType' - 'emoji' - 'allowedModifiers' - 'category')
  FROM jsonb_each(COALESCE(v_menu->'categories','{}'::jsonb)) AS cat(key, value)
  JOIN public.menu_categories mc ON mc.name = cat.key
  CROSS JOIN LATERAL jsonb_array_elements(cat.value) WITH ORDINALITY AS it(item, ord)
  WHERE item->>'id' IS NOT NULL
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.menu_modifier_groups (id, name, allow_multiple, sort_order)
  SELECT key, key,
         COALESCE((v_menu->'modifierGroupSettings'->key->>'allowMultiple')::bool, false),
         ((row_number() OVER (ORDER BY key)) - 1)::int
  FROM jsonb_object_keys(COALESCE(v_menu->'modifierGroups','{}'::jsonb)) AS key
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.menu_modifier_options (id, group_id, name, price_delta_cents, sort_order, data)
  SELECT
    opt->>'id',
    grp.key,
    COALESCE(opt->>'name', ''),
    COALESCE((opt->>'priceDelta')::int, (opt->>'price_delta_cents')::int, 0),
    (o.ord - 1)::int,
    (opt - 'id' - 'name' - 'priceDelta' - 'price_delta_cents')
  FROM jsonb_each(COALESCE(v_menu->'modifierGroups','{}'::jsonb)) AS grp(key, value)
  CROSS JOIN LATERAL jsonb_array_elements(grp.value) WITH ORDINALITY AS o(opt, ord)
  WHERE opt->>'id' IS NOT NULL
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.menu_item_modifier_groups (item_id, group_id, sort_order)
  SELECT item->>'id', m.mod_key, (m.ord - 1)::int
  FROM jsonb_each(COALESCE(v_menu->'categories','{}'::jsonb)) AS cat(key, value)
  CROSS JOIN LATERAL jsonb_array_elements(cat.value) AS item
  CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(item->'allowedModifiers','[]'::jsonb))
                     WITH ORDINALITY AS m(mod_key, ord)
  WHERE EXISTS (SELECT 1 FROM public.menu_items         mi WHERE mi.id = item->>'id')
    AND EXISTS (SELECT 1 FROM public.menu_modifier_groups mg WHERE mg.id = m.mod_key)
  ON CONFLICT DO NOTHING;

  INSERT INTO public.menu_discount_rules (name, rule_type, payload, is_active, sort_order)
  SELECT
    COALESCE(rule->>'name',''),
    COALESCE(rule->>'type',''),
    rule,
    COALESCE((rule->>'isActive')::bool, true),
    (r.ord - 1)::int
  FROM jsonb_array_elements(COALESCE(v_menu->'discountRules','[]'::jsonb))
       WITH ORDINALITY AS r(rule, ord);

  UPDATE public.shop_settings
  SET menu_data = menu_data
                  - 'categories'
                  - 'categoryOrder'
                  - 'hiddenCategories'
                  - 'modifierGroups'
                  - 'modifierGroupSettings'
                  - 'discountRules'
  WHERE id = 1;
END
$menu_split$;
