-- =============================================================================
-- 024_vendor_payouts.sql
--
-- Vendor payout ledger (the money-movement half of multi-vendor sales). The
-- `vendors` settlement report (migration 023) computes what is OWED to each
-- vendor over a date range; this table records what was actually PAID, so the
-- report can show a running balance (owed − paid) instead of recomputing gross
-- every time and risking a double-payment.
--
-- Mirrors tip_payouts: server identity PK, a UNIQUE client local_id for
-- idempotent local→cloud upserts, written local-first then best-effort to cloud.
--
-- Each row also FREEZES the settlement it was paid against in `data` jsonb
-- (the per-item breakdown, the totals, the date range, and whether the
-- menu-fallback attribution was used). That snapshot is the "statement": paying
-- against it is unaffected by later vendor renames, retagging, or price changes.
--
-- This file mirrors the same block embedded in api/install.js and
-- src/components/SetupScreen.jsx. Keep all three in sync.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.vendor_payouts (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_id     text,                                  -- vendors.id; null if vendor since deleted
  vendor_name   text NOT NULL,                         -- snapshot, readable even if vendor removed
  period_from   date,                                  -- settlement range this payment covers
  period_to     date,
  owed_cents    numeric NOT NULL DEFAULT 0,            -- amount owed at close (frozen)
  amount        numeric NOT NULL,                      -- amount actually paid (cents); negative = reversal
  method        text DEFAULT 'cash',
  note          text,
  cashier_name  text,
  data          jsonb NOT NULL DEFAULT '{}'::jsonb,    -- frozen statement: { items, totals, range, menuFallback }
  local_id      uuid UNIQUE,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vendor_payouts_vendor  ON public.vendor_payouts (vendor_id);
CREATE INDEX IF NOT EXISTS idx_vendor_payouts_created ON public.vendor_payouts (created_at);

ALTER TABLE public.vendor_payouts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Hardware can access vendor_payouts" ON public.vendor_payouts;
CREATE POLICY "Hardware can access vendor_payouts" ON public.vendor_payouts
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
