function LoyaltyTab({ loyaltyForm, setLoyaltyForm, menuData, saveMenuToCloud, handleSaveLoyalty, handleResetLoyaltyData, showAlert }) {
  return (
    <div className="admin-section fade-in">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' }}>
        <div><h1 style={{ margin: 0, color: 'var(--text-main)' }}>Loyalty Program</h1><p style={{ color: 'var(--text-muted)', margin: '5px 0 0 0' }}>Design your customer reward system and manage active promotions.</p></div>
        <button onClick={() => { const newForm = { ...loyaltyForm, isActive: !loyaltyForm.isActive }; setLoyaltyForm(newForm); const updatedMenu = { ...menuData, loyaltySettings: newForm }; saveMenuToCloud(updatedMenu); showAlert("Success", newForm.isActive ? "Loyalty Program is now ACTIVE!" : "Loyalty Program is now PAUSED!"); }} style={{ padding: '10px 20px', background: loyaltyForm.isActive ? '#27ae60' : 'transparent', color: loyaltyForm.isActive ? 'white' : 'var(--text-muted)', border: `2px solid ${loyaltyForm.isActive ? '#27ae60' : 'var(--border)'}`, borderRadius: '20px', cursor: 'pointer', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '8px', transition: 'all 0.2s' }}>{loyaltyForm.isActive ? '🟢 Program is ACTIVE' : '⏸️ Program is PAUSED'}</button>
      </div>
      <div style={{ background: 'var(--bg-surface)', padding: '32px', borderRadius: '12px', boxShadow: '0 2px 4px rgba(0,0,0,0.05)', maxWidth: '600px', display: 'flex', flexDirection: 'column', gap: '24px' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', opacity: loyaltyForm.isActive ? 1 : 0.5, pointerEvents: loyaltyForm.isActive ? 'auto' : 'none' }}><label style={{ fontWeight: 'bold', color: 'var(--text-main)' }}>Visits Required</label><input type="number" min="1" value={loyaltyForm.visitsRequired} onChange={(e) => setLoyaltyForm({ ...loyaltyForm, visitsRequired: parseInt(e.target.value) || 10 })} style={{ padding: '12px', border: '1px solid var(--border)', borderRadius: '6px', fontSize: '1.2rem', background: 'var(--bg-main)', color: 'var(--text-main)' }} /><small style={{ color: 'var(--text-muted)' }}>How many stars do they need to collect before unlocking the reward?</small></div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', opacity: loyaltyForm.isActive ? 1 : 0.5, pointerEvents: loyaltyForm.isActive ? 'auto' : 'none' }}><label style={{ fontWeight: 'bold', color: 'var(--text-main)' }}>Reward Description</label><input type="text" placeholder="e.g., tu próxima bebida GRATIS" value={loyaltyForm.rewardDescription} onChange={(e) => setLoyaltyForm({ ...loyaltyForm, rewardDescription: e.target.value })} style={{ padding: '12px', border: '1px solid var(--border)', borderRadius: '6px', fontSize: '1.1rem', background: 'var(--bg-main)', color: 'var(--text-main)' }} /><small style={{ color: 'var(--text-muted)' }}>This exact text will be sent to the customer on WhatsApp when they hit their goal!</small></div>
        <div style={{ background: '#fff0f5', border: '2px solid #ff69b4', padding: '20px', borderRadius: '8px', marginTop: '10px', opacity: loyaltyForm.isActive ? 1 : 0.5 }}><h4 style={{ color: '#ff1493', margin: '0 0 10px 0', textTransform: 'uppercase' }}>WhatsApp Preview (Visit #{loyaltyForm.visitsRequired}):</h4><p style={{ margin: 0, fontFamily: 'monospace', color: '#333', whiteSpace: 'pre-wrap' }}>{`🎉 *¡Felicidades!*\nEsta es tu visita #${loyaltyForm.visitsRequired}. ¡Te has ganado ${loyaltyForm.rewardDescription}!\n`}</p></div>
        <button onClick={handleSaveLoyalty} style={{ padding: '16px', background: 'var(--brand-color)', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold', marginTop: '8px', fontSize: '1.1rem' }}>Save Settings</button>
        <div style={{ marginTop: '20px', paddingTop: '24px', borderTop: '2px dashed #e74c3c' }}><h3 style={{ color: '#e74c3c', marginTop: 0 }}>Danger Zone</h3><p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '16px' }}>Starting a new promotion? Wipe all current customer stars back to zero.</p><button onClick={handleResetLoyaltyData} style={{ width: '100%', padding: '12px', background: 'transparent', color: '#e74c3c', border: '2px solid #e74c3c', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold' }}>⚠️ Reset All Customer Stars to Zero</button></div>
      </div>
    </div>
  );
}
export default LoyaltyTab;
