-- db/schema.sql

CREATE TABLE IF NOT EXISTS public.active_tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  items jsonb,
  cashier_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  sentToBarista boolean,
  discount jsonb,
  savedSplitPayments jsonb,
  savedPaidProductIds jsonb,
  savedSplitMode text,
  savedNWays bigint,
  last_modified_by text
);

CREATE TABLE IF NOT EXISTS public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone character varying NOT NULL,
  visits bigint NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.expenses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount numeric NOT NULL, 
  reason text,
  cashier_name text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  current_stock numeric DEFAULT 0,
  unit text,
  created_at timestamp with time zone DEFAULT now(),
  unit_cost numeric DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.inventory_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_name text NOT NULL,
  qty_deducted numeric NOT NULL,
  deduction_type text NOT NULL,
  ticket_id text,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.recipes (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  linked_menu_item text,
  target_margin numeric DEFAULT 25.0,
  custom_price numeric,
  ingredients jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  total_amount numeric,
  payment_method text,
  items_sold jsonb,
  cashier_name text,
  status text DEFAULT 'paid',
  order_name text
);

CREATE TABLE IF NOT EXISTS public.shop_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  menu_data jsonb
);

-- SEED THE DATABASE: Ensure the shop_settings row exists for the app to boot
INSERT INTO public.shop_settings (id, menu_data)
VALUES (
  1, 
  '{"categories": {"Café": []}, "cashiers": [{"id": 1, "name": "Admin", "pin": "1234", "isAdmin": true}], "posSettings": {"name": "TinyPOS", "pinCode": "1234"}}'::jsonb
)
ON CONFLICT (id) DO NOTHING;