// Customer-facing menu. Read-only. No auth, no settings, no admin.
//
// Hits the Supabase get_active_menu() RPC (migration 015) with the
// publishable key. The resolver picks the right menu server-side based on
// priority + scheduled time windows (shop-local), with the catalog 'live'
// menu as always-on fallback. We re-fetch every 5 minutes so a scheduled
// menu swap (e.g. brunch → lunch at 11am) appears without restart.
//
// Response envelope (sanitized — internal fields never reach the client):
//   { menu: {id, kind, name, data}, shop, categories, modifier_groups }
// For kind='live' we render categories/modifier_groups (catalog view).
// For kind in ('pdf','image','designed') we render from menu.data — those
// renderers ship in later phases.
//
// Routed at /menu and bypasses every App.jsx gate. The shop's Supabase URL
// and publishable key arrive as base64-encoded `u` and `k` query params
// (generated by MenuShareCard), so this single central deployment can serve
// any shop's menu without build-time config.

import { useEffect, useMemo, useRef, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
import { formatForDisplay } from '../utils/moneyUtils';

// Standard base64 → string. Tolerates URL-safe variants in case the link was
// rewritten by a QR scanner or messaging app.
function decodeParam(value) {
  if (!value) return '';
  try {
    const normalized = value.replace(/-/g, '+').replace(/_/g, '/');
    return atob(normalized);
  } catch {
    return '';
  }
}

function PublicMenu() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [activeCategoryId, setActiveCategoryId] = useState(null);
  const isTvMode = typeof window !== 'undefined' && window.location.pathname === '/menu/tv';

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const supabaseUrl = decodeParam(params.get('u'));
    const publishableKey = decodeParam(params.get('k'));

    if (!supabaseUrl || !publishableKey) {
      setError('missing-config');
      return;
    }

    const client = createClient(supabaseUrl, publishableKey, {
      auth: { persistSession: false, autoRefreshToken: false }
    });

    // ?m=<id> pins a specific menu (per-card share links), bypassing the
    // schedule resolver. Falls back to get_active_menu when absent.
    const pinnedId = params.get('m');
    let cancelled = false;
    async function fetchMenu() {
      const { data, error } = pinnedId
        ? await client.rpc('get_menu_by_id', { p_id: Number(pinnedId) })
        : await client.rpc('get_active_menu');
      if (cancelled) return;
      if (error) { setError(error.message); return; }
      setData(data);
      setActiveCategoryId(prev => {
        if (prev && data?.categories?.some(c => c.id === prev)) return prev;
        return data?.categories?.[0]?.id ?? null;
      });
    }
    fetchMenu();
    // Re-resolve every 5 min so scheduled swaps appear without a manual refresh.
    const iv = setInterval(fetchMenu, 5 * 60 * 1000);
    return () => { cancelled = true; clearInterval(iv); };
  }, []);

  const groupsById = useMemo(() => {
    const m = new Map();
    (data?.modifier_groups || []).forEach(g => m.set(g.id, g));
    return m;
  }, [data]);

  if (error === 'missing-config') return <ConfigMissing />;
  if (error) return <ErrorState message={error} />;
  if (!data) return <LoadingState />;

  const shop = data.shop || {};
  const brand = shop.brand_color || '#f28b05';
  const lang = shop.language || 'es';
  const menuKind = data.menu?.kind || 'live';
  const categories = data.categories || [];
  const activeCategory = categories.find(c => c.id === activeCategoryId) || categories[0];

  if (isTvMode) {
    return <TvMode data={data} brand={brand} lang={lang} />;
  }

  // Designer kind: render through a template selected on menu.data.template.
  // Filtering by menu.data.category_names is applied first so the user sees
  // exactly the slice they configured.
  if (menuKind === 'designed') {
    return <TemplatedMenu data={data} brand={brand} lang={lang} />;
  }

  // Uploaded PDF/image kinds render as a page carousel from menu.data.pages.
  if (menuKind === 'pdf' || menuKind === 'image') {
    return (
      <div style={pageStyle}>
        <header style={{ ...headerStyle, background: brand }}>
          <h1 style={headerTitleStyle}>{shop.name || 'Menu'}</h1>
        </header>
        <UploadedMenu menu={data.menu} brand={brand} />
      </div>
    );
  }

  // kind='designed' renderer ships in Phase 4. Placeholder for now.
  if (menuKind !== 'live') {
    return (
      <div style={pageStyle}>
        <header style={{ ...headerStyle, background: brand }}>
          <h1 style={headerTitleStyle}>{shop.name || 'Menu'}</h1>
        </header>
        <div style={centerStyle}>
          <div>
            <p style={{ margin: 0, fontWeight: 700 }}>{data.menu?.name || 'Menú'}</p>
            <p style={{ marginTop: 8, fontSize: '0.85rem', color: '#888' }}>
              Este formato de menú ({menuKind}) aún no está disponible para mostrar.
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div style={pageStyle}>
      <header style={{ ...headerStyle, background: brand }}>
        <h1 style={headerTitleStyle}>{shop.name || 'Menu'}</h1>
      </header>

      {categories.length === 0 ? (
        <EmptyState />
      ) : (
        <>
          <nav style={navStyle} aria-label="Categorías">
            {categories.map(c => {
              const isActive = c.id === activeCategory?.id;
              return (
                <button
                  key={c.id}
                  onClick={() => setActiveCategoryId(c.id)}
                  style={{
                    ...navButtonStyle,
                    color: isActive ? brand : '#555',
                    borderBottomColor: isActive ? brand : 'transparent'
                  }}
                >
                  {c.name}
                </button>
              );
            })}
          </nav>

          <main style={mainStyle}>
            {activeCategory && (
              <ItemList
                items={activeCategory.items}
                groupsById={groupsById}
                lang={lang}
                brand={brand}
              />
            )}
          </main>
        </>
      )}
    </div>
  );
}

function ItemList({ items, groupsById, lang, brand }) {
  if (!items || items.length === 0) {
    return <p style={{ textAlign: 'center', color: '#888', padding: '40px 16px' }}>—</p>;
  }
  return (
    <ul style={listStyle}>
      {items.map(item => (
        <li key={item.id} style={itemStyle}>
          <div style={itemLeftStyle}>
            {item.image_url ? (
              <img
                src={item.image_url}
                alt=""
                loading="lazy"
                style={imageStyle}
              />
            ) : (
              <span style={emojiStyle} aria-hidden>{item.emoji || '•'}</span>
            )}
            <div>
              <div style={itemNameStyle}>{item.name}</div>
              {item.modifier_group_ids?.length > 0 && (
                <ItemModifiers groupIds={item.modifier_group_ids} groupsById={groupsById} lang={lang} brand={brand} />
              )}
            </div>
          </div>
          <div style={priceStyle}>
            {item.price_type === 'open'
              ? <span style={{ color: '#888', fontWeight: 600 }}>—</span>
              : formatForDisplay(item.price_cents, lang)}
          </div>
        </li>
      ))}
    </ul>
  );
}

function ItemModifiers({ groupIds, groupsById, lang, brand }) {
  const groups = groupIds.map(id => groupsById.get(id)).filter(Boolean);
  if (groups.length === 0) return null;
  return (
    <div style={modifiersWrapStyle}>
      {groups.map(g => (
        <div key={g.id} style={{ marginTop: 6 }}>
          <div style={{ fontSize: '0.75rem', color: brand, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            {g.name}
          </div>
          <div style={{ fontSize: '0.85rem', color: '#666', marginTop: 2 }}>
            {g.options.map((o, idx) => {
              const delta = o.price_delta_cents;
              const label = delta ? `${o.name} ${delta > 0 ? '+' : ''}${formatForDisplay(delta, lang)}` : o.name;
              return (
                <span key={o.id}>
                  {idx > 0 && <span style={{ color: '#ccc' }}> · </span>}
                  {label}
                </span>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}

// Swipeable page carousel for pdf/image kinds. Touch swipes via touchstart/end
// deltas (no library); keyboard arrows work too. Single-page menus skip the
// chrome entirely so they look like a clean poster.
function UploadedMenu({ menu, brand }) {
  const pages = menu?.data?.pages || [];
  const originalUrl = menu?.data?.original_url;
  const [idx, setIdx] = useState(0);
  const touchX = useRef(null);

  useEffect(() => {
    function onKey(e) {
      if (e.key === 'ArrowRight') setIdx(i => Math.min(pages.length - 1, i + 1));
      if (e.key === 'ArrowLeft')  setIdx(i => Math.max(0, i - 1));
    }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [pages.length]);

  if (pages.length === 0) {
    return <div style={centerStyle}>Menú vacío.</div>;
  }

  const onTouchStart = e => { touchX.current = e.touches[0].clientX; };
  const onTouchEnd = e => {
    if (touchX.current == null) return;
    const dx = e.changedTouches[0].clientX - touchX.current;
    if (dx > 50) setIdx(i => Math.max(0, i - 1));
    else if (dx < -50) setIdx(i => Math.min(pages.length - 1, i + 1));
    touchX.current = null;
  };

  return (
    <div style={{ padding: '12px 0 32px' }}>
      <div
        style={{
          position: 'relative',
          background: '#000',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          minHeight: 'min(80vh, 720px)',
          overflow: 'hidden'
        }}
        onTouchStart={onTouchStart}
        onTouchEnd={onTouchEnd}
      >
        <img
          src={pages[idx]}
          alt={`Página ${idx + 1}`}
          style={{ maxWidth: '100%', maxHeight: '80vh', objectFit: 'contain', display: 'block' }}
        />
        {pages.length > 1 && (
          <>
            <button onClick={() => setIdx(i => Math.max(0, i - 1))} disabled={idx === 0} style={{ ...carouselBtn, left: 12 }} aria-label="Anterior">
              ‹
            </button>
            <button onClick={() => setIdx(i => Math.min(pages.length - 1, i + 1))} disabled={idx === pages.length - 1} style={{ ...carouselBtn, right: 12 }} aria-label="Siguiente">
              ›
            </button>
          </>
        )}
      </div>

      {pages.length > 1 && (
        <div style={{ display: 'flex', justifyContent: 'center', gap: 6, padding: '14px 16px 0' }}>
          {pages.map((_, i) => (
            <button
              key={i}
              onClick={() => setIdx(i)}
              aria-label={`Página ${i + 1}`}
              style={{
                width: 10, height: 10, borderRadius: 999, border: 'none', padding: 0,
                background: i === idx ? brand : '#ccc', cursor: 'pointer'
              }}
            />
          ))}
        </div>
      )}

      {originalUrl && (
        <div style={{ textAlign: 'center', padding: '18px 16px 0' }}>
          <a
            href={originalUrl}
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: brand, fontWeight: 700, textDecoration: 'none', fontSize: '0.9rem' }}
          >
            Descargar PDF original ↓
          </a>
        </div>
      )}
    </div>
  );
}

const carouselBtn = {
  position: 'absolute',
  top: '50%',
  transform: 'translateY(-50%)',
  width: 44, height: 44,
  borderRadius: 999,
  border: 'none',
  background: 'rgba(255,255,255,0.85)',
  color: '#222',
  fontSize: '1.8rem',
  fontWeight: 700,
  cursor: 'pointer',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  lineHeight: 1
};

// Phase 4a templates. All three templates take the same props and render the
// catalog payload returned by get_active_menu (kind='designed' gets the same
// shape as 'live'). Bindings stay live — prices, hidden state, and modifier
// groups flow through automatically because the customer fetches the same RPC.
function TemplatedMenu({ data, brand, lang }) {
  const menu = data.menu || {};
  const opts = menu.data || {};
  const accent = opts.accent_color || brand;
  const wanted = opts.category_names && opts.category_names.length > 0
    ? new Set(opts.category_names)
    : null;
  const categories = (data.categories || []).filter(c => !wanted || wanted.has(c.name));
  const groupsById = mapGroups(data.modifier_groups);

  const template = opts.template || 'list';
  const TemplateCmp =
    template === 'cards'      ? CardsTemplate :
    template === 'chalkboard' ? ChalkboardTemplate :
                                ListTemplate;

  return (
    <TemplateCmp
      shopName={data.shop?.name || 'Menu'}
      menuName={menu.name || ''}
      categories={categories}
      groupsById={groupsById}
      accent={accent}
      lang={lang}
    />
  );
}

function ListTemplate({ shopName, menuName, categories, groupsById, accent, lang }) {
  return (
    <div style={{ minHeight: '100vh', background: '#fafafa', fontFamily: 'system-ui, -apple-system, sans-serif', color: '#222', paddingBottom: 'env(safe-area-inset-bottom)' }}>
      <header style={{ padding: '32px 20px 20px', textAlign: 'center', background: accent, color: 'white' }}>
        <h1 style={{ margin: 0, fontSize: '1.8rem', fontWeight: 900, letterSpacing: '-0.01em' }}>{shopName}</h1>
        {menuName && <p style={{ margin: '6px 0 0', opacity: 0.85, fontWeight: 600 }}>{menuName}</p>}
      </header>
      <main style={{ padding: '20px 16px 40px', maxWidth: 720, margin: '0 auto' }}>
        {categories.map(c => (
          <section key={c.id} style={{ marginBottom: 32 }}>
            <h2 style={{ margin: '0 0 12px', fontSize: '1.4rem', color: accent, fontWeight: 800, borderBottom: `2px solid ${accent}`, paddingBottom: 6 }}>{c.name}</h2>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 4 }}>
              {c.items.map(it => (
                <li key={it.id} style={{ display: 'flex', justifyContent: 'space-between', gap: 12, padding: '12px 4px', borderBottom: '1px solid #eee' }}>
                  <div style={{ minWidth: 0 }}>
                    <div style={{ fontWeight: 700 }}>{it.emoji ? `${it.emoji} ` : ''}{it.name}</div>
                    {it.modifier_group_ids?.length > 0 && (
                      <div style={{ fontSize: '0.8rem', color: '#888', marginTop: 2 }}>
                        {it.modifier_group_ids.map(id => groupsById.get(id)?.name).filter(Boolean).join(' · ')}
                      </div>
                    )}
                  </div>
                  <div style={{ fontWeight: 800, whiteSpace: 'nowrap' }}>
                    {it.price_type === 'open' ? '—' : formatForDisplay(it.price_cents, lang)}
                  </div>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </main>
    </div>
  );
}

function CardsTemplate({ shopName, menuName, categories, groupsById, accent, lang }) {
  return (
    <div style={{ minHeight: '100vh', background: '#f3f1ee', fontFamily: '"Helvetica Neue", system-ui, sans-serif', color: '#1a1a1a', paddingBottom: 'env(safe-area-inset-bottom)' }}>
      <header style={{ padding: '40px 20px 28px', textAlign: 'center' }}>
        <div style={{ display: 'inline-block', padding: '4px 14px', borderRadius: 999, background: accent, color: 'white', fontSize: '0.75rem', fontWeight: 800, letterSpacing: '0.1em', textTransform: 'uppercase' }}>
          {menuName || 'Menú'}
        </div>
        <h1 style={{ margin: '14px 0 0', fontSize: '2rem', fontWeight: 900, letterSpacing: '-0.02em' }}>{shopName}</h1>
      </header>
      <main style={{ padding: '0 16px 40px', maxWidth: 980, margin: '0 auto' }}>
        {categories.map(c => (
          <section key={c.id} style={{ marginBottom: 40 }}>
            <h2 style={{ margin: '0 0 16px', fontSize: '1.5rem', fontWeight: 900, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{c.name}</h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: 16 }}>
              {c.items.map(it => (
                <article key={it.id} style={{ background: 'white', borderRadius: 16, overflow: 'hidden', boxShadow: '0 8px 24px rgba(0,0,0,0.06)', display: 'flex', flexDirection: 'column' }}>
                  {it.image_url ? (
                    <img src={it.image_url} alt="" loading="lazy" style={{ width: '100%', aspectRatio: '4/3', objectFit: 'cover', display: 'block' }} />
                  ) : (
                    <div style={{ aspectRatio: '4/3', background: '#eee', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '3rem' }}>{it.emoji || '•'}</div>
                  )}
                  <div style={{ padding: 14, display: 'flex', flexDirection: 'column', gap: 8, flex: 1 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, alignItems: 'baseline' }}>
                      <h3 style={{ margin: 0, fontSize: '1.05rem', fontWeight: 800, lineHeight: 1.2 }}>{it.name}</h3>
                      <span style={{ fontWeight: 900, color: accent, whiteSpace: 'nowrap' }}>
                        {it.price_type === 'open' ? '—' : formatForDisplay(it.price_cents, lang)}
                      </span>
                    </div>
                    {it.modifier_group_ids?.length > 0 && (
                      <div style={{ fontSize: '0.78rem', color: '#777' }}>
                        {it.modifier_group_ids.map(id => groupsById.get(id)?.name).filter(Boolean).join(' · ')}
                      </div>
                    )}
                  </div>
                </article>
              ))}
            </div>
          </section>
        ))}
      </main>
    </div>
  );
}

function ChalkboardTemplate({ shopName, menuName, categories, groupsById, accent, lang }) {
  // Chalkboard look: dark green background, hand-painted-style serif, chalky
  // dividers. No external font dep — uses 'Brush Script MT' / 'Marker Felt'
  // with system fallback so it loads instantly even on a kiosk with no net.
  const chalk = '#f5f0e1';
  return (
    <div style={{ minHeight: '100vh', background: '#1d2e25', color: chalk, fontFamily: '"Marker Felt", "Brush Script MT", "Comic Sans MS", cursive', paddingBottom: 'env(safe-area-inset-bottom)' }}>
      <header style={{ padding: '40px 20px 24px', textAlign: 'center', borderBottom: `1px dashed ${chalk}88` }}>
        <h1 style={{ margin: 0, fontSize: '2.4rem', fontWeight: 700, letterSpacing: '0.02em', color: accent }}>{shopName}</h1>
        {menuName && <p style={{ margin: '6px 0 0', opacity: 0.8 }}>~ {menuName} ~</p>}
      </header>
      <main style={{ padding: '24px 20px 40px', maxWidth: 780, margin: '0 auto' }}>
        {categories.map(c => (
          <section key={c.id} style={{ marginBottom: 32 }}>
            <h2 style={{ margin: '0 0 14px', fontSize: '1.8rem', color: accent, textAlign: 'center' }}>· {c.name} ·</h2>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 10 }}>
              {c.items.map(it => (
                <li key={it.id} style={{ display: 'flex', justifyContent: 'space-between', gap: 14, padding: '8px 0', borderBottom: `1px dotted ${chalk}55` }}>
                  <div style={{ minWidth: 0, fontSize: '1.15rem' }}>
                    {it.emoji ? `${it.emoji} ` : ''}{it.name}
                    {it.modifier_group_ids?.length > 0 && (
                      <div style={{ fontSize: '0.85rem', opacity: 0.6, marginTop: 2 }}>
                        {it.modifier_group_ids.map(id => groupsById.get(id)?.name).filter(Boolean).join(' · ')}
                      </div>
                    )}
                  </div>
                  <div style={{ fontSize: '1.25rem', whiteSpace: 'nowrap' }}>
                    {it.price_type === 'open' ? '—' : formatForDisplay(it.price_cents, lang)}
                  </div>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </main>
    </div>
  );
}

// Full-screen kiosk mode at /menu/tv. Requests Wake Lock so tablet screens
// stay on, auto-rotates slides every `rotation_ms` (configurable on the menu
// row's data, default 12s), and crossfades between slides. Re-fetch is
// handled by the parent's 5-min interval, so a scheduled menu swap shows up
// automatically without restart.
//
// Slide set depends on menu kind:
//   live           — one slide per category
//   pdf / image    — one slide per page
//   designed       — placeholder slide (renderer ships in Phase 4)
function TvMode({ data, brand, lang }) {
  const menu = data.menu || {};
  const kind = menu.kind || 'live';
  const rotationMs = Math.max(3000, menu.data?.rotation_ms || 12000);

  const slides = useMemo(() => {
    if (kind === 'live' || kind === 'designed') {
      const wanted = menu.data?.category_names && menu.data.category_names.length > 0
        ? new Set(menu.data.category_names)
        : null;
      const cats = (data.categories || []).filter(c => !wanted || wanted.has(c.name));
      return cats.map(c => ({ key: `cat-${c.id}`, kind: 'category', payload: c }));
    }
    if (kind === 'pdf' || kind === 'image') {
      return (menu.data?.pages || []).map((url, i) => ({ key: `pg-${i}`, kind: 'page', payload: { url, index: i } }));
    }
    return [{ key: 'placeholder', kind: 'placeholder', payload: null }];
  }, [data, kind, menu.data]);

  const [idx, setIdx] = useState(0);
  const [visible, setVisible] = useState(true);

  // Reset index when slide set shrinks (e.g. a category was hidden).
  useEffect(() => {
    if (idx >= slides.length) setIdx(0);
  }, [slides.length, idx]);

  // Rotation: hide → swap → show, for a clean crossfade.
  useEffect(() => {
    if (slides.length <= 1) return;
    const tick = setInterval(() => {
      setVisible(false);
      setTimeout(() => {
        setIdx(i => (i + 1) % slides.length);
        setVisible(true);
      }, 350);
    }, rotationMs);
    return () => clearInterval(tick);
  }, [slides.length, rotationMs]);

  // Wake Lock — quiet best-effort. Some browsers require a gesture; if the
  // request rejects we just let the screen sleep rather than nag the viewer.
  useEffect(() => {
    let sentinel = null;
    let released = false;
    async function acquire() {
      try {
        if ('wakeLock' in navigator) {
          sentinel = await navigator.wakeLock.request('screen');
        }
      } catch { /* ignore */ }
    }
    function onVisibility() {
      // Browsers auto-release on tab hide; reacquire when shown again.
      if (document.visibilityState === 'visible' && !released) acquire();
    }
    acquire();
    document.addEventListener('visibilitychange', onVisibility);
    return () => {
      released = true;
      document.removeEventListener('visibilitychange', onVisibility);
      if (sentinel) sentinel.release().catch(() => {});
    };
  }, []);

  const slide = slides[idx];

  return (
    <div style={tvPageStyle}>
      <div style={{ ...tvHeaderStyle, background: brand }}>
        <h1 style={tvHeaderTitleStyle}>{data.shop?.name || 'Menu'}</h1>
        {slides.length > 1 && (
          <div style={tvDotsStyle}>
            {slides.map((_, i) => (
              <span key={i} style={{ ...tvDotStyle, background: i === idx ? 'white' : 'rgba(255,255,255,0.35)' }} />
            ))}
          </div>
        )}
      </div>
      <div style={{ ...tvSlideStyle, opacity: visible ? 1 : 0 }}>
        {slide?.kind === 'category' && <TvCategorySlide category={slide.payload} groupsById={mapGroups(data.modifier_groups)} lang={lang} brand={brand} />}
        {slide?.kind === 'page' && <TvPageSlide url={slide.payload.url} />}
        {slide?.kind === 'placeholder' && (
          <div style={{ color: 'rgba(255,255,255,0.6)', fontSize: '1.5rem' }}>
            {menu.name || 'Menú'} — formato no disponible aún
          </div>
        )}
      </div>
    </div>
  );
}

function mapGroups(groups) {
  const m = new Map();
  (groups || []).forEach(g => m.set(g.id, g));
  return m;
}

function TvCategorySlide({ category, groupsById, lang, brand }) {
  const items = category?.items || [];
  return (
    <div style={{ width: '100%', height: '100%', padding: '40px 80px 60px', display: 'flex', flexDirection: 'column', gap: 40, color: 'white' }}>
      <h2 style={{ margin: 0, fontSize: 'clamp(2.5rem, 5vw, 4.5rem)', fontWeight: 900, letterSpacing: '-0.02em', color: brand }}>
        {category?.name || ''}
      </h2>
      <div style={{
        display: 'grid',
        gridTemplateColumns: items.length > 6 ? '1fr 1fr' : '1fr',
        gap: '18px 60px',
        flex: 1,
        overflow: 'hidden',
        alignContent: 'start'
      }}>
        {items.map(item => (
          <div key={item.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 24, borderBottom: '1px solid rgba(255,255,255,0.12)', paddingBottom: 14 }}>
            <div style={{ minWidth: 0, flex: 1 }}>
              <div style={{ fontSize: 'clamp(1.4rem, 2.2vw, 2rem)', fontWeight: 800, lineHeight: 1.2 }}>
                {item.emoji ? `${item.emoji} ` : ''}{item.name}
              </div>
              {item.modifier_group_ids?.length > 0 && (
                <div style={{ fontSize: 'clamp(0.9rem, 1.2vw, 1.1rem)', color: 'rgba(255,255,255,0.65)', marginTop: 4 }}>
                  {item.modifier_group_ids.map(id => groupsById.get(id)?.name).filter(Boolean).join(' · ')}
                </div>
              )}
            </div>
            <div style={{ fontSize: 'clamp(1.4rem, 2.2vw, 2rem)', fontWeight: 900, whiteSpace: 'nowrap' }}>
              {item.price_type === 'open' ? '—' : formatForDisplay(item.price_cents, lang)}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function TvPageSlide({ url }) {
  return (
    <img src={url} alt="" style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} />
  );
}

const tvPageStyle = {
  position: 'fixed',
  inset: 0,
  background: '#0b0b0b',
  color: 'white',
  display: 'flex',
  flexDirection: 'column',
  fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  overflow: 'hidden'
};

const tvHeaderStyle = {
  padding: '24px 80px',
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  color: 'white'
};

const tvHeaderTitleStyle = {
  margin: 0,
  fontSize: 'clamp(1.4rem, 2.4vw, 2.4rem)',
  fontWeight: 900,
  letterSpacing: '-0.01em'
};

const tvDotsStyle = { display: 'flex', gap: 8 };
const tvDotStyle = { width: 10, height: 10, borderRadius: 999, display: 'inline-block' };

const tvSlideStyle = {
  flex: 1,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  transition: 'opacity 350ms ease',
  minHeight: 0
};

function LoadingState() {
  return <div style={centerStyle}>Cargando…</div>;
}

function EmptyState() {
  return <div style={centerStyle}>Menú vacío.</div>;
}

function ErrorState({ message }) {
  return (
    <div style={centerStyle}>
      <div>
        <p style={{ margin: 0, fontWeight: 700 }}>No se pudo cargar el menú.</p>
        <p style={{ marginTop: 8, fontSize: '0.85rem', color: '#888' }}>{message}</p>
      </div>
    </div>
  );
}

function ConfigMissing() {
  return (
    <div style={centerStyle}>
      <div>
        <p style={{ margin: 0, fontWeight: 700 }}>Enlace inválido.</p>
        <p style={{ marginTop: 8, fontSize: '0.85rem', color: '#888' }}>
          Faltan los parámetros del menú. Pide al negocio un enlace o QR actualizado.
        </p>
      </div>
    </div>
  );
}

const pageStyle = {
  minHeight: '100vh',
  background: '#fafafa',
  fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  color: '#222',
  paddingBottom: 'env(safe-area-inset-bottom)'
};

const headerStyle = {
  padding: '28px 20px 24px',
  color: 'white',
  textAlign: 'center'
};

const headerTitleStyle = {
  margin: 0,
  fontSize: '1.6rem',
  fontWeight: 800,
  letterSpacing: '-0.01em'
};

const navStyle = {
  display: 'flex',
  overflowX: 'auto',
  gap: 8,
  padding: '12px 16px',
  background: 'white',
  borderBottom: '1px solid #eee',
  position: 'sticky',
  top: 0,
  zIndex: 10,
  WebkitOverflowScrolling: 'touch'
};

const navButtonStyle = {
  background: 'transparent',
  border: 'none',
  borderBottom: '2px solid transparent',
  padding: '8px 4px',
  fontSize: '0.95rem',
  fontWeight: 700,
  cursor: 'pointer',
  whiteSpace: 'nowrap'
};

const mainStyle = { padding: '8px 16px 32px' };

const listStyle = {
  listStyle: 'none',
  margin: 0,
  padding: 0,
  display: 'flex',
  flexDirection: 'column',
  gap: 4
};

const itemStyle = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'flex-start',
  gap: 12,
  padding: '16px 4px',
  borderBottom: '1px solid #eee'
};

const itemLeftStyle = { display: 'flex', gap: 12, alignItems: 'flex-start', flex: 1, minWidth: 0 };
const emojiStyle = { fontSize: '1.5rem', lineHeight: 1, marginTop: 2 };
const imageStyle = {
  width: 72,
  maxHeight: 96,
  objectFit: 'cover',
  borderRadius: 10,
  flexShrink: 0,
  background: '#eee'
};
const itemNameStyle = { fontWeight: 700, fontSize: '1rem' };
const modifiersWrapStyle = { marginTop: 4 };
const priceStyle = { fontWeight: 800, fontSize: '1rem', whiteSpace: 'nowrap' };

const centerStyle = {
  minHeight: '100vh',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  padding: '24px',
  textAlign: 'center',
  color: '#444',
  fontFamily: 'system-ui, -apple-system, sans-serif'
};

export default PublicMenu;
