// Customer-facing menu. Read-only. No auth, no settings, no admin.
//
// Hits the Supabase get_active_menu() RPC (migration 015) with the
// publishable key. The resolver picks the right menu server-side based on
// priority + scheduled time windows (shop-local), with the catalog 'live'
// menu as always-on fallback. We re-fetch every 5 minutes so a scheduled
// menu swap (e.g. brunch → lunch at 11am) appears without restart.
//
// Response envelope (sanitized — internal fields never reach the client):
//   { menu: {id, kind, name, data}, shop, categories, modifier_groups }
// For kind='live' we render categories/modifier_groups (catalog view).
// For kind in ('pdf','image','designed') we render from menu.data — those
// renderers ship in later phases.
//
// Routed at /menu and bypasses every App.jsx gate. Two URL formats:
//
//   Short (preferred): /menu?p=PROJECT_REF
//     Derives Supabase URL from the ref, fetches the anon key from the
//     public menu bucket's config.json. Produces ~55-char QR-friendly URLs.
//
//   Legacy: /menu?u=BASE64_URL&k=BASE64_KEY
//     The shop's Supabase URL and publishable key arrive as base64-encoded
//     query params (generated by older MenuShareCard versions). Still
//     supported for backwards compatibility.

import { useEffect, useMemo, useRef, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
import { formatForDisplay } from '../utils/moneyUtils';
import { applyTheme, syncGoogleFontLink } from '../utils/menuTheme';
import CanvasRenderer from './menuCanvas/CanvasRenderer';

// Standard base64 → string. Tolerates URL-safe variants in case the link was
// rewritten by a QR scanner or messaging app.
function decodeParam(value) {
  if (!value) return '';
  try {
    const normalized = value.replace(/-/g, '+').replace(/_/g, '/');
    return atob(normalized);
  } catch {
    return '';
  }
}

function PublicMenu() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [activeCategoryId, setActiveCategoryId] = useState(null);
  const intervalRef = useRef(null);
  const isTvMode = typeof window !== 'undefined' && window.location.pathname === '/menu/tv';
  const isPrintMode = typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('print') === '1';

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const projectRef = params.get('p');

    // Short-URL path: ?p=PROJECT_REF. Derives the Supabase URL from the ref
    // and fetches the anon key from the public menu bucket's config.json.
    if (projectRef) {
      const supabaseUrl = `https://${projectRef}.supabase.co`;
      const configUrl = `${supabaseUrl}/storage/v1/object/public/menu/config.json`;

      let cancelled = false;
      (async () => {
        try {
          const res = await fetch(configUrl);
          if (!res.ok) throw new Error('Config not found');
          const config = await res.json();
          const publishableKey = config.k;
          if (!publishableKey) throw new Error('Missing key in config');
          if (cancelled) return;

          const client = createClient(supabaseUrl, publishableKey, {
            auth: { persistSession: false, autoRefreshToken: false }
          });

          const pinnedId = params.get('m');
          async function fetchMenu() {
            const { data, error } = pinnedId
              ? await client.rpc('get_menu_by_id', { p_id: Number(pinnedId) })
              : await client.rpc('get_active_menu');
            if (cancelled) return;
            if (error) { setError(error.message); return; }
            setData(data);
            setActiveCategoryId(prev => {
              if (prev && data?.categories?.some(c => c.id === prev)) return prev;
              return data?.categories?.[0]?.id ?? null;
            });
          }
          fetchMenu();
          const iv = setInterval(fetchMenu, 5 * 60 * 1000);
          // Stash cleanup ref so the outer return can clear it.
          intervalRef.current = iv;
        } catch (err) {
          if (!cancelled) setError(err.message || 'Failed to load menu config');
        }
      })();
      return () => {
        cancelled = true;
        if (intervalRef.current) clearInterval(intervalRef.current);
      };
    }

    // Legacy long-URL path: ?u=BASE64_URL&k=BASE64_KEY (backwards compat).
    const supabaseUrl = decodeParam(params.get('u'));
    const publishableKey = decodeParam(params.get('k'));

    if (!supabaseUrl || !publishableKey) {
      setError('missing-config');
      return;
    }

    const client = createClient(supabaseUrl, publishableKey, {
      auth: { persistSession: false, autoRefreshToken: false }
    });

    // ?m=<id> pins a specific menu (per-card share links), bypassing the
    // schedule resolver. Falls back to get_active_menu when absent.
    const pinnedId = params.get('m');
    let cancelled = false;
    async function fetchMenu() {
      const { data, error } = pinnedId
        ? await client.rpc('get_menu_by_id', { p_id: Number(pinnedId) })
        : await client.rpc('get_active_menu');
      if (cancelled) return;
      if (error) { setError(error.message); return; }
      setData(data);
      setActiveCategoryId(prev => {
        if (prev && data?.categories?.some(c => c.id === prev)) return prev;
        return data?.categories?.[0]?.id ?? null;
      });
    }
    fetchMenu();
    // Re-resolve every 5 min so scheduled swaps appear without a manual refresh.
    const iv = setInterval(fetchMenu, 5 * 60 * 1000);
    return () => { cancelled = true; clearInterval(iv); };
  }, []);

  const groupsById = useMemo(() => {
    const m = new Map();
    (data?.modifier_groups || []).forEach(g => m.set(g.id, g));
    return m;
  }, [data]);

  if (error === 'missing-config') return <ConfigMissing />;
  if (error) return <ErrorState message={error} />;
  if (!data) return <LoadingState />;

  const shop = data.shop || {};
  const brand = shop.brand_color || '#f28b05';
  const lang = shop.language || 'es';
  const menuKind = data.menu?.kind || 'live';
  // Live mode shows out-of-stock items with an "Agotado" badge (rather than
  // hiding them) so a coffee list can advertise the whole lineup and its
  // freshness. Owners who prefer the old hide-when-sold-out behavior can set
  // menu.data.hide_out_of_stock = true on the menu row.
  const hideOos = data.menu?.data?.hide_out_of_stock === true;
  const categories = (data.categories || [])
    .map(c => ({ ...c, items: hideOos ? c.items.filter(it => it.available !== false) : c.items }));
  const activeCategory = categories.find(c => c.id === activeCategoryId) || categories[0];
  // Modifier groups show under each item by default; owners can hide them per
  // menu via menu.data.show_modifiers (set in the menu editor).
  const showModifiers = data.menu?.data?.show_modifiers !== false;

  if (isTvMode) {
    return <TvMode data={data} brand={brand} lang={lang} />;
  }

  // Designer kind:
  //   - menu.data.document present → freeform canvas (Phase 4c) renders it.
  //   - otherwise → template-mode (Phase 4a) renders categories via the
  //     chosen template + theme.
  if (menuKind === 'designed') {
    if (data.menu?.data?.document) {
      if (isPrintMode) {
        return <PrintWrapper enabled>
          <CanvasRenderer document={data.menu.data.document} data={data} lang={lang} isPrint />
        </PrintWrapper>;
      }
      // The global `body { overflow: hidden }` (POS anti-bounce in index.css)
      // would otherwise trap the page stack, so the canvas renderer needs its
      // own scroll container for multi-page / tall (9:16) documents.
      return (
        <div className="tinymenu-scroll" style={{ height: '100dvh', overflowY: 'auto', overflowX: 'hidden', background: '#0a0a0a', WebkitOverflowScrolling: 'touch' }}>
          <CanvasRenderer document={data.menu.data.document} data={data} lang={lang} />
        </div>
      );
    }
    return <TemplatedMenu data={data} brand={brand} lang={lang} />;
  }

  // Uploaded PDF/image kinds render as a page carousel from menu.data.pages.
  if (menuKind === 'pdf' || menuKind === 'image') {
    return (
      <div className="tinymenu-scroll" style={pageStyle}>
        <header style={{ ...headerStyle, background: brand }}>
          <h1 style={headerTitleStyle}>{shop.name || 'Menu'}</h1>
        </header>
        <UploadedMenu menu={data.menu} brand={brand} />
      </div>
    );
  }

  // kind='designed' renderer ships in Phase 4. Placeholder for now.
  if (menuKind !== 'live') {
    return (
      <div className="tinymenu-scroll" style={pageStyle}>
        <header style={{ ...headerStyle, background: brand }}>
          <h1 style={headerTitleStyle}>{shop.name || 'Menu'}</h1>
        </header>
        <div style={centerStyle}>
          <div>
            <p style={{ margin: 0, fontWeight: 700 }}>{data.menu?.name || 'Menú'}</p>
            <p style={{ marginTop: 8, fontSize: '0.85rem', color: '#888' }}>
              Este formato de menú ({menuKind}) aún no está disponible para mostrar.
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="tinymenu-scroll" style={pageStyle}>
      <header style={{ ...headerStyle, background: brand }}>
        <h1 style={headerTitleStyle}>{shop.name || 'Menu'}</h1>
      </header>

      {categories.length === 0 ? (
        <EmptyState />
      ) : (
        <>
          <nav style={navStyle} aria-label="Categorías">
            {categories.map(c => {
              const isActive = c.id === activeCategory?.id;
              return (
                <button
                  key={c.id}
                  onClick={() => setActiveCategoryId(c.id)}
                  style={{
                    ...navButtonStyle,
                    color: isActive ? brand : '#555',
                    borderBottomColor: isActive ? brand : 'transparent'
                  }}
                >
                  {c.name}
                </button>
              );
            })}
          </nav>

          <main style={mainStyle}>
            {activeCategory && (
              <ItemList
                items={activeCategory.items}
                groupsById={groupsById}
                lang={lang}
                brand={brand}
                showModifiers={showModifiers}
              />
            )}
          </main>
        </>
      )}
    </div>
  );
}

function ItemList({ items, groupsById, lang, brand, showModifiers = true }) {
  if (!items || items.length === 0) {
    return <p style={{ textAlign: 'center', color: '#888', padding: '40px 16px' }}>—</p>;
  }
  return (
    <ul style={listStyle}>
      {items.map(item => {
        const soldOut = item.available === false;
        return (
        <li key={item.id} style={{ ...itemStyle, opacity: soldOut ? 0.55 : 1 }}>
          <div style={itemLeftStyle}>
            {item.image_url ? (
              <img
                src={item.image_url}
                alt=""
                loading="lazy"
                style={{ ...imageStyle, filter: soldOut ? 'grayscale(1)' : 'none' }}
              />
            ) : (
              <span style={emojiStyle} aria-hidden>{item.emoji || '•'}</span>
            )}
            <div>
              <div style={itemNameStyle}>
                {item.name}
                {soldOut && <span style={soldOutBadgeStyle}>{lang === 'en' ? 'Sold out' : 'Agotado'}</span>}
              </div>
              <RoastLine roastDate={item.roast_date} lang={lang} />
              {showModifiers && item.modifier_group_ids?.length > 0 && (
                <ItemModifiers groupIds={item.modifier_group_ids} groupsById={groupsById} lang={lang} brand={brand} />
              )}
              {item.whatsapp_url && (
                <WhatsAppButton url={item.whatsapp_url} lang={lang} />
              )}
            </div>
          </div>
          <div style={priceStyle}>
            {item.price_type === 'open'
              ? <span style={{ color: '#888', fontWeight: 600 }}>—</span>
              : formatForDisplay(item.price_cents, lang)}
          </div>
        </li>
        );
      })}
    </ul>
  );
}

// Roast-date line — shows the date plus a relative freshness hint ("hace 3
// días") because that's what a coffee buyer actually cares about. Renders
// nothing for a missing/unparseable date so non-coffee items stay clean.
function RoastLine({ roastDate, lang }) {
  const label = formatRoastDate(roastDate, lang);
  if (!label) return null;
  return (
    <div style={{ fontSize: '0.78rem', color: '#8a6d3b', fontWeight: 600, marginTop: 3 }}>
      🔥 {label}
    </div>
  );
}

function formatRoastDate(value, lang) {
  if (!value) return null;
  const d = new Date(`${value}T00:00:00`);
  if (Number.isNaN(d.getTime())) return null;
  const en = lang === 'en';
  const dateStr = d.toLocaleDateString(en ? 'en-US' : 'es-MX', { day: 'numeric', month: 'short', year: 'numeric' });
  const today = new Date();
  const days = Math.floor((new Date(today.getFullYear(), today.getMonth(), today.getDate()) - new Date(d.getFullYear(), d.getMonth(), d.getDate())) / 86400000);
  const roasted = en ? 'Roasted' : 'Tostado';
  if (days <= 0) return `${roasted}: ${dateStr} · ${en ? 'today' : 'hoy'}`;
  const ago = en ? `${days} day${days === 1 ? '' : 's'} ago` : `hace ${days} día${days === 1 ? '' : 's'}`;
  return `${roasted}: ${dateStr} · ${ago}`;
}

// "Order on WhatsApp" button. Opens the owner-pasted catalog/wa.me link in a
// new tab. Stops click bubbling so it never triggers surrounding row handlers.
function WhatsAppButton({ url, lang }) {
  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      onClick={e => e.stopPropagation()}
      style={{
        display: 'inline-flex', alignItems: 'center', gap: 6, marginTop: 8,
        padding: '7px 12px', borderRadius: 999, background: '#25D366', color: 'white',
        fontWeight: 800, fontSize: '0.8rem', textDecoration: 'none'
      }}
    >
      <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor" aria-hidden>
        <path d="M12.04 2C6.58 2 2.13 6.45 2.13 11.91c0 1.76.46 3.45 1.34 4.95L2 22l5.25-1.38a9.9 9.9 0 0 0 4.79 1.22h.01c5.46 0 9.91-4.45 9.91-9.91 0-2.65-1.03-5.14-2.9-7.01A9.82 9.82 0 0 0 12.04 2Zm5.8 14.16c-.24.68-1.4 1.3-1.94 1.35-.5.05-.98.23-3.3-.69-2.78-1.1-4.56-3.94-4.7-4.13-.14-.19-1.13-1.5-1.13-2.86 0-1.36.71-2.03.97-2.31.24-.26.53-.32.7-.32.18 0 .35 0 .5.01.16.01.38-.06.59.45.24.58.81 2 .88 2.15.07.14.12.31.02.5-.09.19-.14.31-.28.48-.14.16-.29.36-.42.48-.14.14-.28.29-.12.57.16.28.72 1.19 1.55 1.93 1.06.95 1.96 1.24 2.24 1.38.28.14.44.12.6-.07.16-.19.69-.81.88-1.09.18-.28.37-.23.62-.14.25.09 1.61.76 1.89.9.28.14.46.21.53.32.07.12.07.66-.17 1.34Z"/>
      </svg>
      {lang === 'en' ? 'Order on WhatsApp' : 'Pedir por WhatsApp'}
    </a>
  );
}

function ItemModifiers({ groupIds, groupsById, lang, brand }) {
  const groups = groupIds.map(id => groupsById.get(id)).filter(Boolean);
  if (groups.length === 0) return null;
  return (
    <div style={modifiersWrapStyle}>
      {groups.map(g => (
        <div key={g.id} style={{ marginTop: 6 }}>
          <div style={{ fontSize: '0.75rem', color: brand, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            {g.name}
          </div>
          <div style={{ fontSize: '0.85rem', color: '#666', marginTop: 2 }}>
            {g.options.map((o, idx) => {
              const delta = o.price_delta_cents;
              const label = delta ? `${o.name} ${delta > 0 ? '+' : ''}${formatForDisplay(delta, lang)}` : o.name;
              return (
                <span key={o.id}>
                  {idx > 0 && <span style={{ color: '#ccc' }}> · </span>}
                  {label}
                </span>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}

// Swipeable page carousel for pdf/image kinds. Touch swipes via touchstart/end
// deltas (no library); keyboard arrows work too. Single-page menus skip the
// chrome entirely so they look like a clean poster.
function UploadedMenu({ menu, brand }) {
  const pages = menu?.data?.pages || [];
  const originalUrl = menu?.data?.original_url;
  const [idx, setIdx] = useState(0);
  const touchX = useRef(null);

  useEffect(() => {
    function onKey(e) {
      if (e.key === 'ArrowRight') setIdx(i => Math.min(pages.length - 1, i + 1));
      if (e.key === 'ArrowLeft')  setIdx(i => Math.max(0, i - 1));
    }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [pages.length]);

  if (pages.length === 0) {
    return <div style={centerStyle}>Menú vacío.</div>;
  }

  const onTouchStart = e => { touchX.current = e.touches[0].clientX; };
  const onTouchEnd = e => {
    if (touchX.current == null) return;
    const dx = e.changedTouches[0].clientX - touchX.current;
    if (dx > 50) setIdx(i => Math.max(0, i - 1));
    else if (dx < -50) setIdx(i => Math.min(pages.length - 1, i + 1));
    touchX.current = null;
  };

  return (
    <div style={{ padding: '12px 0 32px' }}>
      <div
        style={{
          position: 'relative',
          background: '#000',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          minHeight: 'min(80vh, 720px)',
          overflow: 'hidden'
        }}
        onTouchStart={onTouchStart}
        onTouchEnd={onTouchEnd}
      >
        <img
          src={pages[idx]}
          alt={`Página ${idx + 1}`}
          style={{ maxWidth: '100%', maxHeight: '80vh', objectFit: 'contain', display: 'block' }}
        />
        {pages.length > 1 && (
          <>
            <button onClick={() => setIdx(i => Math.max(0, i - 1))} disabled={idx === 0} style={{ ...carouselBtn, left: 12 }} aria-label="Anterior">
              ‹
            </button>
            <button onClick={() => setIdx(i => Math.min(pages.length - 1, i + 1))} disabled={idx === pages.length - 1} style={{ ...carouselBtn, right: 12 }} aria-label="Siguiente">
              ›
            </button>
          </>
        )}
      </div>

      {pages.length > 1 && (
        <div style={{ display: 'flex', justifyContent: 'center', gap: 6, padding: '14px 16px 0' }}>
          {pages.map((_, i) => (
            <button
              key={i}
              onClick={() => setIdx(i)}
              aria-label={`Página ${i + 1}`}
              style={{
                width: 10, height: 10, borderRadius: 999, border: 'none', padding: 0,
                background: i === idx ? brand : '#ccc', cursor: 'pointer'
              }}
            />
          ))}
        </div>
      )}

      {originalUrl && (
        <div style={{ textAlign: 'center', padding: '18px 16px 0' }}>
          <a
            href={originalUrl}
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: brand, fontWeight: 700, textDecoration: 'none', fontSize: '0.9rem' }}
          >
            Descargar PDF original ↓
          </a>
        </div>
      )}
    </div>
  );
}

const carouselBtn = {
  position: 'absolute',
  top: '50%',
  transform: 'translateY(-50%)',
  width: 44, height: 44,
  borderRadius: 999,
  border: 'none',
  background: 'rgba(255,255,255,0.85)',
  color: '#222',
  fontSize: '1.8rem',
  fontWeight: 700,
  cursor: 'pointer',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  lineHeight: 1
};

// Print mode wrapper. Fires window.print() once on mount so the user lands
// in the print dialog without an extra click. Browsers handle the rest —
// the @page CSS injected by CanvasRenderer's PrintStack tells them what
// paper size to use.
function PrintWrapper({ enabled, children }) {
  useEffect(() => {
    if (!enabled) return;
    const t = setTimeout(() => { try { window.print(); } catch { /* ignore */ } }, 400);
    return () => clearTimeout(t);
  }, [enabled]);
  return children;
}

// Phase 4a templates. All three templates take the same props and render the
// catalog payload returned by get_active_menu (kind='designed' gets the same
// shape as 'live'). Bindings stay live — prices, hidden state, and modifier
// groups flow through automatically because the customer fetches the same RPC.
function TemplatedMenu({ data, brand, lang }) {
  const menu = data.menu || {};
  const opts = menu.data || {};
  const wanted = opts.category_names && opts.category_names.length > 0
    ? new Set(opts.category_names)
    : null;
  const hideOos = opts.hide_out_of_stock !== false; // default ON for templates
  const showModifiers = opts.show_modifiers !== false; // default ON
  const listShowImages = opts.list_show_images === true; // list template only, default OFF (emoji)
  const categories = (data.categories || [])
    .filter(c => !wanted || wanted.has(c.name))
    .map(c => hideOos ? { ...c, items: c.items.filter(it => it.available !== false) } : c);
  const groupsById = mapGroups(data.modifier_groups);

  const template = opts.template || 'list';
  const defaults =
    template === 'chalkboard' ? { background: '#1d2e25', text: '#f5f0e1' } :
    template === 'cards'      ? { background: '#f3f1ee', text: '#1a1a1a' } :
                                { background: '#fafafa', text: '#222'    };
  // accent_color from Phase 4a still wins if user set it before themes existed.
  const themeIn = { ...(opts.theme || {}), accent: (opts.theme?.accent || opts.accent_color) };
  const theme = applyTheme(themeIn, brand, defaults);

  useEffect(() => { syncGoogleFontLink(theme.googleFontUrl); }, [theme.googleFontUrl]);

  const TemplateCmp =
    template === 'cards'      ? CardsTemplate :
    template === 'chalkboard' ? ChalkboardTemplate :
                                ListTemplate;

  // Own scroll container: the global `body { overflow: hidden }` (POS
  // anti-bounce in index.css) would otherwise clip a template taller than the
  // viewport. The template paints its own full-height background inside.
  return (
    <div className="tinymenu-scroll" style={templateScrollStyle}>
      <TemplateCmp
        shopName={data.shop?.name || 'Menu'}
        menuName={menu.name || ''}
        categories={categories}
        groupsById={groupsById}
        theme={theme}
        lang={lang}
        showModifiers={showModifiers}
        showImages={listShowImages}
      />
    </div>
  );
}

const templateScrollStyle = {
  height: '100dvh',
  overflowY: 'auto',
  overflowX: 'hidden',
  WebkitOverflowScrolling: 'touch'
};

function ListTemplate({ shopName, menuName, categories, groupsById, theme, lang, showModifiers = true, showImages = false }) {
  const { fontFamily, background, text, accent, density } = theme;
  // When images are on, size the thumbnail off the row density so denser
  // menus stay compact. Falls back to the emoji in a tinted box when an item
  // has no image, keeping every row aligned.
  const thumb = Math.max(44, density.gap * 5);
  return (
    <div style={{ minHeight: '100vh', background, fontFamily, color: text, paddingBottom: 'env(safe-area-inset-bottom)' }}>
      <header style={{ padding: `${density.pad + 12}px 20px ${density.pad}px`, textAlign: 'center', background: accent, color: 'white' }}>
        <h1 style={{ margin: 0, fontSize: '1.8rem', fontWeight: 900, letterSpacing: '-0.01em' }}>{shopName}</h1>
        {menuName && <p style={{ margin: '6px 0 0', opacity: 0.85, fontWeight: 600 }}>{menuName}</p>}
      </header>
      <main style={{ padding: `${density.pad}px 16px 40px`, maxWidth: 720, margin: '0 auto' }}>
        {categories.map(c => (
          <section key={c.id} style={{ marginBottom: density.sectionGap }}>
            <h2 style={{ margin: `0 0 ${density.gap}px`, fontSize: '1.4rem', color: accent, fontWeight: 800, borderBottom: `2px solid ${accent}`, paddingBottom: 6 }}>{c.name}</h2>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 4 }}>
              {c.items.map(it => (
                <li key={it.id} style={{ display: 'flex', justifyContent: 'space-between', gap: 12, padding: `${density.gap}px 4px`, borderBottom: '1px solid rgba(0,0,0,0.08)', alignItems: 'center' }}>
                  {showImages && (
                    it.image_url ? (
                      <img src={it.image_url} alt="" loading="lazy" style={{ width: thumb, height: thumb, flexShrink: 0, borderRadius: 10, objectFit: 'cover', display: 'block' }} />
                    ) : (
                      <div style={{ width: thumb, height: thumb, flexShrink: 0, borderRadius: 10, background: `${accent}1a`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: thumb * 0.5 }}>{it.emoji || '•'}</div>
                    )
                  )}
                  <div style={{ minWidth: 0, flex: 1 }}>
                    <div style={{ fontWeight: 700 }}>{!showImages && it.emoji ? `${it.emoji} ` : ''}{it.name}</div>
                    {showModifiers && it.modifier_group_ids?.length > 0 && (
                      <div style={{ fontSize: '0.8rem', opacity: 0.6, marginTop: 2 }}>
                        {it.modifier_group_ids.map(id => groupsById.get(id)?.name).filter(Boolean).join(' · ')}
                      </div>
                    )}
                    <RoastLine roastDate={it.roast_date} lang={lang} />
                    {it.whatsapp_url && <WhatsAppButton url={it.whatsapp_url} lang={lang} />}
                  </div>
                  <div style={{ fontWeight: 800, whiteSpace: 'nowrap' }}>
                    {it.price_type === 'open' ? '—' : formatForDisplay(it.price_cents, lang)}
                  </div>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </main>
    </div>
  );
}

function CardsTemplate({ shopName, menuName, categories, groupsById, theme, lang, showModifiers = true }) {
  const { fontFamily, background, text, accent, density } = theme;
  return (
    <div style={{ minHeight: '100vh', background, fontFamily, color: text, paddingBottom: 'env(safe-area-inset-bottom)' }}>
      <header style={{ padding: `${density.pad + 20}px 20px ${density.pad + 8}px`, textAlign: 'center' }}>
        <div style={{ display: 'inline-block', padding: '4px 14px', borderRadius: 999, background: accent, color: 'white', fontSize: '0.75rem', fontWeight: 800, letterSpacing: '0.1em', textTransform: 'uppercase' }}>
          {menuName || 'Menú'}
        </div>
        <h1 style={{ margin: '14px 0 0', fontSize: '2rem', fontWeight: 900, letterSpacing: '-0.02em' }}>{shopName}</h1>
      </header>
      <main style={{ padding: '0 16px 40px', maxWidth: 980, margin: '0 auto' }}>
        {categories.map(c => (
          <section key={c.id} style={{ marginBottom: density.sectionGap }}>
            <h2 style={{ margin: `0 0 ${density.gap + 4}px`, fontSize: '1.5rem', fontWeight: 900, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{c.name}</h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: density.gap + 4 }}>
              {c.items.map(it => (
                <article key={it.id} style={{ background: 'white', borderRadius: 16, overflow: 'hidden', boxShadow: '0 8px 24px rgba(0,0,0,0.06)', display: 'flex', flexDirection: 'column' }}>
                  {it.image_url ? (
                    <img src={it.image_url} alt="" loading="lazy" style={{ width: '100%', aspectRatio: '4/3', objectFit: 'cover', display: 'block' }} />
                  ) : (
                    <div style={{ aspectRatio: '4/3', background: '#eee', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '3rem' }}>{it.emoji || '•'}</div>
                  )}
                  <div style={{ padding: 14, display: 'flex', flexDirection: 'column', gap: 8, flex: 1 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, alignItems: 'baseline' }}>
                      <h3 style={{ margin: 0, fontSize: '1.05rem', fontWeight: 800, lineHeight: 1.2 }}>{it.name}</h3>
                      <span style={{ fontWeight: 900, color: accent, whiteSpace: 'nowrap' }}>
                        {it.price_type === 'open' ? '—' : formatForDisplay(it.price_cents, lang)}
                      </span>
                    </div>
                    {showModifiers && it.modifier_group_ids?.length > 0 && (
                      <div style={{ fontSize: '0.78rem', opacity: 0.55 }}>
                        {it.modifier_group_ids.map(id => groupsById.get(id)?.name).filter(Boolean).join(' · ')}
                      </div>
                    )}
                    <RoastLine roastDate={it.roast_date} lang={lang} />
                    {it.whatsapp_url && <WhatsAppButton url={it.whatsapp_url} lang={lang} />}
                  </div>
                </article>
              ))}
            </div>
          </section>
        ))}
      </main>
    </div>
  );
}

function ChalkboardTemplate({ shopName, menuName, categories, groupsById, theme, lang, showModifiers = true }) {
  // Defaults give the original chalkboard look without a theme; user
  // overrides flow in via applyTheme — pick a lighter background + serif
  // font and you've got a wedding-menu vibe instead.
  const { fontFamily, background, text, accent, density } = theme;
  return (
    <div style={{ minHeight: '100vh', background, color: text, fontFamily, paddingBottom: 'env(safe-area-inset-bottom)' }}>
      <header style={{ padding: `${density.pad + 20}px 20px ${density.pad + 4}px`, textAlign: 'center', borderBottom: `1px dashed ${text}55` }}>
        <h1 style={{ margin: 0, fontSize: '2.4rem', fontWeight: 700, letterSpacing: '0.02em', color: accent }}>{shopName}</h1>
        {menuName && <p style={{ margin: '6px 0 0', opacity: 0.8 }}>~ {menuName} ~</p>}
      </header>
      <main style={{ padding: `${density.pad + 4}px 20px 40px`, maxWidth: 780, margin: '0 auto' }}>
        {categories.map(c => (
          <section key={c.id} style={{ marginBottom: density.sectionGap }}>
            <h2 style={{ margin: `0 0 ${density.gap + 2}px`, fontSize: '1.8rem', color: accent, textAlign: 'center' }}>· {c.name} ·</h2>
            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: density.gap - 2 }}>
              {c.items.map(it => (
                <li key={it.id} style={{ display: 'flex', justifyContent: 'space-between', gap: 14, padding: '8px 0', borderBottom: `1px dotted ${text}33` }}>
                  <div style={{ minWidth: 0, fontSize: '1.15rem' }}>
                    {it.emoji ? `${it.emoji} ` : ''}{it.name}
                    {showModifiers && it.modifier_group_ids?.length > 0 && (
                      <div style={{ fontSize: '0.85rem', opacity: 0.6, marginTop: 2 }}>
                        {it.modifier_group_ids.map(id => groupsById.get(id)?.name).filter(Boolean).join(' · ')}
                      </div>
                    )}
                  </div>
                  <div style={{ fontSize: '1.25rem', whiteSpace: 'nowrap' }}>
                    {it.price_type === 'open' ? '—' : formatForDisplay(it.price_cents, lang)}
                  </div>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </main>
    </div>
  );
}

// Full-screen kiosk mode at /menu/tv. Requests Wake Lock so tablet screens
// stay on, auto-rotates slides every `rotation_ms` (configurable on the menu
// row's data, default 12s), and crossfades between slides. Re-fetch is
// handled by the parent's 5-min interval, so a scheduled menu swap shows up
// automatically without restart.
//
// Slide set depends on menu kind:
//   live           — one slide per category
//   pdf / image    — one slide per page
//   designed       — placeholder slide (renderer ships in Phase 4)
function TvMode({ data, brand, lang }) {
  const menu = data.menu || {};
  const kind = menu.kind || 'live';
  const rotationMs = Math.max(3000, menu.data?.rotation_ms || 12000);
  const showModifiers = menu.data?.show_modifiers !== false;

  const slides = useMemo(() => {
    // Canvas-mode designed menus → one slide per document page. Beats the
    // category-list fallback because the owner picked exactly the layout
    // they want on the screen.
    if (kind === 'designed' && menu.data?.document?.pages?.length) {
      return menu.data.document.pages.map((_, i) => ({
        key: `canvaspg-${i}`, kind: 'canvas-page', payload: { index: i }
      }));
    }
    if (kind === 'live' || kind === 'designed') {
      const wanted = menu.data?.category_names && menu.data.category_names.length > 0
        ? new Set(menu.data.category_names)
        : null;
      // TV always hides out-of-stock items — a kiosk advertising sold-out
      // items is the worst case for this feature.
      const cats = (data.categories || [])
        .filter(c => !wanted || wanted.has(c.name))
        .map(c => ({ ...c, items: c.items.filter(it => it.available !== false) }));
      return cats.map(c => ({ key: `cat-${c.id}`, kind: 'category', payload: c }));
    }
    if (kind === 'pdf' || kind === 'image') {
      return (menu.data?.pages || []).map((url, i) => ({ key: `pg-${i}`, kind: 'page', payload: { url, index: i } }));
    }
    return [{ key: 'placeholder', kind: 'placeholder', payload: null }];
  }, [data, kind, menu.data]);

  const [idx, setIdx] = useState(0);
  const [visible, setVisible] = useState(true);

  // Reset index when slide set shrinks (e.g. a category was hidden).
  useEffect(() => {
    if (idx >= slides.length) setIdx(0);
  }, [slides.length, idx]);

  // Rotation: hide → swap → show, for a clean crossfade.
  useEffect(() => {
    if (slides.length <= 1) return;
    const tick = setInterval(() => {
      setVisible(false);
      setTimeout(() => {
        setIdx(i => (i + 1) % slides.length);
        setVisible(true);
      }, 350);
    }, rotationMs);
    return () => clearInterval(tick);
  }, [slides.length, rotationMs]);

  // Wake Lock — quiet best-effort. Some browsers require a gesture; if the
  // request rejects we just let the screen sleep rather than nag the viewer.
  useEffect(() => {
    let sentinel = null;
    let released = false;
    async function acquire() {
      try {
        if ('wakeLock' in navigator) {
          sentinel = await navigator.wakeLock.request('screen');
        }
      } catch { /* ignore */ }
    }
    function onVisibility() {
      // Browsers auto-release on tab hide; reacquire when shown again.
      if (document.visibilityState === 'visible' && !released) acquire();
    }
    acquire();
    document.addEventListener('visibilitychange', onVisibility);
    return () => {
      released = true;
      document.removeEventListener('visibilitychange', onVisibility);
      if (sentinel) sentinel.release().catch(() => {});
    };
  }, []);

  const slide = slides[idx];

  // Canvas-designed menus own the whole screen — the document IS the design,
  // so skip the brand header/dots chrome and render edge-to-edge from the
  // top-left on a black backdrop. (The header was the orange bar bleeding in.)
  if (slide?.kind === 'canvas-page') {
    return (
      <div style={{ position: 'fixed', inset: 0, background: '#000', overflow: 'hidden' }}>
        <div style={{ width: '100%', height: '100%', opacity: visible ? 1 : 0, transition: 'opacity 0.35s ease' }}>
          <CanvasRenderer
            document={menu.data.document}
            data={data}
            lang={lang}
            isTv={true}
            tvPageIndex={slide.payload.index}
          />
        </div>
      </div>
    );
  }

  return (
    <div style={tvPageStyle}>
      <div style={{ ...tvHeaderStyle, background: brand }}>
        <h1 style={tvHeaderTitleStyle}>{data.shop?.name || 'Menu'}</h1>
        {slides.length > 1 && (
          <div style={tvDotsStyle}>
            {slides.map((_, i) => (
              <span key={i} style={{ ...tvDotStyle, background: i === idx ? 'white' : 'rgba(255,255,255,0.35)' }} />
            ))}
          </div>
        )}
      </div>
      <div style={{ ...tvSlideStyle, opacity: visible ? 1 : 0 }}>
        {slide?.kind === 'category' && <TvCategorySlide category={slide.payload} groupsById={mapGroups(data.modifier_groups)} lang={lang} brand={brand} showModifiers={showModifiers} />}
        {slide?.kind === 'page' && <TvPageSlide url={slide.payload.url} />}
        {slide?.kind === 'canvas-page' && (
          <CanvasRenderer
            document={menu.data.document}
            data={data}
            lang={lang}
            isTv={true}
            tvPageIndex={slide.payload.index}
          />
        )}
        {slide?.kind === 'placeholder' && (
          <div style={{ color: 'rgba(255,255,255,0.6)', fontSize: '1.5rem' }}>
            {menu.name || 'Menú'} — formato no disponible aún
          </div>
        )}
      </div>
    </div>
  );
}

function mapGroups(groups) {
  const m = new Map();
  (groups || []).forEach(g => m.set(g.id, g));
  return m;
}

function TvCategorySlide({ category, groupsById, lang, brand, showModifiers = true }) {
  const items = category?.items || [];
  return (
    <div style={{ width: '100%', height: '100%', padding: '40px 80px 60px', display: 'flex', flexDirection: 'column', gap: 40, color: 'white' }}>
      <h2 style={{ margin: 0, fontSize: 'clamp(2.5rem, 5vw, 4.5rem)', fontWeight: 900, letterSpacing: '-0.02em', color: brand }}>
        {category?.name || ''}
      </h2>
      <div style={{
        display: 'grid',
        gridTemplateColumns: items.length > 6 ? '1fr 1fr' : '1fr',
        gap: '18px 60px',
        flex: 1,
        overflow: 'hidden',
        alignContent: 'start'
      }}>
        {items.map(item => (
          <div key={item.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 24, borderBottom: '1px solid rgba(255,255,255,0.12)', paddingBottom: 14 }}>
            <div style={{ minWidth: 0, flex: 1 }}>
              <div style={{ fontSize: 'clamp(1.4rem, 2.2vw, 2rem)', fontWeight: 800, lineHeight: 1.2 }}>
                {item.emoji ? `${item.emoji} ` : ''}{item.name}
              </div>
              {showModifiers && item.modifier_group_ids?.length > 0 && (
                <div style={{ fontSize: 'clamp(0.9rem, 1.2vw, 1.1rem)', color: 'rgba(255,255,255,0.65)', marginTop: 4 }}>
                  {item.modifier_group_ids.map(id => groupsById.get(id)?.name).filter(Boolean).join(' · ')}
                </div>
              )}
            </div>
            <div style={{ fontSize: 'clamp(1.4rem, 2.2vw, 2rem)', fontWeight: 900, whiteSpace: 'nowrap' }}>
              {item.price_type === 'open' ? '—' : formatForDisplay(item.price_cents, lang)}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function TvPageSlide({ url }) {
  return (
    <img src={url} alt="" style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} />
  );
}

const tvPageStyle = {
  position: 'fixed',
  inset: 0,
  background: '#0b0b0b',
  color: 'white',
  display: 'flex',
  flexDirection: 'column',
  fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  overflow: 'hidden'
};

const tvHeaderStyle = {
  padding: '24px 80px',
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  color: 'white'
};

const tvHeaderTitleStyle = {
  margin: 0,
  fontSize: 'clamp(1.4rem, 2.4vw, 2.4rem)',
  fontWeight: 900,
  letterSpacing: '-0.01em'
};

const tvDotsStyle = { display: 'flex', gap: 8 };
const tvDotStyle = { width: 10, height: 10, borderRadius: 999, display: 'inline-block' };

const tvSlideStyle = {
  flex: 1,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  transition: 'opacity 350ms ease',
  minHeight: 0
};

function LoadingState() {
  return <div style={centerStyle}>Cargando…</div>;
}

function EmptyState() {
  return <div style={centerStyle}>Menú vacío.</div>;
}

function ErrorState({ message }) {
  return (
    <div style={centerStyle}>
      <div>
        <p style={{ margin: 0, fontWeight: 700 }}>No se pudo cargar el menú.</p>
        <p style={{ marginTop: 8, fontSize: '0.85rem', color: '#888' }}>{message}</p>
      </div>
    </div>
  );
}

function ConfigMissing() {
  return (
    <div style={centerStyle}>
      <div>
        <p style={{ margin: 0, fontWeight: 700 }}>Enlace inválido.</p>
        <p style={{ marginTop: 8, fontSize: '0.85rem', color: '#888' }}>
          Faltan los parámetros del menú. Pide al negocio un enlace o QR actualizado.
        </p>
      </div>
    </div>
  );
}

const pageStyle = {
  // Own scroll container: the global `body { overflow: hidden }` (POS
  // anti-bounce in index.css) would otherwise trap a menu taller than the
  // viewport, so the public page scrolls itself instead of the body.
  height: '100dvh',
  overflowY: 'auto',
  overflowX: 'hidden',
  WebkitOverflowScrolling: 'touch',
  background: '#fafafa',
  fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  color: '#222',
  paddingBottom: 'env(safe-area-inset-bottom)'
};

const headerStyle = {
  padding: '28px 20px 24px',
  color: 'white',
  textAlign: 'center'
};

const headerTitleStyle = {
  margin: 0,
  fontSize: '1.6rem',
  fontWeight: 800,
  letterSpacing: '-0.01em'
};

const navStyle = {
  display: 'flex',
  overflowX: 'auto',
  gap: 8,
  padding: '12px 16px',
  background: 'white',
  borderBottom: '1px solid #eee',
  position: 'sticky',
  top: 0,
  zIndex: 10,
  WebkitOverflowScrolling: 'touch'
};

const navButtonStyle = {
  background: 'transparent',
  border: 'none',
  borderBottom: '2px solid transparent',
  padding: '8px 4px',
  fontSize: '0.95rem',
  fontWeight: 700,
  cursor: 'pointer',
  whiteSpace: 'nowrap'
};

const mainStyle = { padding: '8px 16px 32px' };

const listStyle = {
  listStyle: 'none',
  margin: 0,
  padding: 0,
  display: 'flex',
  flexDirection: 'column',
  gap: 4
};

const itemStyle = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'flex-start',
  gap: 12,
  padding: '16px 4px',
  borderBottom: '1px solid #eee'
};

const itemLeftStyle = { display: 'flex', gap: 12, alignItems: 'flex-start', flex: 1, minWidth: 0 };
const emojiStyle = { fontSize: '1.5rem', lineHeight: 1, marginTop: 2 };
const imageStyle = {
  width: 72,
  maxHeight: 96,
  objectFit: 'cover',
  borderRadius: 10,
  flexShrink: 0,
  background: '#eee'
};
const itemNameStyle = { fontWeight: 700, fontSize: '1rem' };
const soldOutBadgeStyle = {
  marginLeft: 8,
  fontSize: '0.65rem',
  fontWeight: 800,
  textTransform: 'uppercase',
  letterSpacing: '0.05em',
  color: '#c0392b',
  background: 'rgba(192,57,43,0.1)',
  padding: '2px 7px',
  borderRadius: 999,
  verticalAlign: 'middle',
  whiteSpace: 'nowrap'
};
const modifiersWrapStyle = { marginTop: 4 };
const priceStyle = { fontWeight: 800, fontSize: '1rem', whiteSpace: 'nowrap' };

const centerStyle = {
  minHeight: '100vh',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  padding: '24px',
  textAlign: 'center',
  color: '#444',
  fontFamily: 'system-ui, -apple-system, sans-serif'
};

export default PublicMenu;
