import { useState, useRef, useEffect } from 'react';
import { Icon } from '@iconify/react';
import { supabase } from '../supabaseClient'; // Ensure this points to your standard client
import { createClient } from '@supabase/supabase-js';

export default function SetupScreen({ initialMode, onBack, onComplete, onShowGuide }) {
  const isConnectingExisting = initialMode === 'connect';

  // State for standard connection
  const [formData, setFormData] = useState({ supabaseUrl: '', anonKey: '' });

  // State for Holy Grail OAuth Flow
  const [setupToken, setSetupToken] = useState(null);
  const [projects, setProjects] = useState([]);
  const [selectedProject, setSelectedProject] = useState('');

  // New Admin Auth credentials
  const [adminEmail, setAdminEmail] = useState('');
  const [adminPassword, setAdminPassword] = useState('');

  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState('');
  const [customAlert, setCustomAlert] = useState({ show: false, message: '', type: '' });

  // 1. Check for the OAuth Token on boot
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const token = params.get('setup_token');

    if (token) {
      setSetupToken(token);
      // Strip the token from the URL so it doesn't linger
      window.history.replaceState({}, document.title, "/");
      fetchProjects(token);
    }
  }, []);

  const showAlert = (message, type = 'error') => {
    setCustomAlert({ show: true, message, type });
    setTimeout(() => setCustomAlert({ show: false, message: '', type: '' }), 4000);
  };

  // 2. Fetch User's Projects using the Management API
  const fetchProjects = async (token) => {
    setLoading(true);
    setLoadingStep('Buscando tus proyectos...');
    try {
      // CHANGED: We now call our own backend proxy instead of api.supabase.com
      const res = await fetch('/api/get-projects', {
        headers: { Authorization: `Bearer ${token}` }
      });

      const data = await res.json();
      console.log("Supabase API Response:", data);

      if (!res.ok) throw new Error(data.message || 'Error fetching projects');

      setProjects(data);
      if (data.length > 0) setSelectedProject(data[0].id);

    } catch (err) {
      showAlert(err.message, 'error');
    } finally {
      setLoading(false);
      setLoadingStep('');
    }
  };

  // 3. The Grand Install Function
  const handleHolyGrailInstall = async (e) => {
    e.preventDefault();
    if (!selectedProject || !adminEmail || !adminPassword) {
      return showAlert("Por favor, llena todos los campos", "error");
    }

    setLoading(true);

    try {
      // --- STEP A: Fetch the Anon Key for the selected project ---
      setLoadingStep('Obteniendo credenciales seguras...');

      const keysRes = await fetch(`/api/get-keys?projectRef=${selectedProject}`, {
        headers: { Authorization: `Bearer ${setupToken}` }
      });

      const keysData = await keysRes.json();
      console.log("Respuesta de API Keys:", keysData); // <--- NUEVO SNITCH

      if (!keysRes.ok) {
        // Now it will throw the actual Supabase error message!
        throw new Error(keysData.message || keysData.error || "No se pudieron obtener las credenciales");
      }

      const anonKeyObj = keysData.find(k => k.name === 'anon');
      const serviceRoleObj = keysData.find(k => k.name === 'service_role');
      if (!anonKeyObj || !serviceRoleObj) throw new Error("Llaves de API no encontradas");

      const projectRef = projects.find(p => p.id === selectedProject)?.id;
      const projectUrl = `https://${projectRef}.supabase.co`;

      // --- STEP B: Inject the SQL Schema ---
      setLoadingStep('Instalando base de datos (Esto tomará unos segundos)...');

      const schemaQuery = `
        -- ==========================================
        -- EXTENSIONS
        -- ==========================================
        CREATE EXTENSION IF NOT EXISTS pgcrypto;

        -- ==========================================
        -- TABLES
        -- ==========================================

        CREATE TABLE IF NOT EXISTS public.active_tickets (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name text,
          items jsonb,
          cashier_id bigint,
          created_at timestamp with time zone DEFAULT now(),
          discount jsonb,
          savedSplitPayments jsonb,
          savedPaidProductIds jsonb,
          savedSplitMode text,
          savedNWays bigint,
          last_modified_by text,
          loyalty_phone text,
          loyalty_stars_pending integer DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS public.customers (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          phone character varying NOT NULL UNIQUE,
          visits bigint NOT NULL DEFAULT 0,
          created_at timestamp with time zone DEFAULT now(),
          completed_at timestamp with time zone
        );

        CREATE TABLE IF NOT EXISTS public.expenses (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          amount numeric NOT NULL,
          reason text,
          category text DEFAULT 'General',
          cashier_name text,
          local_id uuid UNIQUE,
          created_at timestamp with time zone DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS public.inventory (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name text NOT NULL UNIQUE,
          current_stock numeric DEFAULT 0,
          unit text,
          created_at timestamp with time zone DEFAULT now(),
          unit_cost numeric DEFAULT 0
        );

        CREATE TABLE IF NOT EXISTS public.inventory_logs (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          item_name text NOT NULL,
          qty_deducted numeric NOT NULL,
          deduction_type text NOT NULL,
          ticket_id text,
          unit_cost numeric DEFAULT 0,
          local_id uuid UNIQUE,
          created_at timestamp with time zone DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS public.activity_logs (
          id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
          created_at timestamp with time zone DEFAULT now(),
          cashier_name text,
          action_type text,
          description text,
          metadata jsonb
        );

        CREATE TABLE IF NOT EXISTS public.recipes (
          id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
          name text NOT NULL,
          linked_menu_item text,
          target_margin numeric DEFAULT 25.0,
          custom_price numeric,
          ingredients jsonb NOT NULL DEFAULT '[]'::jsonb,
          created_at timestamp with time zone DEFAULT now(),
          updated_at timestamp with time zone DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS public.sales (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          created_at timestamp with time zone NOT NULL DEFAULT now(),
          total_amount numeric,
          payment_method text,
          items_sold jsonb,
          cashier_name text,
          status text DEFAULT 'paid',
          order_name text,
          refund_amount numeric DEFAULT 0,
          tip_amount numeric DEFAULT 0,
          tip_refunded numeric DEFAULT 0,
          splits jsonb,
          items jsonb,
          discount jsonb,
          local_id uuid UNIQUE,
          ticket_id text,
          loyalty_phone text,
          loyalty_stars_awarded integer DEFAULT 0,
          loyalty_stars_redeemed integer DEFAULT 0,
          loyalty_program_type text
        );

        CREATE TABLE IF NOT EXISTS public.shop_settings (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          created_at timestamp with time zone NOT NULL DEFAULT now(),
          menu_data jsonb
        );

        -- Secure PIN Storage (hashed via pgcrypto)
        CREATE TABLE IF NOT EXISTS public.cashier_pins (
          cashier_id bigint PRIMARY KEY,
          pin_hash text NOT NULL,
          created_at timestamp with time zone DEFAULT now()
        );

        -- ==========================================
        -- REFUND SAFETY CONSTRAINT
        -- ==========================================
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints
            WHERE constraint_name = 'refund_limit_check' AND table_name = 'sales'
          ) THEN
            ALTER TABLE public.sales ADD CONSTRAINT refund_limit_check CHECK (refund_amount <= total_amount);
          END IF;
        END $$;

        -- ==========================================
        -- ANALYTICS: backfill ticket_id on legacy sale logs so COGS attribution
        -- works for installs that predate ticket_id (migration 009). Only fills
        -- unambiguous matches; colliding timestamps stay NULL to avoid
        -- misattribution.
        -- ==========================================
        WITH log_matches AS (
          SELECT
            il.id AS log_id,
            (SELECT s.ticket_id
               FROM public.sales s
              WHERE s.created_at = il.created_at
                AND s.ticket_id IS NOT NULL
                AND s.ticket_id <> ''
              LIMIT 1) AS resolved_ticket_id,
            (SELECT COUNT(*)
               FROM public.sales s
              WHERE s.created_at = il.created_at
                AND s.ticket_id IS NOT NULL
                AND s.ticket_id <> '') AS match_count
          FROM public.inventory_logs il
          WHERE il.deduction_type = 'sale'
            AND (il.ticket_id IS NULL OR il.ticket_id = '')
        )
        UPDATE public.inventory_logs il
        SET ticket_id = lm.resolved_ticket_id
        FROM log_matches lm
        WHERE il.id = lm.log_id
          AND lm.match_count = 1;

        -- ==========================================
        -- TIPS LIABILITY: schema upgrade for existing installs + new ledger tables
        -- ==========================================
        ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS tip_refunded numeric DEFAULT 0;

        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints
            WHERE constraint_name = 'tip_refund_limit_check' AND table_name = 'sales'
          ) THEN
            ALTER TABLE public.sales ADD CONSTRAINT tip_refund_limit_check CHECK (tip_refunded <= tip_amount);
          END IF;
        END $$;

        -- Records each disbursement of pooled tips to staff. The liability
        -- (SUM(tip_amount - tip_refunded) on sales) decreases by SUM(amount) on
        -- tip_payouts. The shop should periodically pay this out to zero.
        CREATE TABLE IF NOT EXISTS public.tip_payouts (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          amount numeric NOT NULL CHECK (amount > 0),
          method text DEFAULT 'cash',
          recipient text,
          note text,
          cashier_name text,
          local_id uuid UNIQUE,
          created_at timestamp with time zone DEFAULT now()
        );

        -- Immutable audit ledger for every tip movement. INSERT-only; never updated.
        -- event_type: 'accrual' (sale tip), 'refund' (tip refunded to customer),
        --             'payout' (paid to staff), 'adjustment' (manual correction).
        -- delta_cents is signed: + increases liability (accrual), - decreases (refund/payout).
        CREATE TABLE IF NOT EXISTS public.tip_events (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          event_type text NOT NULL CHECK (event_type IN ('accrual','refund','payout','adjustment')),
          delta_cents numeric NOT NULL,
          sale_local_id uuid,
          payout_local_id uuid,
          reason text,
          actor text,
          local_id uuid UNIQUE,
          created_at timestamp with time zone DEFAULT now()
        );
        CREATE INDEX IF NOT EXISTS idx_tip_events_created ON public.tip_events (created_at);
        CREATE INDEX IF NOT EXISTS idx_tip_events_type ON public.tip_events (event_type);

        ALTER TABLE public.tip_payouts ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.tip_events ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "Hardware can access tip_payouts" ON public.tip_payouts;
        DROP POLICY IF EXISTS "Hardware can access tip_events" ON public.tip_events;
        CREATE POLICY "Hardware can access tip_payouts" ON public.tip_payouts FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access tip_events" ON public.tip_events FOR ALL TO authenticated USING (true) WITH CHECK (true);

        -- ==========================================
        -- SEED INITIAL SETTINGS
        -- ==========================================
        INSERT INTO public.shop_settings (id, menu_data)
        VALUES (
          1,
          '{"categories": {"Café": []}, "cashiers": [{"id": 1, "name": "Admin", "pin": "1234", "isAdmin": true}], "posSettings": {"name": "tinypos", "language": "en", "brandColor": "#f28b05", "isDarkMode": false, "autoLockMinutes": 5, "enableCorte": true, "ticketVisibility": "open", "pinCode": "1234", "strictAdminAccess": false, "strictRegisterOverrides": false}, "receiptSettings": {"header": "", "subheader": "", "footer": "", "logo": null, "enableTaxBreakdown": false, "taxRate": 16}, "loyaltySettings": {"isActive": false, "visitsRequired": 10, "rewardDescription": "tu próxima bebida GRATIS"}, "modifierGroups": {}, "discountRules": []}'::jsonb
        )
        ON CONFLICT (id) DO NOTHING;

        -- Seed the default Admin PIN (hashed)
        INSERT INTO public.cashier_pins (cashier_id, pin_hash)
        VALUES (0, crypt('1234', gen_salt('bf'))),
              (1, crypt('1234', gen_salt('bf')))
        ON CONFLICT (cashier_id) DO NOTHING;

        -- ==========================================
        -- ROW LEVEL SECURITY (RLS) & POLICIES
        -- ==========================================

        -- 1. Enable RLS on every table
        ALTER TABLE public.active_tickets ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.inventory_logs ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.shop_settings ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.cashier_pins ENABLE ROW LEVEL SECURITY;

        -- 2. Create Policies for POS Hardware (Drop first to avoid 500 errors on re-run)
        DROP POLICY IF EXISTS "Hardware can access active_tickets" ON public.active_tickets;
        DROP POLICY IF EXISTS "Hardware can access customers" ON public.customers;
        DROP POLICY IF EXISTS "Hardware can access expenses" ON public.expenses;
        DROP POLICY IF EXISTS "Hardware can access inventory" ON public.inventory;
        DROP POLICY IF EXISTS "Hardware can access inventory_logs" ON public.inventory_logs;
        DROP POLICY IF EXISTS "Hardware can access activity_logs" ON public.activity_logs;
        DROP POLICY IF EXISTS "Hardware can access recipes" ON public.recipes;
        DROP POLICY IF EXISTS "Hardware can access sales" ON public.sales;
        DROP POLICY IF EXISTS "Hardware can access shop_settings" ON public.shop_settings;
        DROP POLICY IF EXISTS "Hardware can access cashier_pins" ON public.cashier_pins;

        CREATE POLICY "Hardware can access active_tickets" ON public.active_tickets FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access customers" ON public.customers FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access expenses" ON public.expenses FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access inventory" ON public.inventory FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access inventory_logs" ON public.inventory_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access activity_logs" ON public.activity_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access recipes" ON public.recipes FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access sales" ON public.sales FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access shop_settings" ON public.shop_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access cashier_pins" ON public.cashier_pins FOR ALL TO authenticated USING (true) WITH CHECK (true);

        -- ==========================================
        -- RPC FUNCTIONS
        -- ==========================================

        -- Secure PIN verification (compares against bcrypt hash)
        CREATE OR REPLACE FUNCTION verify_pin(p_cashier_id BIGINT, p_pin TEXT)
        RETURNS BOOLEAN AS $$
        DECLARE
            v_hash TEXT;
        BEGIN
            SELECT pin_hash INTO v_hash FROM public.cashier_pins WHERE cashier_id = p_cashier_id;
            IF v_hash IS NULL THEN RETURN FALSE; END IF;
            RETURN v_hash = crypt(p_pin, v_hash);
        END;
        $$ LANGUAGE plpgsql SECURITY DEFINER;

        -- Mirror of api/install.js: keep these in sync.
        -- search_path includes 'extensions' so pgcrypto's crypt()/gen_salt()
        -- resolve under SECURITY DEFINER. Keep in sync with api/install.js.
        CREATE OR REPLACE FUNCTION public.set_cashier_pin(p_cashier_id BIGINT, p_pin TEXT)
        RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER
        SET search_path = public, extensions AS $$
        BEGIN
          IF p_pin IS NULL OR length(p_pin) = 0 THEN
            RAISE EXCEPTION 'PIN cannot be empty';
          END IF;
          INSERT INTO public.cashier_pins (cashier_id, pin_hash)
          VALUES (p_cashier_id, crypt(p_pin, gen_salt('bf')))
          ON CONFLICT (cashier_id) DO UPDATE SET pin_hash = EXCLUDED.pin_hash;
        END;
        $$;

        CREATE OR REPLACE FUNCTION public.delete_cashier_pin(p_cashier_id BIGINT)
        RETURNS VOID LANGUAGE plpgsql SECURITY DEFINER
        SET search_path = public, extensions AS $$
        BEGIN
          DELETE FROM public.cashier_pins WHERE cashier_id = p_cashier_id;
        END;
        $$;

        -- Backfill any plaintext pins from menu_data.cashiers into cashier_pins.
        INSERT INTO public.cashier_pins (cashier_id, pin_hash)
        SELECT (c->>'id')::bigint, crypt(c->>'pin', gen_salt('bf'))
        FROM public.shop_settings ss,
             jsonb_array_elements(ss.menu_data->'cashiers') c
        WHERE ss.id = 1
          AND c->>'pin' IS NOT NULL
          AND c->>'id' IS NOT NULL
          AND NOT EXISTS (
            SELECT 1 FROM public.cashier_pins cp WHERE cp.cashier_id = (c->>'id')::bigint
          )
        ON CONFLICT (cashier_id) DO NOTHING;

        -- ==========================================
        -- MENU SPLIT: dedicated tables replacing shop_settings.menu_data blobs.
        -- See api/install.js for full rationale. Backfill is idempotent.
        -- ==========================================
        CREATE TABLE IF NOT EXISTS public.menu_categories (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name text NOT NULL UNIQUE,
          sort_order int NOT NULL DEFAULT 0,
          is_hidden bool NOT NULL DEFAULT false,
          created_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE TABLE IF NOT EXISTS public.menu_items (
          id text PRIMARY KEY,
          category_id bigint NOT NULL REFERENCES public.menu_categories(id) ON DELETE RESTRICT,
          name text NOT NULL,
          base_price_cents int NOT NULL DEFAULT 0,
          price_type text NOT NULL DEFAULT 'fixed',
          emoji text NOT NULL DEFAULT '',
          image_url text,
          sort_order int NOT NULL DEFAULT 0,
          is_hidden bool NOT NULL DEFAULT false,
          data jsonb NOT NULL DEFAULT '{}'::jsonb,
          created_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE INDEX IF NOT EXISTS idx_menu_items_category ON public.menu_items (category_id);
        -- Self-heal: image_url added in migration 013, after some installs already had menu_items.
        ALTER TABLE public.menu_items ADD COLUMN IF NOT EXISTS image_url text;
        CREATE TABLE IF NOT EXISTS public.menu_modifier_groups (
          id text PRIMARY KEY,
          name text NOT NULL,
          allow_multiple bool NOT NULL DEFAULT false,
          sort_order int NOT NULL DEFAULT 0,
          data jsonb NOT NULL DEFAULT '{}'::jsonb,
          created_at timestamptz NOT NULL DEFAULT now()
        );
        ALTER TABLE public.menu_modifier_groups ADD COLUMN IF NOT EXISTS allow_multiple bool NOT NULL DEFAULT false;
        CREATE TABLE IF NOT EXISTS public.menu_modifier_options (
          id text PRIMARY KEY,
          group_id text NOT NULL REFERENCES public.menu_modifier_groups(id) ON UPDATE CASCADE ON DELETE CASCADE,
          name text NOT NULL,
          price_delta_cents int NOT NULL DEFAULT 0,
          sort_order int NOT NULL DEFAULT 0,
          data jsonb NOT NULL DEFAULT '{}'::jsonb
        );
        CREATE INDEX IF NOT EXISTS idx_menu_modifier_options_group ON public.menu_modifier_options (group_id);
        CREATE TABLE IF NOT EXISTS public.menu_item_modifier_groups (
          item_id text NOT NULL REFERENCES public.menu_items(id) ON UPDATE CASCADE ON DELETE CASCADE,
          group_id text NOT NULL REFERENCES public.menu_modifier_groups(id) ON UPDATE CASCADE ON DELETE CASCADE,
          sort_order int NOT NULL DEFAULT 0,
          PRIMARY KEY (item_id, group_id)
        );
        -- FK self-heal: see api/install.js for rationale.
        ALTER TABLE public.menu_modifier_options
          DROP CONSTRAINT IF EXISTS menu_modifier_options_group_id_fkey;
        ALTER TABLE public.menu_modifier_options
          ADD CONSTRAINT menu_modifier_options_group_id_fkey
            FOREIGN KEY (group_id) REFERENCES public.menu_modifier_groups(id)
            ON UPDATE CASCADE ON DELETE CASCADE;
        ALTER TABLE public.menu_item_modifier_groups
          DROP CONSTRAINT IF EXISTS menu_item_modifier_groups_group_id_fkey;
        ALTER TABLE public.menu_item_modifier_groups
          ADD CONSTRAINT menu_item_modifier_groups_group_id_fkey
            FOREIGN KEY (group_id) REFERENCES public.menu_modifier_groups(id)
            ON UPDATE CASCADE ON DELETE CASCADE;
        ALTER TABLE public.menu_item_modifier_groups
          DROP CONSTRAINT IF EXISTS menu_item_modifier_groups_item_id_fkey;
        ALTER TABLE public.menu_item_modifier_groups
          ADD CONSTRAINT menu_item_modifier_groups_item_id_fkey
            FOREIGN KEY (item_id) REFERENCES public.menu_items(id)
            ON UPDATE CASCADE ON DELETE CASCADE;
        CREATE TABLE IF NOT EXISTS public.menu_discount_rules (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name text NOT NULL DEFAULT '',
          rule_type text NOT NULL DEFAULT '',
          payload jsonb NOT NULL DEFAULT '{}'::jsonb,
          is_active bool NOT NULL DEFAULT true,
          sort_order int NOT NULL DEFAULT 0,
          created_at timestamptz NOT NULL DEFAULT now()
        );

        ALTER TABLE public.menu_categories           ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.menu_items                ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.menu_modifier_groups      ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.menu_modifier_options     ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.menu_item_modifier_groups ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.menu_discount_rules       ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS "Hardware can access menu_categories"           ON public.menu_categories;
        DROP POLICY IF EXISTS "Hardware can access menu_items"                ON public.menu_items;
        DROP POLICY IF EXISTS "Hardware can access menu_modifier_groups"      ON public.menu_modifier_groups;
        DROP POLICY IF EXISTS "Hardware can access menu_modifier_options"     ON public.menu_modifier_options;
        DROP POLICY IF EXISTS "Hardware can access menu_item_modifier_groups" ON public.menu_item_modifier_groups;
        DROP POLICY IF EXISTS "Hardware can access menu_discount_rules"       ON public.menu_discount_rules;
        CREATE POLICY "Hardware can access menu_categories"           ON public.menu_categories           FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access menu_items"                ON public.menu_items                FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access menu_modifier_groups"      ON public.menu_modifier_groups      FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access menu_modifier_options"     ON public.menu_modifier_options     FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access menu_item_modifier_groups" ON public.menu_item_modifier_groups FOR ALL TO authenticated USING (true) WITH CHECK (true);
        CREATE POLICY "Hardware can access menu_discount_rules"       ON public.menu_discount_rules       FOR ALL TO authenticated USING (true) WITH CHECK (true);

        -- Menu versions (migration 014): snapshots + restore.
        CREATE TABLE IF NOT EXISTS public.menu_versions (
          id bigserial PRIMARY KEY,
          created_at timestamptz NOT NULL DEFAULT now(),
          snapshot jsonb NOT NULL,
          reason text NOT NULL DEFAULT 'auto',
          trigger_op text
        );
        CREATE INDEX IF NOT EXISTS idx_menu_versions_created ON public.menu_versions (created_at DESC);
        ALTER TABLE public.menu_versions ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "menu_versions auth all" ON public.menu_versions;
        CREATE POLICY "menu_versions auth all" ON public.menu_versions FOR ALL TO authenticated USING (true) WITH CHECK (true);

        CREATE OR REPLACE FUNCTION public.build_menu_snapshot()
        RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
          SELECT jsonb_build_object(
            'categories', COALESCE((
              SELECT jsonb_object_agg(c.name, COALESCE((
                SELECT jsonb_agg(jsonb_build_object('id', i.id, 'name', i.name, 'basePrice', i.base_price_cents,
                  'priceType', i.price_type, 'emoji', i.emoji, 'imageUrl', i.image_url,
                  'allowedModifiers', COALESCE((SELECT jsonb_agg(l.group_id ORDER BY l.sort_order) FROM public.menu_item_modifier_groups l WHERE l.item_id = i.id), '[]'::jsonb)
                ) || COALESCE(i.data, '{}'::jsonb) ORDER BY i.sort_order)
                FROM public.menu_items i WHERE i.category_id = c.id
              ), '[]'::jsonb)) FROM public.menu_categories c
            ), '{}'::jsonb),
            'categoryOrder', COALESCE((SELECT jsonb_agg(c.name ORDER BY c.sort_order) FROM public.menu_categories c), '[]'::jsonb),
            'hiddenCategories', COALESCE((SELECT jsonb_agg(c.name) FROM public.menu_categories c WHERE c.is_hidden), '[]'::jsonb),
            'modifierGroups', COALESCE((
              SELECT jsonb_object_agg(g.id, COALESCE((
                SELECT jsonb_agg(jsonb_build_object('id', o.id, 'name', o.name, 'price', o.price_delta_cents) || COALESCE(o.data, '{}'::jsonb) ORDER BY o.sort_order)
                FROM public.menu_modifier_options o WHERE o.group_id = g.id
              ), '[]'::jsonb)) FROM public.menu_modifier_groups g
            ), '{}'::jsonb),
            'modifierGroupSettings', COALESCE((
              SELECT jsonb_object_agg(g.id, jsonb_build_object('allowMultiple', g.allow_multiple)) FROM public.menu_modifier_groups g
            ), '{}'::jsonb),
            'discountRules', COALESCE((SELECT jsonb_agg(r.payload ORDER BY r.sort_order) FROM public.menu_discount_rules r), '[]'::jsonb)
          );
        $$;
        REVOKE ALL ON FUNCTION public.build_menu_snapshot() FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION public.build_menu_snapshot() TO authenticated;

        CREATE OR REPLACE FUNCTION public.prune_menu_versions()
        RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
          WITH
            keep_manual AS (SELECT id FROM public.menu_versions WHERE reason <> 'auto'),
            keep_recent AS (SELECT id FROM public.menu_versions WHERE created_at > now() - interval '7 days'),
            keep_daily AS (SELECT DISTINCT ON (date_trunc('day', created_at)) id FROM public.menu_versions WHERE created_at > now() - interval '30 days' ORDER BY date_trunc('day', created_at), created_at DESC),
            keep_weekly AS (SELECT DISTINCT ON (date_trunc('week', created_at)) id FROM public.menu_versions WHERE created_at > now() - interval '1 year' ORDER BY date_trunc('week', created_at), created_at DESC),
            keep AS (SELECT id FROM keep_manual UNION SELECT id FROM keep_recent UNION SELECT id FROM keep_daily UNION SELECT id FROM keep_weekly)
          DELETE FROM public.menu_versions WHERE id NOT IN (SELECT id FROM keep);
        $$;
        REVOKE ALL ON FUNCTION public.prune_menu_versions() FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION public.prune_menu_versions() TO authenticated;

        CREATE OR REPLACE FUNCTION public.snapshot_menu(p_reason text DEFAULT 'auto', p_trigger_op text DEFAULT NULL)
        RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
        DECLARE v_snap jsonb; v_last jsonb; v_id bigint;
        BEGIN
          v_snap := public.build_menu_snapshot();
          SELECT snapshot INTO v_last FROM public.menu_versions ORDER BY id DESC LIMIT 1;
          IF v_last IS NOT NULL AND v_last = v_snap AND p_reason = 'auto' THEN RETURN NULL; END IF;
          INSERT INTO public.menu_versions (snapshot, reason, trigger_op)
            VALUES (v_snap, COALESCE(p_reason,'auto'), p_trigger_op) RETURNING id INTO v_id;
          PERFORM public.prune_menu_versions();
          RETURN v_id;
        END $$;
        REVOKE ALL ON FUNCTION public.snapshot_menu(text, text) FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION public.snapshot_menu(text, text) TO authenticated;

        CREATE OR REPLACE FUNCTION public.restore_menu_version(p_version_id bigint)
        RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
        DECLARE v_snap jsonb; v_pre bigint; v_cats int := 0; v_items int := 0;
        BEGIN
          SELECT snapshot INTO v_snap FROM public.menu_versions WHERE id = p_version_id;
          IF v_snap IS NULL THEN RAISE EXCEPTION 'menu_versions row % not found', p_version_id; END IF;
          v_pre := public.snapshot_menu('restore-target', 'before-restore-of-' || p_version_id);
          DELETE FROM public.menu_item_modifier_groups;
          DELETE FROM public.menu_modifier_options;
          DELETE FROM public.menu_modifier_groups;
          DELETE FROM public.menu_items;
          DELETE FROM public.menu_categories;
          DELETE FROM public.menu_discount_rules;
          WITH ordered AS (SELECT key, ord FROM jsonb_array_elements_text(COALESCE(v_snap->'categoryOrder','[]'::jsonb)) WITH ORDINALITY AS o(key, ord))
          INSERT INTO public.menu_categories (name, sort_order, is_hidden)
          SELECT k, COALESCE((SELECT ord FROM ordered WHERE key=k)::int, 1000), (COALESCE(v_snap->'hiddenCategories','[]'::jsonb) ? k)
          FROM jsonb_object_keys(COALESCE(v_snap->'categories','{}'::jsonb)) AS k;
          GET DIAGNOSTICS v_cats = ROW_COUNT;
          INSERT INTO public.menu_items (id, category_id, name, base_price_cents, price_type, emoji, image_url, sort_order, is_hidden, data)
          SELECT item->>'id', mc.id, COALESCE(item->>'name',''), COALESCE((item->>'basePrice')::int, 0),
                 COALESCE(item->>'priceType','fixed'), COALESCE(item->>'emoji',''), NULLIF(item->>'imageUrl',''),
                 (it.ord - 1)::int, false,
                 (item - 'id' - 'name' - 'basePrice' - 'priceType' - 'emoji' - 'imageUrl' - 'allowedModifiers' - 'category')
          FROM jsonb_each(COALESCE(v_snap->'categories','{}'::jsonb)) AS cat(key, value)
          JOIN public.menu_categories mc ON mc.name = cat.key
          CROSS JOIN LATERAL jsonb_array_elements(cat.value) WITH ORDINALITY AS it(item, ord)
          WHERE item->>'id' IS NOT NULL;
          GET DIAGNOSTICS v_items = ROW_COUNT;
          INSERT INTO public.menu_modifier_groups (id, name, allow_multiple, sort_order)
          SELECT key, key, COALESCE((v_snap->'modifierGroupSettings'->key->>'allowMultiple')::bool, false),
                 ((row_number() OVER (ORDER BY key)) - 1)::int
          FROM jsonb_object_keys(COALESCE(v_snap->'modifierGroups','{}'::jsonb)) AS key;
          INSERT INTO public.menu_modifier_options (id, group_id, name, price_delta_cents, sort_order, data)
          SELECT opt->>'id', grp.key, COALESCE(opt->>'name',''),
                 COALESCE((opt->>'price')::int, (opt->>'price_delta_cents')::int, 0),
                 (o.ord - 1)::int, (opt - 'id' - 'name' - 'price' - 'price_delta_cents')
          FROM jsonb_each(COALESCE(v_snap->'modifierGroups','{}'::jsonb)) AS grp(key, value)
          CROSS JOIN LATERAL jsonb_array_elements(grp.value) WITH ORDINALITY AS o(opt, ord)
          WHERE opt->>'id' IS NOT NULL;
          INSERT INTO public.menu_item_modifier_groups (item_id, group_id, sort_order)
          SELECT item->>'id', m.mod_key, (m.ord - 1)::int
          FROM jsonb_each(COALESCE(v_snap->'categories','{}'::jsonb)) AS cat(key, value)
          CROSS JOIN LATERAL jsonb_array_elements(cat.value) AS item
          CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(item->'allowedModifiers','[]'::jsonb))
                             WITH ORDINALITY AS m(mod_key, ord)
          WHERE EXISTS (SELECT 1 FROM public.menu_items mi WHERE mi.id = item->>'id')
            AND EXISTS (SELECT 1 FROM public.menu_modifier_groups mg WHERE mg.id = m.mod_key);
          INSERT INTO public.menu_discount_rules (name, rule_type, payload, is_active, sort_order)
          SELECT COALESCE(rule->>'name',''), COALESCE(rule->>'type',''), rule,
                 COALESCE((rule->>'isActive')::bool, true), (r.ord - 1)::int
          FROM jsonb_array_elements(COALESCE(v_snap->'discountRules','[]'::jsonb))
               WITH ORDINALITY AS r(rule, ord);
          RETURN jsonb_build_object('restored_from', p_version_id, 'previous_snapshot_id', v_pre,
                                    'inserted_categories', v_cats, 'inserted_items', v_items);
        END $$;
        REVOKE ALL ON FUNCTION public.restore_menu_version(bigint) FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION public.restore_menu_version(bigint) TO authenticated;

        DO $menu_split$
        DECLARE
          v_menu jsonb;
          v_order jsonb;
          v_hidden jsonb;
          v_items_in int := 0;
        BEGIN
          IF EXISTS (SELECT 1 FROM public.menu_categories) THEN RETURN; END IF;
          SELECT menu_data INTO v_menu FROM public.shop_settings WHERE id = 1;
          IF v_menu IS NULL THEN RETURN; END IF;
          -- Archive the raw legacy JSONB before any migration attempt — recovery surface.
          BEGIN
            INSERT INTO public.menu_versions (snapshot, reason, trigger_op)
              VALUES (v_menu, 'pre-jsonb-strip', 'install_split_menu_data');
          EXCEPTION WHEN undefined_table THEN NULL;
          END;
          v_order  := COALESCE(v_menu->'categoryOrder',    '[]'::jsonb);
          v_hidden := COALESCE(v_menu->'hiddenCategories', '[]'::jsonb);

          WITH ordered AS (
            SELECT key, ord FROM jsonb_array_elements_text(v_order) WITH ORDINALITY AS o(key, ord)
          )
          INSERT INTO public.menu_categories (name, sort_order, is_hidden)
          SELECT k,
                 COALESCE((SELECT ord FROM ordered WHERE key = k)::int, 1000),
                 (v_hidden ? k)
          FROM jsonb_object_keys(COALESCE(v_menu->'categories','{}'::jsonb)) AS k
          ON CONFLICT (name) DO NOTHING;

          INSERT INTO public.menu_items (id, category_id, name, base_price_cents, price_type, emoji, sort_order, data)
          SELECT item->>'id', mc.id,
                 COALESCE(item->>'name',''),
                 COALESCE((item->>'basePrice')::int, 0),
                 COALESCE(item->>'priceType','fixed'),
                 COALESCE(item->>'emoji',''),
                 (it.ord - 1)::int,
                 (item - 'id' - 'name' - 'basePrice' - 'priceType' - 'emoji' - 'allowedModifiers' - 'category')
          FROM jsonb_each(COALESCE(v_menu->'categories','{}'::jsonb)) AS cat(key, value)
          JOIN public.menu_categories mc ON mc.name = cat.key
          CROSS JOIN LATERAL jsonb_array_elements(cat.value) WITH ORDINALITY AS it(item, ord)
          WHERE item->>'id' IS NOT NULL
          ON CONFLICT (id) DO NOTHING;
          GET DIAGNOSTICS v_items_in = ROW_COUNT;

          INSERT INTO public.menu_modifier_groups (id, name, allow_multiple, sort_order)
          SELECT key, key,
                 COALESCE((v_menu->'modifierGroupSettings'->key->>'allowMultiple')::bool, false),
                 ((row_number() OVER (ORDER BY key)) - 1)::int
          FROM jsonb_object_keys(COALESCE(v_menu->'modifierGroups','{}'::jsonb)) AS key
          ON CONFLICT (id) DO NOTHING;

          INSERT INTO public.menu_modifier_options (id, group_id, name, price_delta_cents, sort_order, data)
          SELECT opt->>'id', grp.key,
                 COALESCE(opt->>'name',''),
                 COALESCE((opt->>'priceDelta')::int, (opt->>'price_delta_cents')::int, 0),
                 (o.ord - 1)::int,
                 (opt - 'id' - 'name' - 'priceDelta' - 'price_delta_cents')
          FROM jsonb_each(COALESCE(v_menu->'modifierGroups','{}'::jsonb)) AS grp(key, value)
          CROSS JOIN LATERAL jsonb_array_elements(grp.value) WITH ORDINALITY AS o(opt, ord)
          WHERE opt->>'id' IS NOT NULL
          ON CONFLICT (id) DO NOTHING;

          INSERT INTO public.menu_item_modifier_groups (item_id, group_id, sort_order)
          SELECT item->>'id', m.mod_key, (m.ord - 1)::int
          FROM jsonb_each(COALESCE(v_menu->'categories','{}'::jsonb)) AS cat(key, value)
          CROSS JOIN LATERAL jsonb_array_elements(cat.value) AS item
          CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(item->'allowedModifiers','[]'::jsonb))
                             WITH ORDINALITY AS m(mod_key, ord)
          WHERE EXISTS (SELECT 1 FROM public.menu_items mi WHERE mi.id = item->>'id')
            AND EXISTS (SELECT 1 FROM public.menu_modifier_groups mg WHERE mg.id = m.mod_key)
          ON CONFLICT DO NOTHING;

          INSERT INTO public.menu_discount_rules (name, rule_type, payload, is_active, sort_order)
          SELECT COALESCE(rule->>'name',''), COALESCE(rule->>'type',''), rule,
                 COALESCE((rule->>'isActive')::bool, true), (r.ord - 1)::int
          FROM jsonb_array_elements(COALESCE(v_menu->'discountRules','[]'::jsonb))
               WITH ORDINALITY AS r(rule, ord);

          -- Strip ONLY if migration actually inserted items; otherwise the
          -- JSONB shape didn't match and stripping would erase the only copy.
          IF v_items_in > 0 THEN
            UPDATE public.shop_settings
            SET menu_data = menu_data - 'categories' - 'categoryOrder' - 'hiddenCategories' - 'modifierGroups' - 'modifierGroupSettings' - 'discountRules'
            WHERE id = 1;
          END IF;
        END
        $menu_split$;

        -- Loyalty trigger: fires AFTER INSERT on sales, exactly once per sale.
        -- Idempotent by construction — sales upserts use onConflict: local_id, so retries
        -- don't fire INSERT triggers on conflict. Behavior:
        --   1. ACCRUE: customers.visits += loyalty_stars_awarded (clamped at 0).
        --   2. REDEEM: customers.visits -= loyalty_stars_redeemed (clamped at 0).
        --      Net change per sale = awarded - redeemed.
        --   3. SINGLE-MODE LOCKOUT: if customer.completed_at IS NOT NULL, suppress accrual
        --      (frozen customers can't earn more stars; redemption still works).
        --   4. FREEZE: if loyalty_program_type = 'single' AND redemption occurred,
        --      set customers.completed_at = now() to lock the customer out of future accrual.
        --      Admin "Reset stars" clears completed_at to start a fresh campaign.
        CREATE OR REPLACE FUNCTION public.award_loyalty_visits()
        RETURNS TRIGGER AS $$
        DECLARE
          v_awarded integer := COALESCE(NEW.loyalty_stars_awarded, 0);
          v_redeemed integer := COALESCE(NEW.loyalty_stars_redeemed, 0);
          v_completed timestamp with time zone;
          v_net integer;
        BEGIN
          IF NEW.loyalty_phone IS NULL OR (v_awarded = 0 AND v_redeemed = 0) THEN
            RETURN NEW;
          END IF;

          SELECT completed_at INTO v_completed FROM public.customers WHERE phone = NEW.loyalty_phone;

          IF v_completed IS NOT NULL AND v_awarded > 0 THEN
            v_awarded := 0;
          END IF;

          v_net := v_awarded - v_redeemed;

          INSERT INTO public.customers (phone, visits)
          VALUES (NEW.loyalty_phone, GREATEST(0, v_net))
          ON CONFLICT (phone) DO UPDATE
            SET visits = GREATEST(0, public.customers.visits + v_net);

          IF NEW.loyalty_program_type = 'single' AND v_redeemed > 0 THEN
            UPDATE public.customers SET completed_at = now() WHERE phone = NEW.loyalty_phone;
          END IF;

          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql SECURITY DEFINER;

        DROP TRIGGER IF EXISTS trg_award_loyalty ON public.sales;
        CREATE TRIGGER trg_award_loyalty
          AFTER INSERT ON public.sales
          FOR EACH ROW
          EXECUTE FUNCTION public.award_loyalty_visits();

        -- Self-heal: ensure menu_items.image_url (migration 013) exists before
        -- the resolver below references it.
        ALTER TABLE public.menu_items ADD COLUMN IF NOT EXISTS image_url text;

        -- Multi-menu + scheduling (migration 015). See db/migrations/015_menus_and_schedules.sql.
        CREATE TABLE IF NOT EXISTS public.menus (
          id bigserial PRIMARY KEY,
          name text NOT NULL,
          kind text NOT NULL DEFAULT 'live' CHECK (kind IN ('live','pdf','image','designed')),
          priority int NOT NULL DEFAULT 0,
          is_active bool NOT NULL DEFAULT true,
          data jsonb NOT NULL DEFAULT '{}'::jsonb,
          created_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE UNIQUE INDEX IF NOT EXISTS uniq_menus_live ON public.menus ((1)) WHERE kind = 'live';
        ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "menus auth all" ON public.menus;
        CREATE POLICY "menus auth all" ON public.menus FOR ALL TO authenticated USING (true) WITH CHECK (true);
        INSERT INTO public.menus (name, kind, priority, is_active)
        SELECT 'Menú principal', 'live', 0, true
        WHERE NOT EXISTS (SELECT 1 FROM public.menus WHERE kind = 'live');

        CREATE TABLE IF NOT EXISTS public.menu_schedules (
          id bigserial PRIMARY KEY,
          menu_id bigint NOT NULL REFERENCES public.menus(id) ON DELETE CASCADE,
          days_of_week int NOT NULL DEFAULT 0,
          start_time time, end_time time,
          start_date date, end_date date,
          created_at timestamptz NOT NULL DEFAULT now()
        );
        CREATE INDEX IF NOT EXISTS idx_menu_schedules_menu ON public.menu_schedules (menu_id);
        ALTER TABLE public.menu_schedules ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "menu_schedules auth all" ON public.menu_schedules;
        CREATE POLICY "menu_schedules auth all" ON public.menu_schedules FOR ALL TO authenticated USING (true) WITH CHECK (true);

        CREATE OR REPLACE FUNCTION public.shop_timezone()
        RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
          SELECT COALESCE((SELECT menu_data->'posSettings'->>'timezone' FROM public.shop_settings WHERE id = 1), 'UTC');
        $$;
        REVOKE ALL ON FUNCTION public.shop_timezone() FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION public.shop_timezone() TO anon, authenticated;

        CREATE OR REPLACE FUNCTION public.schedule_matches(
          p_days int, p_start_time time, p_end_time time,
          p_start_date date, p_end_date date, p_local timestamp
        ) RETURNS bool LANGUAGE sql IMMUTABLE AS $$
          SELECT
            (p_start_date IS NULL OR p_local::date >= p_start_date)
            AND (p_end_date IS NULL OR p_local::date <= p_end_date)
            AND (
              COALESCE(p_days, 0) = 0
              OR (COALESCE(p_days, 0) & (1 << (EXTRACT(isodow FROM p_local)::int - 1))) <> 0
            )
            AND (
              (p_start_time IS NULL AND p_end_time IS NULL)
              OR (p_start_time IS NOT NULL AND p_end_time IS NOT NULL AND p_start_time <= p_end_time
                  AND p_local::time >= p_start_time AND p_local::time < p_end_time)
              OR (p_start_time IS NOT NULL AND p_end_time IS NOT NULL AND p_start_time > p_end_time
                  AND (p_local::time >= p_start_time OR p_local::time < p_end_time))
              OR (p_start_time IS NOT NULL AND p_end_time IS NULL AND p_local::time >= p_start_time)
              OR (p_start_time IS NULL AND p_end_time IS NOT NULL AND p_local::time < p_end_time)
            );
        $$;

        -- Per-item availability (migration 018).
        CREATE OR REPLACE FUNCTION public.menu_item_available(p_item_id text)
        RETURNS bool LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
        DECLARE
          v_data jsonb; v_mode text; v_short_id bigint;
        BEGIN
          SELECT data INTO v_data FROM public.menu_items WHERE id = p_item_id;
          IF v_data IS NULL THEN RETURN true; END IF;
          v_mode := COALESCE(v_data->>'inventoryMode', 'none');
          IF v_mode = 'warehouse' THEN
            BEGIN v_short_id := NULLIF(v_data->>'linkedWarehouseId','')::bigint;
            EXCEPTION WHEN OTHERS THEN RETURN true; END;
            IF v_short_id IS NULL THEN RETURN true; END IF;
            RETURN COALESCE((SELECT current_stock > 0 FROM public.inventory WHERE id = v_short_id), true);
          END IF;
          IF v_mode = 'recipe' THEN
            DECLARE v_rid uuid;
            BEGIN
              BEGIN v_rid := NULLIF(v_data->>'linkedRecipeId','')::uuid;
              EXCEPTION WHEN OTHERS THEN RETURN true; END;
              IF v_rid IS NULL THEN RETURN true; END IF;
              RETURN NOT EXISTS (
                SELECT 1 FROM public.recipes r,
                     LATERAL jsonb_array_elements(COALESCE(r.ingredients,'[]'::jsonb)) AS ing(val)
                WHERE r.id = v_rid
                  AND COALESCE(
                        (SELECT current_stock FROM public.inventory
                          WHERE id = (CASE WHEN (ing.val->>'id') ~ '^[0-9]+$' THEN (ing.val->>'id')::bigint ELSE NULL END)),
                        0
                      ) < (CASE WHEN (ing.val->>'qty') ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (ing.val->>'qty')::numeric ELSE 0 END)
              );
            END;
          END IF;
          RETURN true;
        END $$;
        REVOKE ALL ON FUNCTION public.menu_item_available(text) FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION public.menu_item_available(text) TO anon, authenticated;

        CREATE OR REPLACE FUNCTION public.get_active_menu(p_now timestamptz DEFAULT now())
        RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public STABLE AS $$
        DECLARE
          v_tz text; v_local timestamp;
          v_menu_id bigint; v_kind text; v_name text; v_data jsonb; v_shop jsonb;
        BEGIN
          v_tz := public.shop_timezone();
          v_local := (p_now AT TIME ZONE v_tz)::timestamp;
          SELECT m.id, m.kind, m.name, m.data INTO v_menu_id, v_kind, v_name, v_data
          FROM public.menus m
          WHERE m.is_active = true
            AND (
              NOT EXISTS (SELECT 1 FROM public.menu_schedules s WHERE s.menu_id = m.id)
              OR EXISTS (
                SELECT 1 FROM public.menu_schedules s
                WHERE s.menu_id = m.id
                  AND public.schedule_matches(s.days_of_week, s.start_time, s.end_time,
                                              s.start_date, s.end_date, v_local)
              )
            )
          ORDER BY m.priority DESC, m.created_at DESC LIMIT 1;
          IF v_menu_id IS NULL THEN
            SELECT m.id, m.kind, m.name, m.data INTO v_menu_id, v_kind, v_name, v_data
            FROM public.menus m WHERE m.kind = 'live' LIMIT 1;
          END IF;
          v_shop := jsonb_build_object(
            'name', COALESCE((SELECT menu_data->'posSettings'->>'name' FROM public.shop_settings WHERE id = 1), 'Menu'),
            'brand_color', COALESCE((SELECT menu_data->'posSettings'->>'brandColor' FROM public.shop_settings WHERE id = 1), '#f28b05'),
            'language', COALESCE((SELECT menu_data->'posSettings'->>'language' FROM public.shop_settings WHERE id = 1), 'es'),
            'timezone', v_tz
          );
          IF v_kind = 'live' OR v_kind = 'designed' THEN
            RETURN jsonb_build_object(
              'menu', jsonb_build_object('id', v_menu_id, 'kind', v_kind, 'name', v_name, 'data', v_data),
              'shop', v_shop,
              'categories', COALESCE((
                SELECT jsonb_agg(jsonb_build_object(
                  'id', c.id, 'name', c.name, 'sort_order', c.sort_order,
                  'items', COALESCE((
                    SELECT jsonb_agg(jsonb_build_object(
                      'id', i.id, 'name', i.name, 'price_cents', i.base_price_cents,
                      'price_type', i.price_type, 'emoji', i.emoji, 'image_url', i.image_url,
                      'sort_order', i.sort_order,
                      'available', public.menu_item_available(i.id),
                      'modifier_group_ids', COALESCE((
                        SELECT jsonb_agg(l.group_id ORDER BY l.sort_order)
                        FROM public.menu_item_modifier_groups l WHERE l.item_id = i.id
                      ), '[]'::jsonb)
                    ) ORDER BY i.sort_order)
                    FROM public.menu_items i WHERE i.category_id = c.id AND i.is_hidden = false
                  ), '[]'::jsonb)
                ) ORDER BY c.sort_order)
                FROM public.menu_categories c WHERE c.is_hidden = false
              ), '[]'::jsonb),
              'modifier_groups', COALESCE((
                SELECT jsonb_agg(jsonb_build_object(
                  'id', g.id, 'name', g.name, 'allow_multiple', g.allow_multiple,
                  'options', COALESCE((
                    SELECT jsonb_agg(jsonb_build_object(
                      'id', o.id, 'name', o.name, 'price_delta_cents', o.price_delta_cents
                    ) ORDER BY o.sort_order)
                    FROM public.menu_modifier_options o WHERE o.group_id = g.id
                  ), '[]'::jsonb)
                ) ORDER BY g.sort_order)
                FROM public.menu_modifier_groups g
              ), '[]'::jsonb)
            );
          ELSE
            RETURN jsonb_build_object(
              'menu', jsonb_build_object('id', v_menu_id, 'kind', v_kind, 'name', v_name, 'data', v_data),
              'shop', v_shop,
              'categories', '[]'::jsonb, 'modifier_groups', '[]'::jsonb
            );
          END IF;
        END $$;
        REVOKE ALL ON FUNCTION public.get_active_menu(timestamptz) FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION public.get_active_menu(timestamptz) TO anon, authenticated;

        CREATE OR REPLACE FUNCTION public.get_public_menu()
        RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
          SELECT public.get_active_menu(now());
        $$;
        REVOKE ALL ON FUNCTION public.get_public_menu() FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION public.get_public_menu() TO anon, authenticated;

        -- Per-menu deep link (migration 017): /menu?m=<id> renders that
        -- specific menu regardless of schedule. Inactive/unknown falls back
        -- to the catalog so stale QRs still render something.
        CREATE OR REPLACE FUNCTION public.get_menu_by_id(p_id bigint)
        RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public STABLE AS $$
        DECLARE
          v_tz text;
          v_menu_id bigint; v_kind text; v_name text; v_data jsonb; v_shop jsonb;
        BEGIN
          v_tz := public.shop_timezone();
          SELECT m.id, m.kind, m.name, m.data INTO v_menu_id, v_kind, v_name, v_data
          FROM public.menus m WHERE m.id = p_id AND m.is_active = true LIMIT 1;
          IF v_menu_id IS NULL THEN
            SELECT m.id, m.kind, m.name, m.data INTO v_menu_id, v_kind, v_name, v_data
            FROM public.menus m WHERE m.kind = 'live' LIMIT 1;
          END IF;
          v_shop := jsonb_build_object(
            'name', COALESCE((SELECT menu_data->'posSettings'->>'name' FROM public.shop_settings WHERE id = 1), 'Menu'),
            'brand_color', COALESCE((SELECT menu_data->'posSettings'->>'brandColor' FROM public.shop_settings WHERE id = 1), '#f28b05'),
            'language', COALESCE((SELECT menu_data->'posSettings'->>'language' FROM public.shop_settings WHERE id = 1), 'es'),
            'timezone', v_tz
          );
          IF v_kind = 'live' OR v_kind = 'designed' THEN
            RETURN jsonb_build_object(
              'menu', jsonb_build_object('id', v_menu_id, 'kind', v_kind, 'name', v_name, 'data', v_data),
              'shop', v_shop,
              'categories', COALESCE((
                SELECT jsonb_agg(jsonb_build_object(
                  'id', c.id, 'name', c.name, 'sort_order', c.sort_order,
                  'items', COALESCE((
                    SELECT jsonb_agg(jsonb_build_object(
                      'id', i.id, 'name', i.name, 'price_cents', i.base_price_cents,
                      'price_type', i.price_type, 'emoji', i.emoji, 'image_url', i.image_url,
                      'sort_order', i.sort_order,
                      'available', public.menu_item_available(i.id),
                      'modifier_group_ids', COALESCE((
                        SELECT jsonb_agg(l.group_id ORDER BY l.sort_order)
                        FROM public.menu_item_modifier_groups l WHERE l.item_id = i.id
                      ), '[]'::jsonb)
                    ) ORDER BY i.sort_order)
                    FROM public.menu_items i WHERE i.category_id = c.id AND i.is_hidden = false
                  ), '[]'::jsonb)
                ) ORDER BY c.sort_order)
                FROM public.menu_categories c WHERE c.is_hidden = false
              ), '[]'::jsonb),
              'modifier_groups', COALESCE((
                SELECT jsonb_agg(jsonb_build_object(
                  'id', g.id, 'name', g.name, 'allow_multiple', g.allow_multiple,
                  'options', COALESCE((
                    SELECT jsonb_agg(jsonb_build_object(
                      'id', o.id, 'name', o.name, 'price_delta_cents', o.price_delta_cents
                    ) ORDER BY o.sort_order)
                    FROM public.menu_modifier_options o WHERE o.group_id = g.id
                  ), '[]'::jsonb)
                ) ORDER BY g.sort_order)
                FROM public.menu_modifier_groups g
              ), '[]'::jsonb)
            );
          ELSE
            RETURN jsonb_build_object(
              'menu', jsonb_build_object('id', v_menu_id, 'kind', v_kind, 'name', v_name, 'data', v_data),
              'shop', v_shop,
              'categories', '[]'::jsonb, 'modifier_groups', '[]'::jsonb
            );
          END IF;
        END $$;
        REVOKE ALL ON FUNCTION public.get_menu_by_id(bigint) FROM PUBLIC;
        GRANT EXECUTE ON FUNCTION public.get_menu_by_id(bigint) TO anon, authenticated;

        -- Storage bucket for menu item photos (migration 013).
        INSERT INTO storage.buckets (id, name, public)
        VALUES ('menu-assets', 'menu-assets', true)
        ON CONFLICT (id) DO UPDATE SET public = true;

        DROP POLICY IF EXISTS "menu-assets public read" ON storage.objects;
        DROP POLICY IF EXISTS "menu-assets auth insert" ON storage.objects;
        DROP POLICY IF EXISTS "menu-assets auth update" ON storage.objects;
        DROP POLICY IF EXISTS "menu-assets auth delete" ON storage.objects;

        CREATE POLICY "menu-assets public read" ON storage.objects
          FOR SELECT TO public
          USING (bucket_id = 'menu-assets');
        CREATE POLICY "menu-assets auth insert" ON storage.objects
          FOR INSERT TO authenticated
          WITH CHECK (bucket_id = 'menu-assets');
        CREATE POLICY "menu-assets auth update" ON storage.objects
          FOR UPDATE TO authenticated
          USING (bucket_id = 'menu-assets')
          WITH CHECK (bucket_id = 'menu-assets');
        CREATE POLICY "menu-assets auth delete" ON storage.objects
          FOR DELETE TO authenticated
          USING (bucket_id = 'menu-assets');

        -- Atomic inventory deduction (prevents race conditions)
        DROP FUNCTION IF EXISTS deduct_inventory(BIGINT, NUMERIC);
        CREATE OR REPLACE FUNCTION deduct_inventory(item_id BIGINT, qty NUMERIC)
        RETURNS TABLE (
          out_id BIGINT,
          out_name TEXT,
          out_current_stock NUMERIC
        ) AS $$
        BEGIN
          RETURN QUERY
          UPDATE public.inventory AS inv
          SET current_stock = inv.current_stock - qty
          WHERE inv.id = item_id AND inv.current_stock >= qty
          RETURNING inv.id, inv.name, inv.current_stock;
        END;
        $$ LANGUAGE plpgsql SECURITY DEFINER;

        -- ==========================================
        -- APP USERS: unified allowlist. Mirrors api/install.js — no auth
        -- schema references (no FK to auth.users, no trigger on auth.users,
        -- no backfill SELECT against auth.users) because some Supabase
        -- project configs restrict those via the Management API. The
        -- claim-or-bootstrap logic lives in an RPC the client calls.
        -- ==========================================
        CREATE TABLE IF NOT EXISTS public.app_users (
          id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
          email        text NOT NULL UNIQUE,
          role         text NOT NULL DEFAULT 'employee',
          auth_user_id uuid UNIQUE,
          provider     text,
          created_by   uuid,
          created_at   timestamptz NOT NULL DEFAULT now(),
          disabled_at  timestamptz
        );
        CREATE INDEX IF NOT EXISTS idx_app_users_email_lower ON public.app_users (lower(email));

        CREATE OR REPLACE FUNCTION public.is_app_admin(p_user_id uuid)
        RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE
        SET search_path = public AS $$
          SELECT EXISTS (
            SELECT 1 FROM public.app_users
            WHERE auth_user_id = p_user_id AND role = 'admin' AND disabled_at IS NULL
          );
        $$;

        ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;

        DROP POLICY IF EXISTS "Users can read own row"        ON public.app_users;
        DROP POLICY IF EXISTS "Users can read pending row"    ON public.app_users;
        DROP POLICY IF EXISTS "Users can claim pending row"   ON public.app_users;
        DROP POLICY IF EXISTS "Admins can read all"           ON public.app_users;
        DROP POLICY IF EXISTS "Admins can insert"             ON public.app_users;
        DROP POLICY IF EXISTS "Admins can update"             ON public.app_users;
        DROP POLICY IF EXISTS "Admins can delete"             ON public.app_users;

        CREATE POLICY "Users can read own row" ON public.app_users
          FOR SELECT TO authenticated USING (auth_user_id = auth.uid());
        CREATE POLICY "Admins can read all" ON public.app_users
          FOR SELECT TO authenticated USING (public.is_app_admin(auth.uid()));
        CREATE POLICY "Admins can insert" ON public.app_users
          FOR INSERT TO authenticated WITH CHECK (public.is_app_admin(auth.uid()));
        CREATE POLICY "Admins can update" ON public.app_users
          FOR UPDATE TO authenticated
          USING (public.is_app_admin(auth.uid()))
          WITH CHECK (public.is_app_admin(auth.uid()));
        CREATE POLICY "Admins can delete" ON public.app_users
          FOR DELETE TO authenticated USING (public.is_app_admin(auth.uid()));

        -- Client calls this on every successful sign-in. See api/install.js
        -- for the contract docstring.
        CREATE OR REPLACE FUNCTION public.claim_or_bootstrap_app_user()
        RETURNS public.app_users
        LANGUAGE plpgsql SECURITY DEFINER
        SET search_path = public AS $$
        DECLARE
          v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
          v_uid   uuid := auth.uid();
          v_row   public.app_users%ROWTYPE;
        BEGIN
          IF v_email = '' OR v_uid IS NULL THEN RETURN NULL; END IF;

          UPDATE public.app_users
             SET auth_user_id = v_uid
           WHERE auth_user_id IS NULL
             AND lower(email) = v_email
             AND disabled_at IS NULL
          RETURNING * INTO v_row;
          IF FOUND THEN RETURN v_row; END IF;

          IF v_email LIKE '%@device.tinypos.com' THEN
            INSERT INTO public.app_users (email, role, auth_user_id, provider)
            VALUES (v_email, 'device', v_uid, 'email')
            ON CONFLICT (email) DO UPDATE
              SET auth_user_id = EXCLUDED.auth_user_id
              WHERE public.app_users.auth_user_id IS NULL
            RETURNING * INTO v_row;
            IF v_row.id IS NOT NULL THEN RETURN v_row; END IF;
          END IF;

          IF NOT EXISTS (SELECT 1 FROM public.app_users WHERE role = 'admin' LIMIT 1) THEN
            INSERT INTO public.app_users (email, role, auth_user_id, provider, created_by)
            VALUES (v_email, 'admin', v_uid, 'email', v_uid)
            ON CONFLICT (email) DO UPDATE
              SET auth_user_id = EXCLUDED.auth_user_id, role = 'admin'
            RETURNING * INTO v_row;
            RETURN v_row;
          END IF;

          SELECT * INTO v_row FROM public.app_users
          WHERE auth_user_id = v_uid AND disabled_at IS NULL
          LIMIT 1;
          RETURN v_row;
        END;
        $$;
        GRANT EXECUTE ON FUNCTION public.claim_or_bootstrap_app_user() TO authenticated;

        -- Schema version stamp — mirror of api/install.js. Bump together
        -- with src/utils/schemaVersion.js on every schema change.
        CREATE TABLE IF NOT EXISTS public.schema_meta (
          key text PRIMARY KEY,
          value text NOT NULL,
          updated_at timestamptz NOT NULL DEFAULT now()
        );
        ALTER TABLE public.schema_meta ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "Authenticated can read schema_meta" ON public.schema_meta;
        CREATE POLICY "Authenticated can read schema_meta" ON public.schema_meta
          FOR SELECT TO authenticated USING (true);
        INSERT INTO public.schema_meta (key, value, updated_at)
        VALUES ('schema_version', '0.2', now())
        ON CONFLICT (key) DO UPDATE
          SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at;
      `;

      const sqlRes = await fetch(`/api/run-sql?projectRef=${selectedProject}`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${setupToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ query: schemaQuery }),
      });

      const sqlData = await sqlRes.json().catch(() => ({}));
      if (!sqlRes.ok) throw new Error(sqlData.message || 'Falló la instalación de la base de datos');

      // --- STEP C: Create the Admin Auth User (GOD MODE) ---
      setLoadingStep('Creando usuario administrador...');

      // Burn-after-reading: the service_role key lives only in this closure.
      // We never write it to localStorage — daily POS operation must run on
      // the anon key alone. The Admin "Dispositivos" tab re-fetches a
      // short-lived PAT via OAuth each time it needs to provision hardware.
      const adminClient = createClient(projectUrl, serviceRoleObj.api_key);

      // Use the auth.admin namespace to bypass email confirmation
      const { error: authError } = await adminClient.auth.admin.createUser({
        email: adminEmail,
        password: adminPassword,
        email_confirm: true
      });

      if (authError) throw new Error(`Error en Auth: ${authError.message}`);

      // --- STEP D: Complete! Boot the app ---
      setLoadingStep('¡Todo listo! Arrancando tinypos...');

      // Wait a moment for UX
      await new Promise(r => setTimeout(r, 1000));

      // Pass the new keys to App.jsx to save and boot
      onComplete(projectUrl, anonKeyObj.api_key);

    } catch (err) {
      console.error(err);
      showAlert(err.message, 'error');
    } finally {
      setLoading(false);
      setLoadingStep('');
    }
  };


  const handleStandardConnect = async (e) => {
    e.preventDefault();
    if (!selectedProject) {
      return showAlert("Por favor selecciona un proyecto", "error");
    }

    setLoading(true);
    setLoadingStep('Obteniendo credenciales del dispositivo...');

    try {
      // We reuse the exact same proxy we built for the installation!
      const keysRes = await fetch(`/api/get-keys?projectRef=${selectedProject}`, {
        headers: { Authorization: `Bearer ${setupToken}` }
      });
      
      const keysData = await keysRes.json();
      if (!keysRes.ok) throw new Error("No se pudieron obtener las credenciales");
      
      const anonKeyObj = keysData.find(k => k.name === 'anon');
      if (!anonKeyObj) throw new Error("Llave anónima no encontrada");

      // Burn-after-reading: we do NOT persist service_role to localStorage.
      // Device provisioning re-authorizes via OAuth on demand from the
      // Admin "Dispositivos" tab.

      // Calculate the Project URL
      const projectRef = projects.find(p => p.id === selectedProject)?.id;
      const projectUrl = `https://${projectRef}.supabase.co`;

      // Pass the keys back to App.jsx so it saves them to localStorage and reloads!
      onComplete(projectUrl, anonKeyObj.api_key);

    } catch (err) {
      console.error(err);
      showAlert(err.message, 'error');
    } finally {
      setLoading(false);
      setLoadingStep('');
    }
  };

  // ==========================================
  // RENDER UI
  // ==========================================

  // --- STYLE TOKENS ---
  const styles = {
    page: {
      display: 'flex',
      minHeight: '100dvh',
      backgroundColor: 'var(--bg-app)',
      justifyContent: 'center',
      alignItems: 'center',
      fontFamily: 'var(--font-main, system-ui)',
      padding: '20px',
      boxSizing: 'border-box',
    },
    card: {
      background: 'var(--bg-surface)',
      padding: '40px',
      borderRadius: '24px',
      width: '100%',
      maxWidth: '440px',
      boxShadow: '0 20px 50px rgba(0,0,0,0.18)',
      border: '1px solid var(--border)',
      position: 'relative',
    },
    backBtn: {
      background: 'transparent',
      border: 'none',
      color: 'var(--text-muted)',
      cursor: 'pointer',
      marginBottom: '24px',
      display: 'inline-flex',
      alignItems: 'center',
      gap: '6px',
      padding: '6px 10px',
      borderRadius: '8px',
      fontSize: '0.9rem',
      fontWeight: 600,
      transition: 'background 0.15s ease, color 0.15s ease',
    },
    iconBubble: {
      width: '72px',
      height: '72px',
      background: 'rgba(242, 139, 5, 0.12)',
      color: 'var(--brand-color)',
      borderRadius: '20px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: '2.2rem',
      margin: '0 auto 16px',
    },
    title: {
      margin: '0 0 8px 0',
      color: 'var(--text-main)',
      fontSize: '1.6rem',
      fontWeight: 800,
      textAlign: 'center',
      letterSpacing: '-0.01em',
    },
    subtitle: {
      color: 'var(--text-muted)',
      margin: 0,
      fontSize: '0.95rem',
      textAlign: 'center',
      lineHeight: 1.5,
    },
    label: {
      fontWeight: 700,
      color: 'var(--text-main)',
      fontSize: '0.85rem',
      display: 'block',
      marginBottom: '8px',
    },
    inputWrap: { position: 'relative' },
    inputIcon: {
      position: 'absolute',
      left: '14px',
      top: '50%',
      transform: 'translateY(-50%)',
      color: 'var(--text-muted)',
      fontSize: '1.1rem',
      pointerEvents: 'none',
    },
    input: {
      width: '100%',
      padding: '13px 14px 13px 42px',
      borderRadius: '12px',
      border: '1px solid var(--border)',
      background: 'var(--bg-main)',
      color: 'var(--text-main)',
      fontSize: '1rem',
      boxSizing: 'border-box',
      outline: 'none',
      transition: 'border-color 0.15s ease, box-shadow 0.15s ease, background 0.15s ease',
    },
    select: {
      width: '100%',
      padding: '13px 14px 13px 42px',
      borderRadius: '12px',
      border: '1px solid var(--border)',
      background: 'var(--bg-main)',
      color: 'var(--text-main)',
      fontSize: '1rem',
      boxSizing: 'border-box',
      outline: 'none',
      appearance: 'none',
      cursor: 'pointer',
      transition: 'border-color 0.15s ease, box-shadow 0.15s ease',
    },
    stepCard: {
      background: 'var(--bg-main)',
      padding: '18px',
      borderRadius: '16px',
      border: '1px solid var(--border)',
    },
    stepHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: '10px',
      marginBottom: '12px',
    },
    stepBadge: {
      width: '26px',
      height: '26px',
      borderRadius: '50%',
      background: 'var(--brand-color)',
      color: '#fff',
      fontSize: '0.8rem',
      fontWeight: 800,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    primaryBtn: {
      padding: '16px',
      background: 'var(--brand-color)',
      color: '#fff',
      border: 'none',
      borderRadius: '14px',
      cursor: 'pointer',
      fontWeight: 700,
      fontSize: '1.05rem',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '10px',
      boxShadow: '0 8px 24px rgba(242, 139, 5, 0.35)',
      transition: 'box-shadow 0.2s ease, transform 0.05s ease, opacity 0.2s ease',
    },
    successBtn: {
      padding: '16px',
      background: 'var(--color-success)',
      color: '#fff',
      border: 'none',
      borderRadius: '14px',
      cursor: 'pointer',
      fontWeight: 700,
      fontSize: '1.05rem',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '10px',
      boxShadow: '0 8px 22px rgba(39, 174, 96, 0.3)',
      transition: 'box-shadow 0.2s ease, opacity 0.2s ease',
    },
    helperText: {
      fontSize: '0.8rem',
      color: 'var(--text-muted)',
      margin: '0 0 12px 0',
      lineHeight: 1.45,
    },
  };

  const isFullScreenLoading = loading && (loadingStep || isConnectingExisting);

  return (
    <>
      {/* Local style block — pseudo-selectors and keyframes can't be inlined */}
      <style>{`
        .setup-input:focus,
        .setup-select:focus {
          border-color: var(--brand-color) !important;
          box-shadow: 0 0 0 4px rgba(242, 139, 5, 0.15);
          background: var(--bg-surface) !important;
        }
        .setup-back:hover {
          background: var(--bg-main);
          color: var(--text-main);
        }
        .setup-cta-supabase {
          position: relative;
          overflow: hidden;
        }
        .setup-cta-supabase::after {
          content: '';
          position: absolute;
          inset: 0;
          border-radius: inherit;
          box-shadow: 0 0 0 0 rgba(62, 179, 112, 0.55);
          animation: setup-pulse 2.2s ease-out infinite;
          pointer-events: none;
        }
        .setup-cta-supabase:hover {
          box-shadow: 0 14px 32px rgba(62, 179, 112, 0.45);
        }
        @keyframes setup-pulse {
          0%   { box-shadow: 0 0 0 0   rgba(62, 179, 112, 0.55); }
          70%  { box-shadow: 0 0 0 18px rgba(62, 179, 112, 0);   }
          100% { box-shadow: 0 0 0 0   rgba(62, 179, 112, 0);    }
        }
        @keyframes setup-text-pulse {
          0%, 100% { opacity: 0.55; }
          50%      { opacity: 1; }
        }
        .setup-loading-text {
          animation: setup-text-pulse 1.6s ease-in-out infinite;
        }
        @keyframes setup-toast-in {
          from { opacity: 0; transform: translate(-50%, -12px); }
          to   { opacity: 1; transform: translate(-50%, 0); }
        }
        .setup-toast {
          animation: setup-toast-in 0.25s ease-out both;
        }
        .setup-primary-cta:hover {
          box-shadow: 0 12px 30px rgba(242, 139, 5, 0.45);
        }
        .setup-success-cta:hover {
          box-shadow: 0 12px 30px rgba(39, 174, 96, 0.45);
        }
        .setup-primary-cta:disabled,
        .setup-success-cta:disabled {
          opacity: 0.65;
          cursor: not-allowed;
        }
      `}</style>

      <div style={styles.page}>
        <div className="fade-in" style={styles.card}>

          {/* --- TOAST ALERT --- */}
          {customAlert.show && (
            <div
              className="setup-toast"
              style={{
                position: 'absolute',
                top: '-14px',
                left: '50%',
                transform: 'translateX(-50%)',
                minWidth: '260px',
                maxWidth: '90%',
                padding: '12px 16px',
                background: customAlert.type === 'error' ? 'var(--color-danger)' : 'var(--color-success)',
                color: '#fff',
                borderRadius: '12px',
                boxShadow: '0 12px 28px rgba(0,0,0,0.18)',
                display: 'flex',
                alignItems: 'center',
                gap: '10px',
                fontSize: '0.9rem',
                fontWeight: 600,
                zIndex: 10,
              }}
            >
              <Icon
                icon={customAlert.type === 'error' ? 'lucide:alert-triangle' : 'lucide:check-circle-2'}
                width="18"
              />
              <span style={{ flex: 1 }}>{customAlert.message}</span>
            </div>
          )}

          {/* --- BACK BUTTON --- */}
          <button
            type="button"
            onClick={onBack}
            className="setup-back"
            style={styles.backBtn}
          >
            <Icon icon="lucide:arrow-left" /> Volver
          </button>

          {/* --- FULL-SCREEN LOADING VIEW --- */}
          {isFullScreenLoading ? (
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '24px',
              padding: '40px 8px 16px',
              textAlign: 'center',
            }}>
              <div className="spinner" />
              <div>
                <h3 style={{
                  margin: '0 0 6px 0',
                  color: 'var(--text-main)',
                  fontSize: '1.15rem',
                  fontWeight: 700,
                }}>
                  Trabajando…
                </h3>
                <p
                  className="setup-loading-text"
                  style={{
                    margin: 0,
                    color: 'var(--text-muted)',
                    fontSize: '0.95rem',
                    minHeight: '1.2em',
                  }}
                >
                  {loadingStep || 'Un momento…'}
                </p>
              </div>
            </div>
          ) : (
            <>
              {/* --- HEADER --- */}
              <div style={{ textAlign: 'center', marginBottom: '28px' }}>
                <div style={styles.iconBubble}>
                  <Icon icon={isConnectingExisting ? 'lucide:plug-zap' : 'lucide:sparkles'} />
                </div>
                <h2 style={styles.title}>
                  {isConnectingExisting ? 'Vincular Dispositivo' : 'Instalación Automática'}
                </h2>
                <p style={styles.subtitle}>
                  {isConnectingExisting
                    ? 'Autoriza con Supabase y elige el proyecto existente al que quieres vincular este dispositivo.'
                    : 'Autoriza a tinypos y configuraremos tu base de datos en segundos.'}
                </p>
              </div>

              {/* --- SCENARIO A: PRE-OAUTH (both modes need the token) --- */}
              {!setupToken && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '18px' }}>
                  <div style={{
                    background: 'var(--bg-main)',
                    border: '1px solid var(--border)',
                    borderRadius: '14px',
                    padding: '14px 16px',
                    display: 'flex',
                    gap: '12px',
                    alignItems: 'flex-start',
                  }}>
                    <Icon icon="lucide:shield-check" style={{ color: 'var(--color-success)', fontSize: '1.3rem', marginTop: '2px', flexShrink: 0 }} />
                    <p style={{ margin: 0, color: 'var(--text-muted)', fontSize: '0.88rem', lineHeight: 1.5 }}>
                      {isConnectingExisting
                        ? 'Conexión segura. tinypos sólo leerá las llaves del proyecto que elijas — no modificará tu base de datos.'
                        : 'Conexión segura. tinypos sólo solicitará los permisos mínimos para crear las tablas necesarias.'}
                    </p>
                  </div>

                  <button
                    type="button"
                    onClick={() => {
                      // Stash the current mode so the post-OAuth return into App.jsx
                      // can restore 'connect' vs 'new' instead of always defaulting to 'new'.
                      try { sessionStorage.setItem('tinypos_setup_mode', initialMode); } catch (_) {}

                      const clientId = import.meta.env.VITE_SUPABASE_MANAGEMENT_CLIENT_ID;
                      const redirectUri = `${window.location.origin}/api/auth/callback`;

                      // List the exact permissions we checked in the dashboard
                      const requiredScopes = "api_gateway_keys_read api_keys_read database_read database_write";

                      // We use encodeURIComponent to safely put the spaces into the URL
                      window.location.href = `https://api.supabase.com/v1/oauth/authorize?client_id=${clientId}&redirect_uri=${redirectUri}&response_type=code&state=install&scope=${encodeURIComponent(requiredScopes)}`;
                    }}
                    className="setup-cta-supabase"
                    style={{
                      padding: '18px',
                      background: '#3eb370',
                      color: '#fff',
                      border: 'none',
                      borderRadius: '14px',
                      cursor: 'pointer',
                      fontWeight: 700,
                      fontSize: '1.05rem',
                      display: 'flex',
                      justifyContent: 'center',
                      alignItems: 'center',
                      gap: '10px',
                      boxShadow: '0 10px 28px rgba(62, 179, 112, 0.4)',
                      transition: 'box-shadow 0.2s ease',
                    }}
                  >
                    <Icon icon="mdi:database-sync" width="22" />
                    Conectar con Supabase
                  </button>

                  {onShowGuide && (
                    <button
                      type="button"
                      onClick={onShowGuide}
                      style={{
                        background: 'transparent',
                        border: 'none',
                        color: 'var(--text-muted)',
                        cursor: 'pointer',
                        fontSize: '0.88rem',
                        textDecoration: 'underline',
                        padding: '4px',
                      }}
                    >
                      ¿No tienes una cuenta de Supabase?
                    </button>
                  )}
                </div>
              )}

              {/* --- SCENARIO B: POST-OAUTH — install (new) OR link (connect) --- */}
              {setupToken && (
                <form
                  onSubmit={isConnectingExisting ? handleStandardConnect : handleHolyGrailInstall}
                  style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}
                >

                  {/* Step 1 — Project */}
                  <div style={styles.stepCard}>
                    <div style={styles.stepHeader}>
                      <div style={styles.stepBadge}>1</div>
                      <label style={{ ...styles.label, marginBottom: 0 }}>Selecciona tu Proyecto</label>
                    </div>

                    {projects.length === 0 ? (
                      <div style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '10px',
                        padding: '12px 14px',
                        background: 'rgba(231, 76, 60, 0.08)',
                        border: '1px solid rgba(231, 76, 60, 0.25)',
                        borderRadius: '10px',
                        color: 'var(--color-danger)',
                        fontSize: '0.85rem',
                      }}>
                        <Icon icon="lucide:alert-circle" width="18" />
                        <span>No se encontraron proyectos. Crea uno vacío en Supabase primero.</span>
                      </div>
                    ) : (
                      <div style={styles.inputWrap}>
                        <Icon icon="lucide:database" style={styles.inputIcon} />
                        <select
                          className="setup-select"
                          value={selectedProject}
                          onChange={e => setSelectedProject(e.target.value)}
                          required
                          style={{
                            ...styles.select,
                            backgroundImage: `url("data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8' fill='none'%3e%3cpath d='M1 1.5L6 6.5L11 1.5' stroke='%236b7280' stroke-width='1.6' stroke-linecap='round' stroke-linejoin='round'/%3e%3c/svg%3e")`,
                            backgroundRepeat: 'no-repeat',
                            backgroundPosition: 'right 16px center',
                            paddingRight: '42px',
                          }}
                        >
                          <option value="" disabled>Selecciona un proyecto...</option>
                          {projects.map(p => (
                            <option key={p.id} value={p.id}>{p.name}</option>
                          ))}
                        </select>
                      </div>
                    )}
                  </div>

                  {/* Step 2 — Admin (only when installing from scratch) */}
                  {!isConnectingExisting && (
                  <div style={styles.stepCard}>
                    <div style={styles.stepHeader}>
                      <div style={styles.stepBadge}>2</div>
                      <label style={{ ...styles.label, marginBottom: 0 }}>Crea tu cuenta de Administrador</label>
                    </div>
                    <p style={styles.helperText}>
                      Esta será tu llave maestra (RLS) para entrar al sistema.
                    </p>

                    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                      <div style={styles.inputWrap}>
                        <Icon icon="lucide:mail" style={styles.inputIcon} />
                        <input
                          className="setup-input"
                          type="email"
                          placeholder="Correo electrónico"
                          value={adminEmail}
                          onChange={e => setAdminEmail(e.target.value)}
                          required
                          style={styles.input}
                        />
                      </div>
                      <div style={styles.inputWrap}>
                        <Icon icon="lucide:lock" style={styles.inputIcon} />
                        <input
                          className="setup-input"
                          type="password"
                          placeholder="Contraseña segura"
                          value={adminPassword}
                          onChange={e => setAdminPassword(e.target.value)}
                          required
                          style={styles.input}
                        />
                      </div>
                    </div>
                  </div>
                  )}

                  <button
                    type="submit"
                    disabled={loading || projects.length === 0}
                    className="setup-success-cta"
                    style={{ ...styles.successBtn, marginTop: '4px' }}
                  >
                    <Icon icon={isConnectingExisting ? 'lucide:log-in' : 'lucide:rocket'} width="20" />
                    <span>{isConnectingExisting ? 'Acceder a tinypos' : 'Instalar tinypos'}</span>
                  </button>
                </form>
              )}
            </>
          )}
        </div>
      </div>
    </>
  );
}
