// Bilingual help content for the in-app Help page (Admin tab + Register modal).
//
// Prose lives here instead of translations.js on purpose: translations.js is a
// flat key->string map that's great for buttons but painful for multi-paragraph
// articles. Each language below is an ordered list of sections with the same
// shape, so HelpTab can render either one by picking the array for the active
// language (see useTranslation().lang).
//
// Section shape:
//   {
//     id:    stable id (matches the Admin tab id where applicable),
//     group: 'register' | 'admin',
//     icon:  Iconify id (reuse the tab's own icon),
//     badges: optional ['advanced'] | ['cloud'] | ['advanced','cloud'],
//     title: heading,
//     what:  one-paragraph "what it does",
//     how:   one-paragraph "how it works",
//     do:    [{ action, steps }]  // "what you can do & how"
//   }
//
// `id`, `group`, `icon` and `badges` are kept identical across languages; only
// the human-readable strings differ. Keep the two arrays in the same order.

const en = [
  // ---------------------------------------------------------------- Register
  {
    id: 'register-overview',
    group: 'register',
    icon: 'lucide:shopping-cart',
    title: 'Register (Point of Sale)',
    what: 'The everyday sales screen where cashiers build tickets, add products, and take payment. It is optimized for fast, high-volume touch use and works fully offline.',
    how: 'Open tickets live on the device (IndexedDB) so nothing is lost if the connection drops; sales upload automatically when the network returns. The layout adapts to your business type — a classic category grid (Cafe), a step-by-step drill-down (OrderFlow), or a floor map (Tables) — chosen per device in General Settings.',
    do: [
      { action: 'Start a ticket', steps: 'Tap "New" in the tickets list, then pick a category and tap products to add them.' },
      { action: 'Switch between open tickets', steps: 'Use the tickets sidebar (or the tickets button on mobile) to jump between orders.' },
      { action: 'Edit a line', steps: 'Tap an item in the ticket to change quantity or remove it.' },
      { action: 'Change the layout', steps: 'Go to Admin → General Settings → Layout mode (this is per-device).' },
    ],
  },
  {
    id: 'register-ticket',
    group: 'register',
    icon: 'lucide:coffee',
    title: 'Building a ticket & modifiers',
    what: 'Add products to a ticket and customize them with modifier groups — extra shots, milk swaps, sizes, and other options.',
    how: 'When an item has modifier groups a modal opens so you choose options before it lands on the ticket. Modifiers can deduct extra inventory (an extra shot pulls extra grams) or substitute ingredients (an oat-milk swap recalculates cost). Each item also carries its own IVA treatment, so tax is computed per line, not as a flat rate.',
    do: [
      { action: 'Add a customized item', steps: 'Tap the product; in the modifier modal choose the options, then confirm.' },
      { action: 'Change quantity', steps: 'Tap the line on the ticket and use the quantity editor.' },
      { action: 'Remove an item', steps: 'Open the line and choose remove, or swipe/tap the delete control.' },
    ],
  },
  {
    id: 'register-checkout',
    group: 'register',
    icon: 'lucide:credit-card',
    title: 'Checkout & payment',
    what: 'Close a ticket by taking payment — cash, card, or transfer — with support for tips, split payments, and partial paid items.',
    how: 'Checkout carves the real IVA out of the tax-inclusive total and records the payment method(s) so Analytics can reconcile card/cash/transfer. You can split a bill N ways, pay specific lines, and capture a tip that is tracked separately as a custodial amount (not counted as revenue).',
    do: [
      { action: 'Take payment', steps: 'Tap "Pay & Close", choose the payment method, and confirm.' },
      { action: 'Add a tip', steps: 'In checkout, enter a tip amount or pick a percentage before confirming.' },
      { action: 'Split the bill', steps: 'Switch to split mode, choose N ways or select specific lines, then settle each part.' },
      { action: 'Refund a sale', steps: 'Open the sale from Admin → Receipt History and refund the whole ticket or specific lines.' },
    ],
  },
  {
    id: 'register-discounts',
    group: 'register',
    icon: 'lucide:badge-percent',
    title: 'Discounts at the register',
    what: 'Apply a manual percentage or flat discount to the current ticket.',
    how: 'Discounts come from the rules you define in Admin → Auto Discounts, and applying one is PIN-protected. If "Require Manager for Sensitive Actions" is on, an Employee is prompted for a Manager/Admin PIN and the override is written to the activity log.',
    do: [
      { action: 'Apply a discount', steps: 'Open the discount control on the ticket, pick a rule (or amount), and confirm the PIN if prompted.' },
      { action: 'Remove a discount', steps: 'Reopen the discount control and clear it before payment.' },
    ],
  },
  {
    id: 'register-expenses',
    group: 'register',
    icon: 'lucide:banknote',
    title: 'Expenses (Gasto)',
    what: 'Log a cash expense — supplies, small purchases, petty cash — directly from the register.',
    how: 'Expenses are stored with the shift and subtracted in the cash count and in Analytics net profit. They sync across devices using a cloud local_id so the same expense is not double-counted.',
    do: [
      { action: 'Record an expense', steps: 'Tap "Gasto", enter the amount and a note, and save (a PIN may be required).' },
      { action: 'Review expenses', steps: 'See them reflected in the corte cash count and in Admin → Analytics.' },
    ],
  },
  {
    id: 'register-corte',
    group: 'register',
    icon: 'lucide:calculator',
    title: 'Corte de caja (shift close)',
    what: 'Close out the till: count cash, compare against expected, and record the shift total.',
    how: 'The corte tallies sales, tips, and expenses for the session and warns you if the counted cash does not match the expected amount. It is PIN-protected and logged to the activity feed. It can be turned off in General Settings for shops that do not need it.',
    do: [
      { action: 'Run a corte', steps: 'Tap "Corte", enter the counted cash, review the discrepancy warning, and confirm.' },
      { action: 'Enable/disable corte', steps: 'Admin → General Settings → Enable corte.' },
    ],
  },
  {
    id: 'register-loyalty',
    group: 'register',
    icon: 'lucide:star',
    title: 'Loyalty capture',
    what: 'Attach a customer to a sale by phone number so they earn loyalty rewards.',
    how: 'Points accrue via a database trigger bound to the sale insert, so resending a receipt never double-counts. Programs are configured in Admin → Loyalty Program.',
    do: [
      { action: 'Add a customer to a sale', steps: 'Open the loyalty capture during the order, enter the phone number, and confirm.' },
      { action: 'Set up rewards', steps: 'Configure recurring or single-use programs in Admin → Loyalty Program.' },
    ],
  },
  {
    id: 'register-lock',
    group: 'register',
    icon: 'lucide:lock',
    title: 'Lock, cashiers & security',
    what: 'Lock the register between users and switch cashiers with PINs.',
    how: 'Each cashier has a role (employee / manager / admin). Two optional toggles tighten access: "Restrict Admin Panel" hides the Admin button for non-admins, and "Require Manager for Sensitive Actions" asks for a Manager/Admin PIN on refunds, voids, expenses, and manual discounts. Both are off by default.',
    do: [
      { action: 'Lock the screen', steps: 'Tap "Lock"; the next user unlocks with their PIN.' },
      { action: 'Switch cashier', steps: 'Lock, then unlock with a different cashier PIN.' },
      { action: 'Turn on restrictions', steps: 'Admin → General Settings → "Seguridad y Accesos".' },
    ],
  },
  {
    id: 'register-sync',
    group: 'register',
    icon: 'lucide:refresh-cw',
    title: 'Sync status',
    what: 'Shows whether the device is online and whether any sales are still waiting to upload.',
    how: 'The app is offline-first: everything is saved locally first and a background queue uploads when the connection returns. The status pill opens a panel showing pending items.',
    do: [
      { action: 'Check sync', steps: 'Tap the connection pill in the action bar to open the sync panel.' },
      { action: 'Inspect stuck data', steps: 'Admin → Devices → Pending Sync inspector (PIN required) to review or discard queued items.' },
    ],
  },

  // ------------------------------------------------------------------- Admin
  {
    id: 'analytics',
    group: 'admin',
    icon: 'lucide:bar-chart-3',
    badges: ['advanced'],
    title: 'Analytics',
    what: 'Your money dashboard: revenue, true net profit, top sellers, and cost of goods for a chosen period.',
    how: 'It reads sales stored locally (offline-first) and computes true profit by subtracting COGS and wastage via the recipe/inventory engine, allocating fees, de-duplicating opex, and treating tips as a custodial liability with their own ledger. The Excel export reconciles 1:1 with the on-screen totals.',
    do: [
      { action: 'Change the period', steps: 'Use the time-range selector at the top (or set a custom date range).' },
      { action: 'Read the headline numbers', steps: 'Revenue, gross, and net cards; top items; and sales split by payment method.' },
      { action: 'Export a report', steps: 'Tap Download to generate a multi-sheet Excel workbook.' },
    ],
  },
  {
    id: 'orders',
    group: 'admin',
    icon: 'lucide:receipt',
    title: 'Receipt History',
    what: 'The record of every completed sale — items, totals, tip, payment method, and status (completed, partially refunded, or voided) — filtered by the same time range as Analytics. This is also where all refunds happen.',
    how: 'Sales come from the cloud with the local cache as a fallback, so history is visible even offline. Refunds are the important part and support three modes: (1) Full — returns the whole remaining balance and marks the sale refunded; (2) Custom amount — returns any partial amount; (3) By item — pick exactly which lines and how many units to return. Line-level refunds are cumulative (a line already partly returned only offers the units still eligible) and are stored per line, so multi-vendor settlement charges each refund back to the exact product/vendor. Every refund is logged to the Activity Log, and under strict mode an Employee needs a manager PIN to issue one.',
    do: [
      { action: 'Filter and find a sale', steps: 'Use the time-range/date selector at the top, then scroll to the ticket you need.' },
      { action: 'Refund the whole sale', steps: 'Open the sale, tap Refund, choose "Refund all", pick how to handle the tip, and confirm.' },
      { action: 'Refund a custom amount', steps: 'In the refund dialog choose "Custom", type the amount, and confirm — the sale becomes partially refunded.' },
      { action: 'Refund specific items', steps: 'Choose "By item", set the quantity to return on each line (only still-refundable units are offered), and confirm.' },
      { action: 'Decide the tip on a refund', steps: 'Pick Keep tip, Proportional, or Full — full refunds default to returning the tip, partials default to keeping it.' },
      { action: 'Resend or reprint a receipt', steps: 'Open the sale and share it again via WhatsApp, save it as a PNG, or reprint — loyalty is never double-counted.' },
    ],
  },
  {
    id: 'menu',
    group: 'admin',
    icon: 'lucide:coffee',
    title: 'Menu Editor',
    what: 'Create and manage the catalog: products, prices, categories, photos, and each item\'s tax treatment.',
    how: 'Items carry a price, an optional photo (uploaded through a crop modal, converted to WebP, stored in Supabase), an IVA treatment (iva16 / tasa0 / exento), and can be tied to a recipe for costing. Categories can be hidden, and the same photo shows in the register grid and the public menu.',
    do: [
      { action: 'Add or edit an item', steps: 'Open the item editor, set name/price/category, and save.' },
      { action: 'Add a photo', steps: 'Upload an image and crop it in the modal; it is optimized automatically.' },
      { action: 'Set the tax treatment', steps: 'Choose iva16, tasa0, or exento per item so checkout computes IVA correctly.' },
      { action: 'Hide a category', steps: 'Toggle its visibility; hidden categories drop out of the register and public menu.' },
    ],
  },
  {
    id: 'modifiers',
    group: 'admin',
    icon: 'lucide:sparkles',
    title: 'Modifiers',
    what: 'A reusable library of modifier groups (extra shot, milk choice, size…) that you attach to menu items.',
    how: 'Groups are defined once and linked to many items. A group can be hidden without breaking its links, so un-hiding restores it everywhere without re-attaching. Modifier options can adjust price and inventory deductions/substitutions.',
    do: [
      { action: 'Create a group', steps: 'Add a group, then add its options with prices and any inventory effect.' },
      { action: 'Attach to items', steps: 'Link the group to the products that should offer it.' },
      { action: 'Hide a group', steps: 'Toggle it hidden; links are preserved for when you un-hide it.' },
    ],
  },
  {
    id: 'calculator',
    group: 'admin',
    icon: 'lucide:flask-conical',
    badges: ['advanced'],
    title: 'Recipes Builder',
    what: 'Define the bill of materials (recipe) for each product so the app knows its real cost and can suggest a price.',
    how: 'A recipe lists ingredients and quantities drawn from Inventory. From live ingredient cost the COGS/Profit engine computes cost per item and, given a target margin, recommends a price. Recipes also drive COGS and wastage in Analytics.',
    do: [
      { action: 'Build a recipe', steps: 'Pick ingredients and quantities; the cost per unit updates live.' },
      { action: 'Get a suggested price', steps: 'Enter a target margin to see the recommended price.' },
      { action: 'Publish', steps: 'Attach the recipe to the menu item so its cost feeds Analytics.' },
    ],
  },
  {
    id: 'inventory',
    group: 'admin',
    icon: 'lucide:database',
    badges: ['advanced'],
    title: 'Inventory & The Roaster',
    what: 'Tracks raw stock (grams, milliliters, pieces…), what each unit costs, and how stock is consumed, transformed, and replenished. It feeds true COGS in Analytics, powers low-stock alerts, and — for coffee shops — includes a Roaster that turns green beans into roasted stock with real lot/batch traceability.',
    how: 'Every item has a current stock, a unit, and a unit cost derived from what you paid. Recipes draw stock down automatically at each sale, and every movement is written to an audit trail. Restocks and roasts also post their cost to the expense ledger tagged by the pocket you paid from (cash drawer vs. bank), so the corte and P&L stay honest. The Roaster (Transform) consumes an amount of a source item and produces a target item by the FINAL YIELD WEIGHT — you enter what actually came out of the drum, not a shrinkage estimate — plus an optional operational cost. Lot-tracked items (roasted coffee, batches) keep dated lots, and sales draw from the OLDEST lot first (FIFO); a batch report shows exactly which sales pulled from a given roast. The Audit action lets you log a loss/waste or a surplus with a reason and keeps lot remainders truthful. Per-item reorder points raise "needs reordering" alerts; items without one fall back to a default (2000 for grams, 10 otherwise). Deletions are logged with a reason.',
    do: [
      { action: 'Add an item', steps: 'Enter name, starting stock, unit, and total cost paid (unit cost is derived); pick the payment pocket.' },
      { action: 'Restock', steps: 'Open an item and record the added quantity and cost — it posts to the expense ledger for the corte.' },
      { action: 'Roast / transform', steps: 'Use Transform: pick the source and amount used, then enter the final yield weight of the target and any operational cost.' },
      { action: 'Trace a batch (FIFO)', steps: 'For lot-tracked items, expand a lot to see which sales drew from that roast; oldest lots are consumed first.' },
      { action: 'Log waste or a correction', steps: 'Use Audit on an item to record a loss/waste or surplus with a reason; lots stay accurate.' },
      { action: 'Set a reorder point', steps: 'Give an item a per-item threshold so a low-stock alert appears when it is reached.' },
    ],
  },
  {
    id: 'vendors',
    group: 'admin',
    icon: 'lucide:store',
    badges: ['advanced'],
    title: 'Vendors & Settlement',
    what: 'For consignment shops: tag products with the vendor that owns them and run a per-vendor settlement report.',
    how: 'Vendor attribution is snapshotted onto each sale line at checkout, so historic settlements survive renames. Two split models are supported: commission % (on gross or pre-IVA) or cost-recovery (house keeps production cost, vendor takes profit). A payout ledger records money actually paid and freezes the statement, so the report shows owed − paid = balance. A Books Summary separates commission income from vendor payable and itemizes IVA.',
    do: [
      { action: 'Tag a product', steps: 'Assign a vendor to menu items in the Menu Editor or here.' },
      { action: 'Run a settlement', steps: 'Pick a vendor and period, choose the split model, and review the statement.' },
      { action: 'Record a payout', steps: 'Post a payment to the ledger; it freezes that statement and updates the balance.' },
    ],
  },
  {
    id: 'tables',
    group: 'admin',
    icon: 'lucide:armchair',
    badges: ['advanced'],
    title: 'Tables',
    what: 'Lay out your dining room on a visual floor plan and track tickets by table.',
    how: 'A floor-plan registry stores tables (number, name, seats, shape, position) as a canvas document. Tickets link to a table id (resolved by scanning, not a hard foreign key), and the register\'s Tables layout tracks open orders on the map.',
    do: [
      { action: 'Design the floor', steps: 'Add tables to the canvas and set seats, shape, and position.' },
      { action: 'Use it at the register', steps: 'Switch the layout to Tables (General Settings) to open tickets from the map.' },
    ],
  },
  {
    id: 'menus',
    group: 'admin',
    icon: 'lucide:layout-list',
    badges: ['cloud'],
    title: 'Public Menus (TinyMenu)',
    what: 'Build and publish digital menus — served at /menu with QR codes, TV/kiosk mode, and a drag-and-drop designer.',
    how: 'A shop can have multiple named menus (breakfast, lunch, seasonal) with a weekly/time-of-day schedule that auto-picks the active one. Menus can be catalog-driven templates, an uploaded PDF/PNG carousel, or a full canvas design (shapes, text, images, bound catalog items). Every save writes a version snapshot you can restore, and each menu has a shareable QR/link.',
    do: [
      { action: 'Create a menu', steps: 'Add a named menu and choose a template, upload, or canvas design.' },
      { action: 'Schedule it', steps: 'Set the weekly and time-of-day schedule so the right menu shows automatically.' },
      { action: 'Share', steps: 'Open the share card for the QR code and copy-link; TV mode lives at /menu/tv.' },
      { action: 'Restore a version', steps: 'Browse snapshots and restore any prior save.' },
    ],
  },
  {
    id: 'receipt',
    group: 'admin',
    icon: 'lucide:printer',
    title: 'Receipt Settings',
    what: 'Customize the printed/digital receipt: logo, header and footer text, tax display, and a live preview.',
    how: 'Settings are saved to your shop profile and applied to every receipt. You can show the tax breakdown, add a legal disclaimer, and include a CFDI QR that links to the invoicing portal.',
    do: [
      { action: 'Add a logo and text', steps: 'Upload a logo and set the header/subheader/footer lines.' },
      { action: 'Configure tax display', steps: 'Enable the tax line and set the rate label.' },
      { action: 'Show the CFDI QR', steps: 'Turn on the CFDI QR so customers can self-invoice; preview it on the right.' },
    ],
  },
  {
    id: 'cfdi',
    group: 'admin',
    icon: 'lucide:file-text',
    badges: ['cloud'],
    title: 'CFDI Portal',
    what: 'A request inbox that COLLECTS your customers\' fiscal data so you can invoice them. Important: this portal does NOT generate the CFDI. You still create the actual invoice manually in the SAT portal (or your PAC), then come back here to record it. Think of it as the bridge that gathers the RFC / tax details and tracks which tickets are still pending vs. already invoiced.',
    how: 'When a receipt shows the CFDI QR, the customer scans it, enters their fiscal data (RFC, name, tax regime, use), and that creates a request that lands in this tab under "Pending". The sale\'s IVA was already extracted per line at checkout, so you have the exact amounts. You then go to the SAT portal outside the POS, issue the CFDI there, and mark the request as Issued by entering the folio it returned — that moves it to the "Issued" tab and lets you share it back to the customer. You can also Reopen a request (send it back to pending) or Cancel it. For everything nobody invoiced individually, use Factura Global: at month end you issue ONE global invoice in the SAT for the period, then close that period here so those tickets can no longer be requested individually — customers see a notice that their ticket was included in the month\'s global invoice.',
    do: [
      { action: 'Turn the portal on', steps: 'Enable the CFDI QR in Receipt Settings so it prints on receipts; requests then arrive here.' },
      { action: 'Read a pending request', steps: 'Open the "Pending" tab to see the customer\'s fiscal data and the ticket amounts.' },
      { action: 'Issue the invoice (in the SAT)', steps: 'Use that fiscal data to create the CFDI in the SAT portal or your PAC — this step happens outside the POS.' },
      { action: 'Record the folio', steps: 'Back here, open the request and enter the folio the SAT gave you to mark it Issued.' },
      { action: 'Reopen or cancel', steps: 'Send a request back to pending, or cancel it, if the customer\'s data was wrong.' },
      { action: 'Close a Factura Global period', steps: 'After issuing the month\'s global invoice in the SAT, close that period here to freeze it and stop individual requests.' },
    ],
  },
  {
    id: 'discounts',
    group: 'admin',
    icon: 'lucide:percent',
    badges: ['advanced'],
    title: 'Auto Discounts & Promotions',
    what: 'A full promotions engine, not just a flat "10% off" toggle. You can build percentage or fixed-amount discounts, Buy X Get Y (BOGO) deals, and combo/bundle prices, then decide whether they apply automatically or must be entered by a cashier — with conditions, schedules, and spending limits.',
    how: 'Each rule has three parts. (1) Trigger: Automatic rules apply themselves the moment the cart qualifies; Manual rules are applied by a cashier and can require a promo code. (2) Reward: Standard (percentage or flat, applied to the whole cart or a specific item), Buy X Get Y, or a fixed Combo price for a set of items. (3) Conditions & limits: required items with minimum quantities, a minimum subtotal, customer type, days of the week, a start/end date, and a time-of-day window — plus guardrails like max redemptions, max per day, a max budget, a max discount cap, priority (which rule wins), whether it can stack with others, and whether it needs manager approval. Rules can be recurring or single-use, and applying a discount at the register is PIN-protected (a manager override under strict mode, logged to Activity).',
    do: [
      { action: 'Create a basic discount', steps: 'Name it, choose Standard, pick percentage or flat, set the value, and target the whole cart or one item.' },
      { action: 'Make it automatic or code-based', steps: 'Set Trigger to Automatic to apply on qualifying carts, or Manual and add a code the cashier types in.' },
      { action: 'Build a BOGO or combo', steps: 'Choose "Buy X Get Y" (set buy/pay quantities and the item) or "Combo price" (pick items and a bundle price).' },
      { action: 'Add conditions', steps: 'Require certain items/quantities, a minimum subtotal, specific days, or a date and time-of-day window.' },
      { action: 'Set limits & priority', steps: 'Cap redemptions, per-day uses, budget, or max discount; set priority and whether it may stack.' },
      { action: 'Require approval', steps: 'Turn on approval so applying the rule needs a manager PIN.' },
    ],
  },
  {
    id: 'loyalty',
    group: 'admin',
    icon: 'lucide:star',
    badges: ['advanced'],
    title: 'Loyalty Program',
    what: 'Set up phone-number loyalty with recurring or single-use rewards.',
    how: 'Accrual is bound to sales by a database trigger, so receipt resends never double-count. Cashiers attach a customer at the register by phone number; rewards are defined here.',
    do: [
      { action: 'Create a program', steps: 'Choose recurring or single-use and set the reward rules.' },
      { action: 'Track members', steps: 'Customers accrue automatically once attached to sales at the register.' },
    ],
  },
  {
    id: 'team',
    group: 'admin',
    icon: 'lucide:users',
    badges: ['cloud'],
    title: 'Team & PINs',
    what: 'Manage cashiers, their PINs, and their roles (employee / manager / admin).',
    how: 'Adding a cashier writes a securely hashed PIN via a server RPC; removing one wipes it. Roles drive the optional access restrictions, and everyone allowed to sign in is tracked in a single allowlist.',
    do: [
      { action: 'Add a cashier', steps: 'Enter a name, set a PIN, and choose a role.' },
      { action: 'Change a role', steps: 'Use the role selector to set employee, manager, or admin.' },
      { action: 'Remove a cashier', steps: 'Delete the entry; their PIN is revoked.' },
    ],
  },
  {
    id: 'devices',
    group: 'admin',
    icon: 'lucide:tablet-smartphone',
    badges: ['cloud'],
    title: 'Devices',
    what: 'Provision new POS terminals and inspect stuck sync data without touching the Supabase dashboard.',
    how: 'Adding a device provisions it through the app (optionally with a custom sign-in email). The Pending Sync inspector (PIN required) lets you review and surgically discard queued offline data if a sync error occurs.',
    do: [
      { action: 'Add a device', steps: 'Use the device form; optionally set a custom email instead of the auto-generated one.' },
      { action: 'Fix a sync problem', steps: 'Open the Pending Sync inspector, re-enter your PIN, and review or discard queued items.' },
    ],
  },
  {
    id: 'tips',
    group: 'admin',
    icon: 'lucide:wallet',
    badges: ['advanced'],
    title: 'Tips Ledger',
    what: 'Track tips collected and paid out, kept separate from revenue.',
    how: 'Tips are treated as a custodial liability with their own ledger — collected at checkout, refundable line-aware, and reconciled in Analytics so they never inflate profit.',
    do: [
      { action: 'Review tips', steps: 'See tips collected for the period and any payouts.' },
      { action: 'Record a payout', steps: 'Log tip distributions so the ledger balances.' },
    ],
  },
  {
    id: 'activity',
    group: 'admin',
    icon: 'lucide:history',
    badges: ['advanced', 'cloud'],
    title: 'Activity Log',
    what: 'An audit trail of important events: sales, refunds, settings changes, menu edits, inventory deletions, and cortes.',
    how: 'Every logged event stores metadata — including manager-override details (who authorized a refund/void/expense/discount) when strict mode is on — so you can trace sensitive actions.',
    do: [
      { action: 'Review activity', steps: 'Scroll or filter the feed to find an event.' },
      { action: 'Audit an override', steps: 'Open a sensitive action to see who authorized it.' },
    ],
  },
  {
    id: 'settings',
    group: 'admin',
    icon: 'lucide:settings',
    title: 'General Settings',
    what: 'The control center for the whole system: branding, business type and register layout, language, security and access rules, the register\'s operational toggles, hardware, and database maintenance. Several of these settings change how every other screen behaves, so it\'s the first place to set up a new shop.',
    how: 'Settings save to your shop profile in the cloud and mirror to local storage so branding and boot are instant even offline. A few are deliberately per-device rather than per-shop: the Layout mode (Cafe grid / OrderFlow / Tables) and the printer size live on the device you set them on, so each terminal can differ. Advanced Mode is the master switch that unlocks the deeper tabs (Recipes, Inventory, Vendors, Tables, Discounts, Loyalty, Tips) and can be protected with its own PIN. The two access toggles under "Seguridad y Accesos" — Restrict Admin Panel and Require Manager for Sensitive Actions — are off by default and drive the role checks used across the Register and Admin. The Update Schema button compares the database version the app expects against what your server has and, when an update is available, runs an idempotent OAuth-backed migration so your database catches up safely.',
    do: [
      { action: 'Change the language', steps: 'Set System Language to English or Español — the whole app (and this help) follows it instantly.' },
      { action: 'Set business type & layout', steps: 'Pick your business type, then choose the register layout (Cafe grid, OrderFlow, or Tables) — layout is per device.' },
      { action: 'Brand the app', steps: 'Upload a logo, set the shop name, and pick a brand color and light/dark theme.' },
      { action: 'Turn on Advanced Mode', steps: 'Enable it to unlock Recipes, Inventory, Vendors, Tables, Discounts, Loyalty, and Tips — optionally set a PIN to protect it.' },
      { action: 'Tighten access', steps: 'Under "Seguridad y Accesos", turn on Restrict Admin Panel and/or Require Manager for Sensitive Actions.' },
      { action: 'Tune register behavior', steps: 'Enable/disable the corte, set the low-stock threshold, order numbers, auto-lock, and printer size.' },
      { action: 'Update the database', steps: 'If it shows "Update available", run Actualizar esquema to apply the latest migrations (safe to re-run).' },
      { action: 'Danger zone', steps: 'Disconnect the device or reset data only when you mean to — these are destructive.' },
    ],
  },
];

const es = [
  // ---------------------------------------------------------------- Register
  {
    id: 'register-overview',
    group: 'register',
    icon: 'lucide:shopping-cart',
    title: 'Caja registradora (Punto de venta)',
    what: 'La pantalla de ventas del día a día donde los cajeros arman tickets, agregan productos y cobran. Está optimizada para uso táctil rápido y de alto volumen, y funciona sin conexión.',
    how: 'Los tickets abiertos viven en el dispositivo (IndexedDB), así no se pierde nada si se cae la conexión; las ventas suben solas cuando la red regresa. El diseño se adapta a tu tipo de negocio — rejilla de categorías (Cafetería), flujo paso a paso (OrderFlow) o mapa de mesas (Mesas) — elegido por dispositivo en Configuración General.',
    do: [
      { action: 'Iniciar un ticket', steps: 'Toca "Nuevo" en la lista de tickets, elige una categoría y toca los productos para agregarlos.' },
      { action: 'Cambiar entre tickets abiertos', steps: 'Usa la barra de tickets (o el botón de tickets en móvil) para saltar entre órdenes.' },
      { action: 'Editar una línea', steps: 'Toca un artículo del ticket para cambiar la cantidad o quitarlo.' },
      { action: 'Cambiar el diseño', steps: 'Ve a Admin → Configuración General → Modo de diseño (es por dispositivo).' },
    ],
  },
  {
    id: 'register-ticket',
    group: 'register',
    icon: 'lucide:coffee',
    title: 'Armar un ticket y modificadores',
    what: 'Agrega productos a un ticket y personalízalos con grupos de modificadores — shots extra, cambio de leche, tamaños y otras opciones.',
    how: 'Cuando un artículo tiene grupos de modificadores se abre un modal para que elijas opciones antes de agregarlo al ticket. Los modificadores pueden descontar inventario extra (un shot extra jala más gramos) o sustituir ingredientes (cambio a leche de avena recalcula el costo). Cada artículo lleva su propio tratamiento de IVA, así que el impuesto se calcula por línea, no con una tasa fija.',
    do: [
      { action: 'Agregar un artículo personalizado', steps: 'Toca el producto; en el modal de modificadores elige las opciones y confirma.' },
      { action: 'Cambiar la cantidad', steps: 'Toca la línea del ticket y usa el editor de cantidad.' },
      { action: 'Quitar un artículo', steps: 'Abre la línea y elige quitar, o usa el control de eliminar.' },
    ],
  },
  {
    id: 'register-checkout',
    group: 'register',
    icon: 'lucide:credit-card',
    title: 'Cobro y pago',
    what: 'Cierra un ticket cobrando — efectivo, tarjeta o transferencia — con soporte para propinas, pagos divididos y líneas pagadas parcialmente.',
    how: 'El cobro separa el IVA real del total (que ya incluye impuesto) y registra el/los método(s) de pago para que Analíticas concilie tarjeta/efectivo/transferencia. Puedes dividir una cuenta en N partes, pagar líneas específicas y capturar propina, que se rastrea aparte como monto en custodia (no cuenta como ingreso).',
    do: [
      { action: 'Cobrar', steps: 'Toca "Pagar y cerrar", elige el método de pago y confirma.' },
      { action: 'Agregar propina', steps: 'En el cobro, escribe un monto de propina o elige un porcentaje antes de confirmar.' },
      { action: 'Dividir la cuenta', steps: 'Cambia a modo dividido, elige N partes o selecciona líneas específicas y liquida cada parte.' },
      { action: 'Reembolsar una venta', steps: 'Abre la venta en Admin → Historial de recibos y reembolsa el ticket completo o líneas específicas.' },
    ],
  },
  {
    id: 'register-discounts',
    group: 'register',
    icon: 'lucide:badge-percent',
    title: 'Descuentos en caja',
    what: 'Aplica un descuento manual en porcentaje o monto fijo al ticket actual.',
    how: 'Los descuentos vienen de las reglas que defines en Admin → Descuentos automáticos, y aplicarlos requiere PIN. Si "Requerir gerente para acciones sensibles" está activo, a un empleado se le pide un PIN de gerente/admin y la anulación se registra en la bitácora.',
    do: [
      { action: 'Aplicar un descuento', steps: 'Abre el control de descuento en el ticket, elige una regla (o monto) y confirma el PIN si se solicita.' },
      { action: 'Quitar un descuento', steps: 'Vuelve a abrir el control de descuento y bórralo antes del pago.' },
    ],
  },
  {
    id: 'register-expenses',
    group: 'register',
    icon: 'lucide:banknote',
    title: 'Gastos',
    what: 'Registra un gasto en efectivo — insumos, compras pequeñas, caja chica — directo desde la caja.',
    how: 'Los gastos se guardan con el turno y se restan en el conteo de efectivo y en la utilidad neta de Analíticas. Se sincronizan entre dispositivos con un local_id en la nube para no contarse doble.',
    do: [
      { action: 'Registrar un gasto', steps: 'Toca "Gasto", escribe el monto y una nota, y guarda (puede pedir PIN).' },
      { action: 'Revisar gastos', steps: 'Se reflejan en el conteo del corte y en Admin → Analíticas.' },
    ],
  },
  {
    id: 'register-corte',
    group: 'register',
    icon: 'lucide:calculator',
    title: 'Corte de caja',
    what: 'Cierra la caja: cuenta el efectivo, compáralo con lo esperado y registra el total del turno.',
    how: 'El corte suma ventas, propinas y gastos del turno y te avisa si el efectivo contado no coincide con lo esperado. Requiere PIN y queda en la bitácora. Se puede desactivar en Configuración General para negocios que no lo necesiten.',
    do: [
      { action: 'Hacer un corte', steps: 'Toca "Corte", escribe el efectivo contado, revisa la advertencia de diferencia y confirma.' },
      { action: 'Activar/desactivar el corte', steps: 'Admin → Configuración General → Activar corte.' },
    ],
  },
  {
    id: 'register-loyalty',
    group: 'register',
    icon: 'lucide:star',
    title: 'Captura de lealtad',
    what: 'Vincula un cliente a una venta por número de teléfono para que acumule recompensas.',
    how: 'Los puntos se acumulan mediante un disparador en la base de datos ligado a la inserción de la venta, así reenviar un recibo nunca cuenta doble. Los programas se configuran en Admin → Programa de lealtad.',
    do: [
      { action: 'Agregar un cliente a la venta', steps: 'Abre la captura de lealtad durante la orden, escribe el teléfono y confirma.' },
      { action: 'Configurar recompensas', steps: 'Define programas recurrentes o de un solo uso en Admin → Programa de lealtad.' },
    ],
  },
  {
    id: 'register-lock',
    group: 'register',
    icon: 'lucide:lock',
    title: 'Bloqueo, cajeros y seguridad',
    what: 'Bloquea la caja entre usuarios y cambia de cajero con PIN.',
    how: 'Cada cajero tiene un rol (empleado / gerente / admin). Dos interruptores opcionales refuerzan el acceso: "Restringir panel de administración" oculta el botón Admin a los no administradores, y "Requerir gerente para acciones sensibles" pide un PIN de gerente/admin en reembolsos, cancelaciones, gastos y descuentos manuales. Ambos vienen apagados.',
    do: [
      { action: 'Bloquear la pantalla', steps: 'Toca "Bloquear"; el siguiente usuario desbloquea con su PIN.' },
      { action: 'Cambiar de cajero', steps: 'Bloquea y luego desbloquea con el PIN de otro cajero.' },
      { action: 'Activar restricciones', steps: 'Admin → Configuración General → "Seguridad y Accesos".' },
    ],
  },
  {
    id: 'register-sync',
    group: 'register',
    icon: 'lucide:refresh-cw',
    title: 'Estado de sincronización',
    what: 'Muestra si el dispositivo está en línea y si hay ventas pendientes por subir.',
    how: 'La app es "offline-first": todo se guarda primero localmente y una cola en segundo plano sube los datos cuando regresa la conexión. La píldora de estado abre un panel con los pendientes.',
    do: [
      { action: 'Revisar la sincronización', steps: 'Toca la píldora de conexión en la barra de acciones para abrir el panel.' },
      { action: 'Inspeccionar datos atorados', steps: 'Admin → Dispositivos → inspector de sincronización pendiente (pide PIN) para revisar o descartar elementos en cola.' },
    ],
  },

  // ------------------------------------------------------------------- Admin
  {
    id: 'analytics',
    group: 'admin',
    icon: 'lucide:bar-chart-3',
    badges: ['advanced'],
    title: 'Analíticas',
    what: 'Tu panel de dinero: ingresos, utilidad neta real, más vendidos y costo de la mercancía en el periodo elegido.',
    how: 'Usa las ventas guardadas localmente (funciona sin conexión) y calcula la utilidad real restando el costo de insumos (COGS) y la merma con el motor de recetas/inventario, asignando comisiones, evitando duplicar gastos operativos y tratando las propinas como pasivo en custodia con su propia bitácora. El export a Excel cuadra 1:1 con los totales en pantalla.',
    do: [
      { action: 'Cambiar el periodo', steps: 'Usa el selector de rango arriba (o define un rango de fechas personalizado).' },
      { action: 'Leer las cifras clave', steps: 'Tarjetas de ingresos, bruto y neto; más vendidos; y ventas por método de pago.' },
      { action: 'Exportar un reporte', steps: 'Toca Descargar para generar un libro de Excel con varias hojas.' },
    ],
  },
  {
    id: 'orders',
    group: 'admin',
    icon: 'lucide:receipt',
    title: 'Historial de recibos',
    what: 'El registro de cada venta completada — artículos, totales, propina, método de pago y estado (completada, reembolsada parcialmente o cancelada) — filtrado por el mismo rango de tiempo que Analíticas. Aquí también se hacen todos los reembolsos.',
    how: 'Las ventas vienen de la nube con la caché local como respaldo, así que el historial se ve incluso sin conexión. Lo importante son los reembolsos, con tres modos: (1) Total — devuelve todo el saldo restante y marca la venta como reembolsada; (2) Monto personalizado — devuelve cualquier parte; (3) Por artículo — eliges exactamente qué líneas y cuántas unidades devolver. Los reembolsos por línea son acumulativos (una línea ya devuelta en parte solo ofrece las unidades que aún quedan) y se guardan por línea, para que la liquidación por proveedor cargue cada reembolso al producto/proveedor exacto. Cada reembolso queda en la Bitácora de actividad, y en modo estricto un empleado necesita un PIN de gerente para hacerlo.',
    do: [
      { action: 'Filtrar y encontrar una venta', steps: 'Usa el selector de rango/fecha arriba y desplázate hasta el ticket que necesites.' },
      { action: 'Reembolsar toda la venta', steps: 'Abre la venta, toca Reembolsar, elige "Reembolsar todo", decide qué hacer con la propina y confirma.' },
      { action: 'Reembolsar un monto personalizado', steps: 'En el diálogo elige "Personalizado", escribe el monto y confirma — la venta queda reembolsada parcialmente.' },
      { action: 'Reembolsar artículos específicos', steps: 'Elige "Por artículo", define cuántas unidades devolver por línea (solo ofrece las reembolsables) y confirma.' },
      { action: 'Decidir la propina en un reembolso', steps: 'Elige Conservar, Proporcional o Total — los reembolsos totales devuelven la propina por defecto; los parciales la conservan.' },
      { action: 'Reenviar o reimprimir un recibo', steps: 'Abre la venta y compártela por WhatsApp, guárdala como PNG o reimprímela — la lealtad nunca se cuenta doble.' },
    ],
  },
  {
    id: 'menu',
    group: 'admin',
    icon: 'lucide:coffee',
    title: 'Editor de menú',
    what: 'Crea y administra el catálogo: productos, precios, categorías, fotos y el tratamiento de impuesto de cada artículo.',
    how: 'Los artículos llevan precio, una foto opcional (subida por un modal de recorte, convertida a WebP y guardada en Supabase), un tratamiento de IVA (iva16 / tasa0 / exento) y pueden ligarse a una receta para costeo. Las categorías se pueden ocultar, y la misma foto aparece en la rejilla de la caja y en el menú público.',
    do: [
      { action: 'Agregar o editar un artículo', steps: 'Abre el editor, define nombre/precio/categoría y guarda.' },
      { action: 'Agregar una foto', steps: 'Sube una imagen y recórtala en el modal; se optimiza automáticamente.' },
      { action: 'Definir el impuesto', steps: 'Elige iva16, tasa0 o exento por artículo para que el cobro calcule bien el IVA.' },
      { action: 'Ocultar una categoría', steps: 'Cambia su visibilidad; las categorías ocultas salen de la caja y del menú público.' },
    ],
  },
  {
    id: 'modifiers',
    group: 'admin',
    icon: 'lucide:sparkles',
    title: 'Modificadores',
    what: 'Una biblioteca reutilizable de grupos de modificadores (shot extra, tipo de leche, tamaño…) que adjuntas a los artículos.',
    how: 'Los grupos se definen una vez y se ligan a muchos artículos. Un grupo se puede ocultar sin romper sus vínculos, así al mostrarlo de nuevo se restaura en todos lados sin volver a adjuntarlo. Las opciones pueden ajustar el precio y los descuentos/sustituciones de inventario.',
    do: [
      { action: 'Crear un grupo', steps: 'Agrega un grupo y luego sus opciones con precios y efecto en inventario.' },
      { action: 'Adjuntar a artículos', steps: 'Liga el grupo a los productos que deban ofrecerlo.' },
      { action: 'Ocultar un grupo', steps: 'Márcalo como oculto; los vínculos se conservan para cuando lo muestres.' },
    ],
  },
  {
    id: 'calculator',
    group: 'admin',
    icon: 'lucide:flask-conical',
    badges: ['advanced'],
    title: 'Constructor de recetas',
    what: 'Define la lista de materiales (receta) de cada producto para que la app conozca su costo real y sugiera un precio.',
    how: 'Una receta lista ingredientes y cantidades tomados de Inventario. Con el costo vivo de los ingredientes, el motor de COGS/utilidad calcula el costo por artículo y, dado un margen objetivo, recomienda un precio. Las recetas también alimentan el COGS y la merma en Analíticas.',
    do: [
      { action: 'Armar una receta', steps: 'Elige ingredientes y cantidades; el costo por unidad se actualiza en vivo.' },
      { action: 'Obtener un precio sugerido', steps: 'Escribe un margen objetivo para ver el precio recomendado.' },
      { action: 'Publicar', steps: 'Adjunta la receta al artículo del menú para que su costo alimente Analíticas.' },
    ],
  },
  {
    id: 'inventory',
    group: 'admin',
    icon: 'lucide:database',
    badges: ['advanced'],
    title: 'Inventario y el Tostador',
    what: 'Controla el stock de materia prima (gramos, mililitros, piezas…), cuánto cuesta cada unidad y cómo se consume, transforma y resurte. Alimenta el COGS real en Analíticas, genera las alertas de bajo stock y — para cafeterías — incluye un Tostador que convierte café verde en tostado con trazabilidad real por lote.',
    how: 'Cada artículo tiene stock actual, unidad y un costo unitario derivado de lo que pagaste. Las recetas descuentan stock automáticamente en cada venta y todo movimiento queda en una bitácora. Los resurtidos y tuestes también registran su costo en el libro de gastos, etiquetado por el bolsillo con el que pagaste (caja vs. banco), para que el corte y el P&L cuadren. El Tostador (Transformar) consume una cantidad de un artículo de origen y produce un artículo destino por el PESO FINAL OBTENIDO — escribes lo que de verdad salió del tambor, no una estimación de merma — más un costo operativo opcional. Los artículos con lote (café tostado, tandas) guardan lotes fechados, y las ventas consumen primero el lote MÁS ANTIGUO (FIFO); un reporte de tanda muestra exactamente qué ventas salieron de un tueste dado. La acción Auditar te deja registrar una pérdida/merma o un excedente con motivo y mantiene los remanentes de lote veraces. Los puntos de reorden por artículo generan alertas de "requiere resurtido"; los que no tienen usan un valor por defecto (2000 para gramos, 10 en otros casos). Los borrados se registran con motivo.',
    do: [
      { action: 'Agregar un artículo', steps: 'Escribe nombre, stock inicial, unidad y costo total pagado (el unitario se deriva); elige el bolsillo de pago.' },
      { action: 'Resurtir', steps: 'Abre un artículo y registra la cantidad y costo agregados — se anota en el libro de gastos para el corte.' },
      { action: 'Tostar / transformar', steps: 'Usa Transformar: elige el origen y la cantidad usada, luego escribe el peso final obtenido del destino y el costo operativo.' },
      { action: 'Rastrear una tanda (FIFO)', steps: 'En artículos con lote, expande un lote para ver qué ventas salieron de ese tueste; se consume primero el más antiguo.' },
      { action: 'Registrar merma o corrección', steps: 'Usa Auditar en un artículo para registrar una pérdida/merma o excedente con motivo; los lotes quedan correctos.' },
      { action: 'Definir un punto de reorden', steps: 'Dale a un artículo un umbral propio para que aparezca la alerta de bajo stock al alcanzarlo.' },
    ],
  },
  {
    id: 'vendors',
    group: 'admin',
    icon: 'lucide:store',
    badges: ['advanced'],
    title: 'Proveedores y liquidación',
    what: 'Para negocios de consignación: etiqueta productos con el proveedor dueño y genera un reporte de liquidación por proveedor.',
    how: 'La atribución de proveedor se congela en cada línea de venta al cobrar, así las liquidaciones históricas sobreviven a los cambios de nombre. Hay dos modelos: comisión % (sobre bruto o pre-IVA) o recuperación de costo (la casa se queda el costo de producción y el proveedor la utilidad). Una bitácora de pagos registra lo pagado y congela el estado, así el reporte muestra adeudado − pagado = saldo. Un Resumen contable separa el ingreso por comisión del pasivo por pagar al proveedor y desglosa el IVA.',
    do: [
      { action: 'Etiquetar un producto', steps: 'Asigna un proveedor a los artículos en el Editor de menú o aquí.' },
      { action: 'Generar una liquidación', steps: 'Elige proveedor y periodo, escoge el modelo de reparto y revisa el estado.' },
      { action: 'Registrar un pago', steps: 'Registra un pago en la bitácora; congela ese estado y actualiza el saldo.' },
    ],
  },
  {
    id: 'tables',
    group: 'admin',
    icon: 'lucide:armchair',
    badges: ['advanced'],
    title: 'Mesas',
    what: 'Distribuye tu salón en un plano visual y rastrea tickets por mesa.',
    how: 'Un registro de plano guarda las mesas (número, nombre, lugares, forma, posición) como documento de lienzo. Los tickets se ligan a un id de mesa (resuelto por escaneo, no una llave foránea rígida) y el diseño de Mesas en la caja rastrea las órdenes abiertas en el mapa.',
    do: [
      { action: 'Diseñar el salón', steps: 'Agrega mesas al lienzo y define lugares, forma y posición.' },
      { action: 'Usarlo en la caja', steps: 'Cambia el diseño a Mesas (Configuración General) para abrir tickets desde el mapa.' },
    ],
  },
  {
    id: 'menus',
    group: 'admin',
    icon: 'lucide:layout-list',
    badges: ['cloud'],
    title: 'Menús públicos (TinyMenu)',
    what: 'Crea y publica menús digitales — servidos en /menu con códigos QR, modo TV/kiosco y un diseñador de arrastrar y soltar.',
    how: 'Un negocio puede tener varios menús con nombre (desayuno, comida, temporada) con un horario semanal/por hora que elige el activo automáticamente. Los menús pueden ser plantillas basadas en el catálogo, un carrusel de PDF/PNG subido, o un diseño completo en lienzo (formas, texto, imágenes, artículos ligados al catálogo). Cada guardado crea una versión que puedes restaurar, y cada menú tiene un QR/enlace para compartir.',
    do: [
      { action: 'Crear un menú', steps: 'Agrega un menú con nombre y elige plantilla, subida o diseño en lienzo.' },
      { action: 'Programarlo', steps: 'Define el horario semanal y por hora para que el menú correcto aparezca solo.' },
      { action: 'Compartir', steps: 'Abre la tarjeta para el QR y copiar enlace; el modo TV vive en /menu/tv.' },
      { action: 'Restaurar una versión', steps: 'Explora los respaldos y restaura cualquier guardado anterior.' },
    ],
  },
  {
    id: 'receipt',
    group: 'admin',
    icon: 'lucide:printer',
    title: 'Configuración de recibo',
    what: 'Personaliza el recibo impreso/digital: logo, texto de encabezado y pie, despliegue de impuesto y una vista previa en vivo.',
    how: 'La configuración se guarda en el perfil de tu negocio y se aplica a cada recibo. Puedes mostrar el desglose de impuesto, agregar un aviso legal e incluir un QR de CFDI que enlaza al portal de facturación.',
    do: [
      { action: 'Agregar logo y texto', steps: 'Sube un logo y define las líneas de encabezado/subencabezado/pie.' },
      { action: 'Configurar el impuesto', steps: 'Activa la línea de impuesto y define la etiqueta de la tasa.' },
      { action: 'Mostrar el QR de CFDI', steps: 'Activa el QR de CFDI para que los clientes se autofacturen; míralo en la vista previa.' },
    ],
  },
  {
    id: 'cfdi',
    group: 'admin',
    icon: 'lucide:file-text',
    badges: ['cloud'],
    title: 'Portal CFDI',
    what: 'Un buzón de solicitudes que RECOPILA los datos fiscales de tus clientes para que puedas facturarles. Importante: este portal NO genera el CFDI. La factura se sigue haciendo manualmente en el portal del SAT (o tu PAC) y luego regresas aquí a registrarla. Es el puente que junta el RFC y los datos fiscales y lleva el control de qué tickets siguen pendientes vs. ya facturados.',
    how: 'Cuando un recibo muestra el QR de CFDI, el cliente lo escanea, ingresa sus datos fiscales (RFC, nombre, régimen, uso) y eso crea una solicitud que llega a esta pestaña en "Pendientes". El IVA de la venta ya se separó por línea al cobrar, así que tienes los montos exactos. Después vas al portal del SAT, fuera del POS, emites ahí el CFDI y marcas la solicitud como Emitida ingresando el folio que te devolvió — eso la pasa a la pestaña "Emitidas" y te deja compartirla con el cliente. También puedes Reabrir una solicitud (regresarla a pendiente) o Cancelarla. Para todo lo que nadie facturó individualmente, usa la Factura Global: a fin de mes emites UNA factura global en el SAT por el periodo y luego cierras ese periodo aquí para que esos tickets ya no se puedan solicitar individualmente — al cliente se le muestra el aviso de que su ticket se incluyó en la factura global del mes.',
    do: [
      { action: 'Activar el portal', steps: 'Activa el QR de CFDI en Configuración de recibo para que se imprima; las solicitudes llegan aquí.' },
      { action: 'Leer una solicitud pendiente', steps: 'Abre la pestaña "Pendientes" para ver los datos fiscales del cliente y los montos del ticket.' },
      { action: 'Emitir la factura (en el SAT)', steps: 'Usa esos datos fiscales para crear el CFDI en el portal del SAT o tu PAC — este paso es fuera del POS.' },
      { action: 'Registrar el folio', steps: 'De vuelta aquí, abre la solicitud e ingresa el folio que te dio el SAT para marcarla Emitida.' },
      { action: 'Reabrir o cancelar', steps: 'Regresa una solicitud a pendiente, o cancélala, si los datos del cliente estaban mal.' },
      { action: 'Cerrar un periodo de Factura Global', steps: 'Tras emitir la factura global del mes en el SAT, cierra ese periodo aquí para congelarlo y frenar solicitudes individuales.' },
    ],
  },
  {
    id: 'discounts',
    group: 'admin',
    icon: 'lucide:percent',
    badges: ['advanced'],
    title: 'Descuentos y promociones',
    what: 'Un motor completo de promociones, no solo un "10% de descuento". Puedes crear descuentos en porcentaje o monto fijo, ofertas Compra X Lleva Y (BOGO) y precios de combo/paquete, y decidir si se aplican solos o los captura un cajero — con condiciones, horarios y límites de gasto.',
    how: 'Cada regla tiene tres partes. (1) Disparador: las reglas Automáticas se aplican solas en cuanto el carrito califica; las Manuales las aplica un cajero y pueden requerir un código de promoción. (2) Recompensa: Estándar (porcentaje o fijo, sobre todo el carrito o un artículo específico), Compra X Lleva Y, o un precio de Combo fijo para un conjunto de artículos. (3) Condiciones y límites: artículos requeridos con cantidad mínima, un subtotal mínimo, tipo de cliente, días de la semana, fecha de inicio/fin y una ventana de horario — además de topes como máximo de canjes, máximo por día, presupuesto máximo, descuento máximo, prioridad (qué regla gana), si puede acumularse con otras y si requiere aprobación de gerente. Las reglas pueden ser recurrentes o de un solo uso, y aplicar un descuento en la caja requiere PIN (una anulación de gerente en modo estricto, registrada en Actividad).',
    do: [
      { action: 'Crear un descuento básico', steps: 'Ponle nombre, elige Estándar, escoge porcentaje o fijo, define el valor y aplícalo al carrito o a un artículo.' },
      { action: 'Automático o con código', steps: 'Pon el disparador en Automático para aplicar en carritos que califican, o en Manual y agrega un código que el cajero escribe.' },
      { action: 'Armar un BOGO o combo', steps: 'Elige "Compra X Lleva Y" (define cantidades y artículo) o "Precio de combo" (elige artículos y un precio de paquete).' },
      { action: 'Agregar condiciones', steps: 'Exige ciertos artículos/cantidades, un subtotal mínimo, días específicos o una fecha y ventana de horario.' },
      { action: 'Definir límites y prioridad', steps: 'Limita canjes, usos por día, presupuesto o descuento máximo; define prioridad y si puede acumularse.' },
      { action: 'Requerir aprobación', steps: 'Activa la aprobación para que aplicar la regla necesite un PIN de gerente.' },
    ],
  },
  {
    id: 'loyalty',
    group: 'admin',
    icon: 'lucide:star',
    badges: ['advanced'],
    title: 'Programa de lealtad',
    what: 'Configura lealtad por número de teléfono con recompensas recurrentes o de un solo uso.',
    how: 'La acumulación se liga a las ventas por un disparador de base de datos, así reenviar recibos nunca cuenta doble. Los cajeros vinculan un cliente en la caja por teléfono; las recompensas se definen aquí.',
    do: [
      { action: 'Crear un programa', steps: 'Elige recurrente o de un solo uso y define las reglas de recompensa.' },
      { action: 'Seguir a los miembros', steps: 'Los clientes acumulan automáticamente al vincularlos a las ventas en la caja.' },
    ],
  },
  {
    id: 'team',
    group: 'admin',
    icon: 'lucide:users',
    badges: ['cloud'],
    title: 'Equipo y PINs',
    what: 'Administra cajeros, sus PINs y sus roles (empleado / gerente / admin).',
    how: 'Agregar un cajero guarda un PIN cifrado de forma segura mediante un RPC del servidor; eliminarlo lo borra. Los roles rigen las restricciones de acceso opcionales, y todos los que pueden iniciar sesión se controlan en una sola lista de permitidos.',
    do: [
      { action: 'Agregar un cajero', steps: 'Escribe un nombre, define un PIN y elige un rol.' },
      { action: 'Cambiar un rol', steps: 'Usa el selector de rol para asignar empleado, gerente o admin.' },
      { action: 'Eliminar un cajero', steps: 'Borra el registro; su PIN se revoca.' },
    ],
  },
  {
    id: 'devices',
    group: 'admin',
    icon: 'lucide:tablet-smartphone',
    badges: ['cloud'],
    title: 'Dispositivos',
    what: 'Aprovisiona nuevas terminales POS e inspecciona datos de sincronización atorados sin entrar al panel de Supabase.',
    how: 'Agregar un dispositivo lo aprovisiona desde la app (opcionalmente con un correo de inicio de sesión personalizado). El inspector de sincronización pendiente (pide PIN) te deja revisar y descartar quirúrgicamente datos en cola si ocurre un error.',
    do: [
      { action: 'Agregar un dispositivo', steps: 'Usa el formulario; opcionalmente define un correo personalizado en vez del automático.' },
      { action: 'Arreglar un problema de sync', steps: 'Abre el inspector de sincronización pendiente, reingresa tu PIN y revisa o descarta elementos.' },
    ],
  },
  {
    id: 'tips',
    group: 'admin',
    icon: 'lucide:wallet',
    badges: ['advanced'],
    title: 'Bitácora de propinas',
    what: 'Controla las propinas cobradas y pagadas, separadas del ingreso.',
    how: 'Las propinas se tratan como pasivo en custodia con su propia bitácora — cobradas al pagar, reembolsables por línea y conciliadas en Analíticas para que nunca inflen la utilidad.',
    do: [
      { action: 'Revisar propinas', steps: 'Consulta las propinas cobradas del periodo y cualquier pago.' },
      { action: 'Registrar un pago', steps: 'Registra la distribución de propinas para que la bitácora cuadre.' },
    ],
  },
  {
    id: 'activity',
    group: 'admin',
    icon: 'lucide:history',
    badges: ['advanced', 'cloud'],
    title: 'Bitácora de actividad',
    what: 'Un registro de auditoría de eventos importantes: ventas, reembolsos, cambios de configuración, ediciones de menú, borrados de inventario y cortes.',
    how: 'Cada evento registrado guarda metadatos — incluidos los detalles de anulación de gerente (quién autorizó un reembolso/cancelación/gasto/descuento) cuando el modo estricto está activo — para rastrear acciones sensibles.',
    do: [
      { action: 'Revisar la actividad', steps: 'Desplázate o filtra el feed para encontrar un evento.' },
      { action: 'Auditar una anulación', steps: 'Abre una acción sensible para ver quién la autorizó.' },
    ],
  },
  {
    id: 'settings',
    group: 'admin',
    icon: 'lucide:settings',
    title: 'Configuración general',
    what: 'El centro de control de todo el sistema: marca, tipo de negocio y diseño de la caja, idioma, seguridad y reglas de acceso, los interruptores operativos de la caja, hardware y mantenimiento de la base de datos. Varias de estas opciones cambian el comportamiento de todas las demás pantallas, así que es el primer lugar para configurar un negocio nuevo.',
    how: 'La configuración se guarda en el perfil del negocio en la nube y se refleja en el almacenamiento local para que la marca y el arranque sean instantáneos incluso sin conexión. Algunas son a propósito por dispositivo y no por negocio: el Modo de diseño (rejilla Cafetería / OrderFlow / Mesas) y el tamaño de impresora viven en el dispositivo donde los definas, así cada terminal puede diferir. El Modo Avanzado es el interruptor maestro que desbloquea las pestañas más profundas (Recetas, Inventario, Proveedores, Mesas, Descuentos, Lealtad, Propinas) y se puede proteger con su propio PIN. Los dos interruptores de "Seguridad y Accesos" — Restringir panel de administración y Requerir gerente para acciones sensibles — vienen apagados y rigen las verificaciones de rol que se usan en la Caja y en Admin. El botón Actualizar esquema compara la versión de base de datos que espera la app con la de tu servidor y, cuando hay actualización, corre una migración idempotente respaldada por OAuth para ponerla al día con seguridad.',
    do: [
      { action: 'Cambiar el idioma', steps: 'Define el Idioma del Sistema en Inglés o Español — toda la app (y esta ayuda) lo sigue al instante.' },
      { action: 'Definir tipo de negocio y diseño', steps: 'Elige tu tipo de negocio y luego el diseño de la caja (rejilla Cafetería, OrderFlow o Mesas) — el diseño es por dispositivo.' },
      { action: 'Personalizar la marca', steps: 'Sube un logo, define el nombre del negocio y elige color de marca y tema claro/oscuro.' },
      { action: 'Activar el Modo Avanzado', steps: 'Actívalo para desbloquear Recetas, Inventario, Proveedores, Mesas, Descuentos, Lealtad y Propinas — opcionalmente ponle un PIN.' },
      { action: 'Reforzar el acceso', steps: 'En "Seguridad y Accesos", activa Restringir panel de administración y/o Requerir gerente para acciones sensibles.' },
      { action: 'Ajustar la caja', steps: 'Activa/desactiva el corte, define el umbral de bajo stock, los números de orden, el auto-bloqueo y el tamaño de impresora.' },
      { action: 'Actualizar la base de datos', steps: 'Si muestra "Actualización disponible", ejecuta Actualizar esquema para aplicar las últimas migraciones (seguro de repetir).' },
      { action: 'Zona de peligro', steps: 'Desconecta el dispositivo o reinicia los datos solo cuando de verdad lo quieras — son acciones destructivas.' },
    ],
  },
];

export const helpContent = { en, es };

// Group headings (rendered by HelpTab). Kept here so both languages stay together.
export const helpGroupLabels = {
  en: { register: 'Register', admin: 'Admin dashboard' },
  es: { register: 'Caja', admin: 'Panel de administración' },
};
