// Bilingual help content for the in-app Help page (Admin tab + Register modal).
//
// Prose lives here instead of translations.js on purpose: translations.js is a
// flat key->string map that's great for buttons but painful for multi-paragraph
// articles. Each language below is an ordered list of sections with the same
// shape, so HelpTab can render either one by picking the array for the active
// language (see useTranslation().lang).
//
// Section shape:
//   {
//     id:    stable id (matches the Admin tab id where applicable),
//     group: 'register' | 'admin',
//     icon:  Iconify id (reuse the tab's own icon),
//     badges: optional ['advanced'] | ['cloud'] | ['advanced','cloud'],
//     title: heading,
//     what:  one-paragraph "what it does",
//     how:   one-paragraph "how it works",
//     do:    [{ action, steps }]  // "what you can do & how"
//   }
//
// `id`, `group`, `icon` and `badges` are kept identical across languages; only
// the human-readable strings differ. Keep the two arrays in the same order.

const en = [
  // ---------------------------------------------------------------- Register
  {
    id: 'register-overview',
    group: 'register',
    icon: 'lucide:shopping-cart',
    title: 'Register (Point of Sale)',
    what: 'The everyday sales screen where cashiers build tickets, add products, and take payment. It is optimized for fast, high-volume touch use and works fully offline.',
    how: 'Open tickets live on the device (IndexedDB) so nothing is lost if the connection drops; sales upload automatically when the network returns. The layout adapts to your business type — a classic category grid (Cafe), a step-by-step drill-down (OrderFlow), or a floor map (Tables) — chosen per device in General Settings.',
    do: [
      { action: 'Start a ticket', steps: 'Tap "New" in the tickets list, then pick a category and tap products to add them.' },
      { action: 'Switch between open tickets', steps: 'Use the tickets sidebar (or the tickets button on mobile) to jump between orders.' },
      { action: 'Edit a line', steps: 'Tap an item in the ticket to change quantity or remove it.' },
      { action: 'Change the layout', steps: 'Go to Admin → General Settings → Layout mode (this is per-device).' },
    ],
  },
  {
    id: 'register-ticket',
    group: 'register',
    icon: 'lucide:coffee',
    title: 'Building a ticket & modifiers',
    what: 'Add products to a ticket and customize them with modifier groups — extra shots, milk swaps, sizes, and other options.',
    how: 'When an item has modifier groups a modal opens so you choose options before it lands on the ticket. Modifiers can deduct extra inventory (an extra shot pulls extra grams) or substitute ingredients (an oat-milk swap recalculates cost). Each item also carries its own IVA treatment, so tax is computed per line, not as a flat rate.',
    do: [
      { action: 'Add a customized item', steps: 'Tap the product; in the modifier modal choose the options, then confirm.' },
      { action: 'Change quantity', steps: 'Tap the line on the ticket and use the quantity editor.' },
      { action: 'Remove an item', steps: 'Open the line and choose remove, or swipe/tap the delete control.' },
    ],
  },
  {
    id: 'register-checkout',
    group: 'register',
    icon: 'lucide:credit-card',
    title: 'Checkout & payment',
    what: 'Close a ticket by taking payment — cash, card, or transfer — with support for tips, split payments, and partial paid items.',
    how: 'Checkout carves the real IVA out of the tax-inclusive total and records the payment method(s) so Analytics can reconcile card/cash/transfer. You can split a bill N ways, pay specific lines, and capture a tip that is tracked separately as a custodial amount (not counted as revenue).',
    do: [
      { action: 'Take payment', steps: 'Tap "Pay & Close", choose the payment method, and confirm.' },
      { action: 'Add a tip', steps: 'In checkout, enter a tip amount or pick a percentage before confirming.' },
      { action: 'Split the bill', steps: 'Switch to split mode, choose N ways or select specific lines, then settle each part.' },
      { action: 'Refund a sale', steps: 'Open the sale from Admin → Receipt History and refund the whole ticket or specific lines.' },
    ],
  },
  {
    id: 'register-discounts',
    group: 'register',
    icon: 'lucide:badge-percent',
    title: 'Discounts at the register',
    what: 'Apply a manual percentage or flat discount to the current ticket.',
    how: 'Discounts come from the rules you define in Admin → Auto Discounts, and applying one is PIN-protected. If "Require Manager for Sensitive Actions" is on, an Employee is prompted for a Manager/Admin PIN and the override is written to the activity log.',
    do: [
      { action: 'Apply a discount', steps: 'Open the discount control on the ticket, pick a rule (or amount), and confirm the PIN if prompted.' },
      { action: 'Remove a discount', steps: 'Reopen the discount control and clear it before payment.' },
    ],
  },
  {
    id: 'register-expenses',
    group: 'register',
    icon: 'lucide:banknote',
    title: 'Expenses (Gasto)',
    what: 'Log a cash expense — supplies, small purchases, petty cash — directly from the register.',
    how: 'Expenses are stored with the shift and subtracted in the cash count and in Analytics net profit. They sync across devices using a cloud local_id so the same expense is not double-counted.',
    do: [
      { action: 'Record an expense', steps: 'Tap "Gasto", enter the amount and a note, and save (a PIN may be required).' },
      { action: 'Review expenses', steps: 'See them reflected in the corte cash count and in Admin → Analytics.' },
    ],
  },
  {
    id: 'register-corte',
    group: 'register',
    icon: 'lucide:calculator',
    title: 'Corte de caja (shift close)',
    what: 'Close out the till: count cash, compare against expected, and record the shift total.',
    how: 'The corte tallies sales, tips, and expenses for the session and warns you if the counted cash does not match the expected amount. It is PIN-protected and logged to the activity feed. It can be turned off in General Settings for shops that do not need it.',
    do: [
      { action: 'Run a corte', steps: 'Tap "Corte", enter the counted cash, review the discrepancy warning, and confirm.' },
      { action: 'Enable/disable corte', steps: 'Admin → General Settings → Enable corte.' },
    ],
  },
  {
    id: 'register-loyalty',
    group: 'register',
    icon: 'lucide:star',
    title: 'Loyalty capture',
    what: 'Attach a customer to a sale by phone number so they earn loyalty rewards.',
    how: 'Points accrue via a database trigger bound to the sale insert, so resending a receipt never double-counts. Programs are configured in Admin → Loyalty Program.',
    do: [
      { action: 'Add a customer to a sale', steps: 'Open the loyalty capture during the order, enter the phone number, and confirm.' },
      { action: 'Set up rewards', steps: 'Configure recurring or single-use programs in Admin → Loyalty Program.' },
    ],
  },
  {
    id: 'register-lock',
    group: 'register',
    icon: 'lucide:lock',
    title: 'Lock, cashiers & security',
    what: 'Lock the register between users and switch cashiers with PINs.',
    how: 'Each cashier has a role (employee / manager / admin). Two optional toggles tighten access: "Restrict Admin Panel" hides the Admin button for non-admins, and "Require Manager for Sensitive Actions" asks for a Manager/Admin PIN on refunds, voids, expenses, and manual discounts. Both are off by default.',
    do: [
      { action: 'Lock the screen', steps: 'Tap "Lock"; the next user unlocks with their PIN.' },
      { action: 'Switch cashier', steps: 'Lock, then unlock with a different cashier PIN.' },
      { action: 'Turn on restrictions', steps: 'Admin → General Settings → "Seguridad y Accesos".' },
    ],
  },
  {
    id: 'register-sync',
    group: 'register',
    icon: 'lucide:refresh-cw',
    title: 'Sync status',
    what: 'Shows whether the device is online and whether any sales are still waiting to upload.',
    how: 'The app is offline-first: everything is saved locally first and a background queue uploads when the connection returns. The status pill opens a panel showing pending items.',
    do: [
      { action: 'Check sync', steps: 'Tap the connection pill in the action bar to open the sync panel.' },
      { action: 'Inspect stuck data', steps: 'Admin → Devices → Pending Sync inspector (PIN required) to review or discard queued items.' },
    ],
  },

  // ------------------------------------------------------------------- Admin
  {
    id: 'analytics',
    group: 'admin',
    icon: 'lucide:bar-chart-3',
    badges: ['advanced'],
    title: 'Analytics',
    what: 'Your money dashboard: revenue, true net profit, top sellers, and cost of goods for a chosen period.',
    how: 'It reads sales stored locally (offline-first) and computes true profit by subtracting COGS and wastage via the recipe/inventory engine, allocating fees, de-duplicating opex, and treating tips as a custodial liability with their own ledger. The Excel export reconciles 1:1 with the on-screen totals.',
    do: [
      { action: 'Change the period', steps: 'Use the time-range selector at the top (or set a custom date range).' },
      { action: 'Read the headline numbers', steps: 'Revenue, gross, and net cards; top items; and sales split by payment method.' },
      { action: 'Export a report', steps: 'Tap Download to generate a multi-sheet Excel workbook.' },
    ],
  },
  {
    id: 'orders',
    group: 'admin',
    icon: 'lucide:receipt',
    title: 'Receipt History',
    what: 'A searchable list of every sale with its items, totals, payment method, and status.',
    how: 'Sales are pulled from the cloud (with the local cache as fallback). Refunds are line-aware: you can return specific lines and the record keeps exactly which lines were refunded, so multi-vendor settlement charges the right line.',
    do: [
      { action: 'Find a sale', steps: 'Search or scroll the list and open a receipt for its details.' },
      { action: 'Refund', steps: 'Open a sale and refund the whole ticket, specific lines, or a custom amount.' },
      { action: 'Resend a receipt', steps: 'Open the sale and share the WhatsApp/PNG receipt again (loyalty is not double-counted).' },
    ],
  },
  {
    id: 'menu',
    group: 'admin',
    icon: 'lucide:coffee',
    title: 'Menu Editor',
    what: 'Create and manage the catalog: products, prices, categories, photos, and each item\'s tax treatment.',
    how: 'Items carry a price, an optional photo (uploaded through a crop modal, converted to WebP, stored in Supabase), an IVA treatment (iva16 / tasa0 / exento), and can be tied to a recipe for costing. Categories can be hidden, and the same photo shows in the register grid and the public menu.',
    do: [
      { action: 'Add or edit an item', steps: 'Open the item editor, set name/price/category, and save.' },
      { action: 'Add a photo', steps: 'Upload an image and crop it in the modal; it is optimized automatically.' },
      { action: 'Set the tax treatment', steps: 'Choose iva16, tasa0, or exento per item so checkout computes IVA correctly.' },
      { action: 'Hide a category', steps: 'Toggle its visibility; hidden categories drop out of the register and public menu.' },
    ],
  },
  {
    id: 'modifiers',
    group: 'admin',
    icon: 'lucide:sparkles',
    title: 'Modifiers',
    what: 'A reusable library of modifier groups (extra shot, milk choice, size…) that you attach to menu items.',
    how: 'Groups are defined once and linked to many items. A group can be hidden without breaking its links, so un-hiding restores it everywhere without re-attaching. Modifier options can adjust price and inventory deductions/substitutions.',
    do: [
      { action: 'Create a group', steps: 'Add a group, then add its options with prices and any inventory effect.' },
      { action: 'Attach to items', steps: 'Link the group to the products that should offer it.' },
      { action: 'Hide a group', steps: 'Toggle it hidden; links are preserved for when you un-hide it.' },
    ],
  },
  {
    id: 'calculator',
    group: 'admin',
    icon: 'lucide:flask-conical',
    badges: ['advanced'],
    title: 'Recipes Builder',
    what: 'Define the bill of materials (recipe) for each product so the app knows its real cost and can suggest a price.',
    how: 'A recipe lists ingredients and quantities drawn from Inventory. From live ingredient cost the COGS/Profit engine computes cost per item and, given a target margin, recommends a price. Recipes also drive COGS and wastage in Analytics.',
    do: [
      { action: 'Build a recipe', steps: 'Pick ingredients and quantities; the cost per unit updates live.' },
      { action: 'Get a suggested price', steps: 'Enter a target margin to see the recommended price.' },
      { action: 'Publish', steps: 'Attach the recipe to the menu item so its cost feeds Analytics.' },
    ],
  },
  {
    id: 'inventory',
    group: 'admin',
    icon: 'lucide:database',
    badges: ['advanced'],
    title: 'Inventory',
    what: 'Track raw stock, warehouses, and transformations (including green-to-roasted coffee), with low-stock alerts.',
    how: 'Stock is drawn down by recipes at each sale and logged to an audit trail. The Roaster records a final yield weight (what you actually got out of the drum, not a loss estimate). Per-item reorder points raise "needs reordering" alerts; unset items fall back to a default threshold.',
    do: [
      { action: 'Add or restock an item', steps: 'Create the item or record a restock quantity and cost.' },
      { action: 'Roast / transform', steps: 'Use the Roaster to turn green into finished stock by entering the final yield weight.' },
      { action: 'Set a reorder point', steps: 'Enter a per-item threshold so low-stock alerts appear when it is hit.' },
    ],
  },
  {
    id: 'vendors',
    group: 'admin',
    icon: 'lucide:store',
    badges: ['advanced'],
    title: 'Vendors & Settlement',
    what: 'For consignment shops: tag products with the vendor that owns them and run a per-vendor settlement report.',
    how: 'Vendor attribution is snapshotted onto each sale line at checkout, so historic settlements survive renames. Two split models are supported: commission % (on gross or pre-IVA) or cost-recovery (house keeps production cost, vendor takes profit). A payout ledger records money actually paid and freezes the statement, so the report shows owed − paid = balance. A Books Summary separates commission income from vendor payable and itemizes IVA.',
    do: [
      { action: 'Tag a product', steps: 'Assign a vendor to menu items in the Menu Editor or here.' },
      { action: 'Run a settlement', steps: 'Pick a vendor and period, choose the split model, and review the statement.' },
      { action: 'Record a payout', steps: 'Post a payment to the ledger; it freezes that statement and updates the balance.' },
    ],
  },
  {
    id: 'tables',
    group: 'admin',
    icon: 'lucide:armchair',
    badges: ['advanced'],
    title: 'Tables',
    what: 'Lay out your dining room on a visual floor plan and track tickets by table.',
    how: 'A floor-plan registry stores tables (number, name, seats, shape, position) as a canvas document. Tickets link to a table id (resolved by scanning, not a hard foreign key), and the register\'s Tables layout tracks open orders on the map.',
    do: [
      { action: 'Design the floor', steps: 'Add tables to the canvas and set seats, shape, and position.' },
      { action: 'Use it at the register', steps: 'Switch the layout to Tables (General Settings) to open tickets from the map.' },
    ],
  },
  {
    id: 'menus',
    group: 'admin',
    icon: 'lucide:layout-list',
    badges: ['cloud'],
    title: 'Public Menus (TinyMenu)',
    what: 'Build and publish digital menus — served at /menu with QR codes, TV/kiosk mode, and a drag-and-drop designer.',
    how: 'A shop can have multiple named menus (breakfast, lunch, seasonal) with a weekly/time-of-day schedule that auto-picks the active one. Menus can be catalog-driven templates, an uploaded PDF/PNG carousel, or a full canvas design (shapes, text, images, bound catalog items). Every save writes a version snapshot you can restore, and each menu has a shareable QR/link.',
    do: [
      { action: 'Create a menu', steps: 'Add a named menu and choose a template, upload, or canvas design.' },
      { action: 'Schedule it', steps: 'Set the weekly and time-of-day schedule so the right menu shows automatically.' },
      { action: 'Share', steps: 'Open the share card for the QR code and copy-link; TV mode lives at /menu/tv.' },
      { action: 'Restore a version', steps: 'Browse snapshots and restore any prior save.' },
    ],
  },
  {
    id: 'receipt',
    group: 'admin',
    icon: 'lucide:printer',
    title: 'Receipt Settings',
    what: 'Customize the printed/digital receipt: logo, header and footer text, tax display, and a live preview.',
    how: 'Settings are saved to your shop profile and applied to every receipt. You can show the tax breakdown, add a legal disclaimer, and include a CFDI QR that links to the invoicing portal.',
    do: [
      { action: 'Add a logo and text', steps: 'Upload a logo and set the header/subheader/footer lines.' },
      { action: 'Configure tax display', steps: 'Enable the tax line and set the rate label.' },
      { action: 'Show the CFDI QR', steps: 'Turn on the CFDI QR so customers can self-invoice; preview it on the right.' },
    ],
  },
  {
    id: 'cfdi',
    group: 'admin',
    icon: 'lucide:file-text',
    badges: ['cloud'],
    title: 'CFDI Portal',
    what: 'The self-invoicing portal (Mexican CFDI) where customers turn a ticket into a tax invoice.',
    how: 'Receipts can carry a CFDI QR that opens a public page; the customer enters their fiscal data and the sale\'s IVA (extracted per line at checkout) is used to issue the invoice. This tab manages the portal configuration.',
    do: [
      { action: 'Enable the portal', steps: 'Configure CFDI here and turn on the CFDI QR in Receipt Settings.' },
      { action: 'Help a customer invoice', steps: 'They scan the QR, enter fiscal data, and download the invoice.' },
    ],
  },
  {
    id: 'discounts',
    group: 'admin',
    icon: 'lucide:percent',
    badges: ['advanced'],
    title: 'Auto Discounts',
    what: 'Define the discount rules (percentage or flat) that cashiers can apply at the register.',
    how: 'Rules are stored centrally and offered in the register\'s discount control. Applying a discount is PIN-protected, and under strict mode it requires a manager override that is logged.',
    do: [
      { action: 'Create a rule', steps: 'Add a percentage or flat discount and give it a name.' },
      { action: 'Manage rules', steps: 'Edit or remove rules; changes apply to the register immediately.' },
    ],
  },
  {
    id: 'loyalty',
    group: 'admin',
    icon: 'lucide:star',
    badges: ['advanced'],
    title: 'Loyalty Program',
    what: 'Set up phone-number loyalty with recurring or single-use rewards.',
    how: 'Accrual is bound to sales by a database trigger, so receipt resends never double-count. Cashiers attach a customer at the register by phone number; rewards are defined here.',
    do: [
      { action: 'Create a program', steps: 'Choose recurring or single-use and set the reward rules.' },
      { action: 'Track members', steps: 'Customers accrue automatically once attached to sales at the register.' },
    ],
  },
  {
    id: 'team',
    group: 'admin',
    icon: 'lucide:users',
    badges: ['cloud'],
    title: 'Team & PINs',
    what: 'Manage cashiers, their PINs, and their roles (employee / manager / admin).',
    how: 'Adding a cashier writes a securely hashed PIN via a server RPC; removing one wipes it. Roles drive the optional access restrictions, and everyone allowed to sign in is tracked in a single allowlist.',
    do: [
      { action: 'Add a cashier', steps: 'Enter a name, set a PIN, and choose a role.' },
      { action: 'Change a role', steps: 'Use the role selector to set employee, manager, or admin.' },
      { action: 'Remove a cashier', steps: 'Delete the entry; their PIN is revoked.' },
    ],
  },
  {
    id: 'devices',
    group: 'admin',
    icon: 'lucide:tablet-smartphone',
    badges: ['cloud'],
    title: 'Devices',
    what: 'Provision new POS terminals and inspect stuck sync data without touching the Supabase dashboard.',
    how: 'Adding a device provisions it through the app (optionally with a custom sign-in email). The Pending Sync inspector (PIN required) lets you review and surgically discard queued offline data if a sync error occurs.',
    do: [
      { action: 'Add a device', steps: 'Use the device form; optionally set a custom email instead of the auto-generated one.' },
      { action: 'Fix a sync problem', steps: 'Open the Pending Sync inspector, re-enter your PIN, and review or discard queued items.' },
    ],
  },
  {
    id: 'tips',
    group: 'admin',
    icon: 'lucide:wallet',
    badges: ['advanced'],
    title: 'Tips Ledger',
    what: 'Track tips collected and paid out, kept separate from revenue.',
    how: 'Tips are treated as a custodial liability with their own ledger — collected at checkout, refundable line-aware, and reconciled in Analytics so they never inflate profit.',
    do: [
      { action: 'Review tips', steps: 'See tips collected for the period and any payouts.' },
      { action: 'Record a payout', steps: 'Log tip distributions so the ledger balances.' },
    ],
  },
  {
    id: 'activity',
    group: 'admin',
    icon: 'lucide:history',
    badges: ['advanced', 'cloud'],
    title: 'Activity Log',
    what: 'An audit trail of important events: sales, refunds, settings changes, menu edits, inventory deletions, and cortes.',
    how: 'Every logged event stores metadata — including manager-override details (who authorized a refund/void/expense/discount) when strict mode is on — so you can trace sensitive actions.',
    do: [
      { action: 'Review activity', steps: 'Scroll or filter the feed to find an event.' },
      { action: 'Audit an override', steps: 'Open a sensitive action to see who authorized it.' },
    ],
  },
  {
    id: 'settings',
    group: 'admin',
    icon: 'lucide:settings',
    title: 'General Settings',
    what: 'The control center: language, branding, layout, business type, security, hardware, and database maintenance.',
    how: 'Settings save to your shop profile (and mirror locally for instant boot/branding). Advanced Mode unlocks the deeper tabs; Layout mode and printer size are per device. The Update Schema button compares the app\'s expected database version with the server and applies idempotent SQL when an update is available.',
    do: [
      { action: 'Change the language', steps: 'Set System Language to English or Español — the whole app (and this help) follows it.' },
      { action: 'Turn on Advanced Mode', steps: 'Enable Advanced Mode to unlock Recipes, Inventory, Vendors, Tables, and more.' },
      { action: 'Set branding & layout', steps: 'Upload a logo, pick a brand color and theme, and choose the register layout.' },
      { action: 'Tighten access', steps: 'Under "Seguridad y Accesos", enable admin-panel and sensitive-action restrictions.' },
      { action: 'Update the database', steps: 'If it says "Update available", run Update Schema to apply the latest migrations.' },
    ],
  },
];

const es = [
  // ---------------------------------------------------------------- Register
  {
    id: 'register-overview',
    group: 'register',
    icon: 'lucide:shopping-cart',
    title: 'Caja registradora (Punto de venta)',
    what: 'La pantalla de ventas del día a día donde los cajeros arman tickets, agregan productos y cobran. Está optimizada para uso táctil rápido y de alto volumen, y funciona sin conexión.',
    how: 'Los tickets abiertos viven en el dispositivo (IndexedDB), así no se pierde nada si se cae la conexión; las ventas suben solas cuando la red regresa. El diseño se adapta a tu tipo de negocio — rejilla de categorías (Cafetería), flujo paso a paso (OrderFlow) o mapa de mesas (Mesas) — elegido por dispositivo en Configuración General.',
    do: [
      { action: 'Iniciar un ticket', steps: 'Toca "Nuevo" en la lista de tickets, elige una categoría y toca los productos para agregarlos.' },
      { action: 'Cambiar entre tickets abiertos', steps: 'Usa la barra de tickets (o el botón de tickets en móvil) para saltar entre órdenes.' },
      { action: 'Editar una línea', steps: 'Toca un artículo del ticket para cambiar la cantidad o quitarlo.' },
      { action: 'Cambiar el diseño', steps: 'Ve a Admin → Configuración General → Modo de diseño (es por dispositivo).' },
    ],
  },
  {
    id: 'register-ticket',
    group: 'register',
    icon: 'lucide:coffee',
    title: 'Armar un ticket y modificadores',
    what: 'Agrega productos a un ticket y personalízalos con grupos de modificadores — shots extra, cambio de leche, tamaños y otras opciones.',
    how: 'Cuando un artículo tiene grupos de modificadores se abre un modal para que elijas opciones antes de agregarlo al ticket. Los modificadores pueden descontar inventario extra (un shot extra jala más gramos) o sustituir ingredientes (cambio a leche de avena recalcula el costo). Cada artículo lleva su propio tratamiento de IVA, así que el impuesto se calcula por línea, no con una tasa fija.',
    do: [
      { action: 'Agregar un artículo personalizado', steps: 'Toca el producto; en el modal de modificadores elige las opciones y confirma.' },
      { action: 'Cambiar la cantidad', steps: 'Toca la línea del ticket y usa el editor de cantidad.' },
      { action: 'Quitar un artículo', steps: 'Abre la línea y elige quitar, o usa el control de eliminar.' },
    ],
  },
  {
    id: 'register-checkout',
    group: 'register',
    icon: 'lucide:credit-card',
    title: 'Cobro y pago',
    what: 'Cierra un ticket cobrando — efectivo, tarjeta o transferencia — con soporte para propinas, pagos divididos y líneas pagadas parcialmente.',
    how: 'El cobro separa el IVA real del total (que ya incluye impuesto) y registra el/los método(s) de pago para que Analíticas concilie tarjeta/efectivo/transferencia. Puedes dividir una cuenta en N partes, pagar líneas específicas y capturar propina, que se rastrea aparte como monto en custodia (no cuenta como ingreso).',
    do: [
      { action: 'Cobrar', steps: 'Toca "Pagar y cerrar", elige el método de pago y confirma.' },
      { action: 'Agregar propina', steps: 'En el cobro, escribe un monto de propina o elige un porcentaje antes de confirmar.' },
      { action: 'Dividir la cuenta', steps: 'Cambia a modo dividido, elige N partes o selecciona líneas específicas y liquida cada parte.' },
      { action: 'Reembolsar una venta', steps: 'Abre la venta en Admin → Historial de recibos y reembolsa el ticket completo o líneas específicas.' },
    ],
  },
  {
    id: 'register-discounts',
    group: 'register',
    icon: 'lucide:badge-percent',
    title: 'Descuentos en caja',
    what: 'Aplica un descuento manual en porcentaje o monto fijo al ticket actual.',
    how: 'Los descuentos vienen de las reglas que defines en Admin → Descuentos automáticos, y aplicarlos requiere PIN. Si "Requerir gerente para acciones sensibles" está activo, a un empleado se le pide un PIN de gerente/admin y la anulación se registra en la bitácora.',
    do: [
      { action: 'Aplicar un descuento', steps: 'Abre el control de descuento en el ticket, elige una regla (o monto) y confirma el PIN si se solicita.' },
      { action: 'Quitar un descuento', steps: 'Vuelve a abrir el control de descuento y bórralo antes del pago.' },
    ],
  },
  {
    id: 'register-expenses',
    group: 'register',
    icon: 'lucide:banknote',
    title: 'Gastos',
    what: 'Registra un gasto en efectivo — insumos, compras pequeñas, caja chica — directo desde la caja.',
    how: 'Los gastos se guardan con el turno y se restan en el conteo de efectivo y en la utilidad neta de Analíticas. Se sincronizan entre dispositivos con un local_id en la nube para no contarse doble.',
    do: [
      { action: 'Registrar un gasto', steps: 'Toca "Gasto", escribe el monto y una nota, y guarda (puede pedir PIN).' },
      { action: 'Revisar gastos', steps: 'Se reflejan en el conteo del corte y en Admin → Analíticas.' },
    ],
  },
  {
    id: 'register-corte',
    group: 'register',
    icon: 'lucide:calculator',
    title: 'Corte de caja',
    what: 'Cierra la caja: cuenta el efectivo, compáralo con lo esperado y registra el total del turno.',
    how: 'El corte suma ventas, propinas y gastos del turno y te avisa si el efectivo contado no coincide con lo esperado. Requiere PIN y queda en la bitácora. Se puede desactivar en Configuración General para negocios que no lo necesiten.',
    do: [
      { action: 'Hacer un corte', steps: 'Toca "Corte", escribe el efectivo contado, revisa la advertencia de diferencia y confirma.' },
      { action: 'Activar/desactivar el corte', steps: 'Admin → Configuración General → Activar corte.' },
    ],
  },
  {
    id: 'register-loyalty',
    group: 'register',
    icon: 'lucide:star',
    title: 'Captura de lealtad',
    what: 'Vincula un cliente a una venta por número de teléfono para que acumule recompensas.',
    how: 'Los puntos se acumulan mediante un disparador en la base de datos ligado a la inserción de la venta, así reenviar un recibo nunca cuenta doble. Los programas se configuran en Admin → Programa de lealtad.',
    do: [
      { action: 'Agregar un cliente a la venta', steps: 'Abre la captura de lealtad durante la orden, escribe el teléfono y confirma.' },
      { action: 'Configurar recompensas', steps: 'Define programas recurrentes o de un solo uso en Admin → Programa de lealtad.' },
    ],
  },
  {
    id: 'register-lock',
    group: 'register',
    icon: 'lucide:lock',
    title: 'Bloqueo, cajeros y seguridad',
    what: 'Bloquea la caja entre usuarios y cambia de cajero con PIN.',
    how: 'Cada cajero tiene un rol (empleado / gerente / admin). Dos interruptores opcionales refuerzan el acceso: "Restringir panel de administración" oculta el botón Admin a los no administradores, y "Requerir gerente para acciones sensibles" pide un PIN de gerente/admin en reembolsos, cancelaciones, gastos y descuentos manuales. Ambos vienen apagados.',
    do: [
      { action: 'Bloquear la pantalla', steps: 'Toca "Bloquear"; el siguiente usuario desbloquea con su PIN.' },
      { action: 'Cambiar de cajero', steps: 'Bloquea y luego desbloquea con el PIN de otro cajero.' },
      { action: 'Activar restricciones', steps: 'Admin → Configuración General → "Seguridad y Accesos".' },
    ],
  },
  {
    id: 'register-sync',
    group: 'register',
    icon: 'lucide:refresh-cw',
    title: 'Estado de sincronización',
    what: 'Muestra si el dispositivo está en línea y si hay ventas pendientes por subir.',
    how: 'La app es "offline-first": todo se guarda primero localmente y una cola en segundo plano sube los datos cuando regresa la conexión. La píldora de estado abre un panel con los pendientes.',
    do: [
      { action: 'Revisar la sincronización', steps: 'Toca la píldora de conexión en la barra de acciones para abrir el panel.' },
      { action: 'Inspeccionar datos atorados', steps: 'Admin → Dispositivos → inspector de sincronización pendiente (pide PIN) para revisar o descartar elementos en cola.' },
    ],
  },

  // ------------------------------------------------------------------- Admin
  {
    id: 'analytics',
    group: 'admin',
    icon: 'lucide:bar-chart-3',
    badges: ['advanced'],
    title: 'Analíticas',
    what: 'Tu panel de dinero: ingresos, utilidad neta real, más vendidos y costo de la mercancía en el periodo elegido.',
    how: 'Usa las ventas guardadas localmente (funciona sin conexión) y calcula la utilidad real restando el costo de insumos (COGS) y la merma con el motor de recetas/inventario, asignando comisiones, evitando duplicar gastos operativos y tratando las propinas como pasivo en custodia con su propia bitácora. El export a Excel cuadra 1:1 con los totales en pantalla.',
    do: [
      { action: 'Cambiar el periodo', steps: 'Usa el selector de rango arriba (o define un rango de fechas personalizado).' },
      { action: 'Leer las cifras clave', steps: 'Tarjetas de ingresos, bruto y neto; más vendidos; y ventas por método de pago.' },
      { action: 'Exportar un reporte', steps: 'Toca Descargar para generar un libro de Excel con varias hojas.' },
    ],
  },
  {
    id: 'orders',
    group: 'admin',
    icon: 'lucide:receipt',
    title: 'Historial de recibos',
    what: 'Una lista buscable de cada venta con sus artículos, totales, método de pago y estado.',
    how: 'Las ventas vienen de la nube (con la caché local como respaldo). Los reembolsos son por línea: puedes devolver líneas específicas y el registro guarda exactamente cuáles se reembolsaron, para que la liquidación por proveedor cargue la línea correcta.',
    do: [
      { action: 'Buscar una venta', steps: 'Busca o desplázate por la lista y abre un recibo para ver el detalle.' },
      { action: 'Reembolsar', steps: 'Abre una venta y reembolsa el ticket completo, líneas específicas o un monto personalizado.' },
      { action: 'Reenviar un recibo', steps: 'Abre la venta y comparte de nuevo el recibo de WhatsApp/PNG (la lealtad no se cuenta doble).' },
    ],
  },
  {
    id: 'menu',
    group: 'admin',
    icon: 'lucide:coffee',
    title: 'Editor de menú',
    what: 'Crea y administra el catálogo: productos, precios, categorías, fotos y el tratamiento de impuesto de cada artículo.',
    how: 'Los artículos llevan precio, una foto opcional (subida por un modal de recorte, convertida a WebP y guardada en Supabase), un tratamiento de IVA (iva16 / tasa0 / exento) y pueden ligarse a una receta para costeo. Las categorías se pueden ocultar, y la misma foto aparece en la rejilla de la caja y en el menú público.',
    do: [
      { action: 'Agregar o editar un artículo', steps: 'Abre el editor, define nombre/precio/categoría y guarda.' },
      { action: 'Agregar una foto', steps: 'Sube una imagen y recórtala en el modal; se optimiza automáticamente.' },
      { action: 'Definir el impuesto', steps: 'Elige iva16, tasa0 o exento por artículo para que el cobro calcule bien el IVA.' },
      { action: 'Ocultar una categoría', steps: 'Cambia su visibilidad; las categorías ocultas salen de la caja y del menú público.' },
    ],
  },
  {
    id: 'modifiers',
    group: 'admin',
    icon: 'lucide:sparkles',
    title: 'Modificadores',
    what: 'Una biblioteca reutilizable de grupos de modificadores (shot extra, tipo de leche, tamaño…) que adjuntas a los artículos.',
    how: 'Los grupos se definen una vez y se ligan a muchos artículos. Un grupo se puede ocultar sin romper sus vínculos, así al mostrarlo de nuevo se restaura en todos lados sin volver a adjuntarlo. Las opciones pueden ajustar el precio y los descuentos/sustituciones de inventario.',
    do: [
      { action: 'Crear un grupo', steps: 'Agrega un grupo y luego sus opciones con precios y efecto en inventario.' },
      { action: 'Adjuntar a artículos', steps: 'Liga el grupo a los productos que deban ofrecerlo.' },
      { action: 'Ocultar un grupo', steps: 'Márcalo como oculto; los vínculos se conservan para cuando lo muestres.' },
    ],
  },
  {
    id: 'calculator',
    group: 'admin',
    icon: 'lucide:flask-conical',
    badges: ['advanced'],
    title: 'Constructor de recetas',
    what: 'Define la lista de materiales (receta) de cada producto para que la app conozca su costo real y sugiera un precio.',
    how: 'Una receta lista ingredientes y cantidades tomados de Inventario. Con el costo vivo de los ingredientes, el motor de COGS/utilidad calcula el costo por artículo y, dado un margen objetivo, recomienda un precio. Las recetas también alimentan el COGS y la merma en Analíticas.',
    do: [
      { action: 'Armar una receta', steps: 'Elige ingredientes y cantidades; el costo por unidad se actualiza en vivo.' },
      { action: 'Obtener un precio sugerido', steps: 'Escribe un margen objetivo para ver el precio recomendado.' },
      { action: 'Publicar', steps: 'Adjunta la receta al artículo del menú para que su costo alimente Analíticas.' },
    ],
  },
  {
    id: 'inventory',
    group: 'admin',
    icon: 'lucide:database',
    badges: ['advanced'],
    title: 'Inventario',
    what: 'Controla stock de materia prima, almacenes y transformaciones (incluido tostado de café verde a tostado), con alertas de bajo stock.',
    how: 'El stock se descuenta con las recetas en cada venta y se registra en una bitácora. El Tostador registra el peso final obtenido (lo que de verdad salió del tambor, no una estimación de pérdida). Los puntos de reorden por artículo generan alertas de "requiere resurtido"; los artículos sin definir usan un umbral por defecto.',
    do: [
      { action: 'Agregar o resurtir un artículo', steps: 'Crea el artículo o registra una cantidad de resurtido y su costo.' },
      { action: 'Tostar / transformar', steps: 'Usa el Tostador para convertir verde en producto terminado ingresando el peso final obtenido.' },
      { action: 'Definir un punto de reorden', steps: 'Escribe un umbral por artículo para que aparezcan alertas de bajo stock.' },
    ],
  },
  {
    id: 'vendors',
    group: 'admin',
    icon: 'lucide:store',
    badges: ['advanced'],
    title: 'Proveedores y liquidación',
    what: 'Para negocios de consignación: etiqueta productos con el proveedor dueño y genera un reporte de liquidación por proveedor.',
    how: 'La atribución de proveedor se congela en cada línea de venta al cobrar, así las liquidaciones históricas sobreviven a los cambios de nombre. Hay dos modelos: comisión % (sobre bruto o pre-IVA) o recuperación de costo (la casa se queda el costo de producción y el proveedor la utilidad). Una bitácora de pagos registra lo pagado y congela el estado, así el reporte muestra adeudado − pagado = saldo. Un Resumen contable separa el ingreso por comisión del pasivo por pagar al proveedor y desglosa el IVA.',
    do: [
      { action: 'Etiquetar un producto', steps: 'Asigna un proveedor a los artículos en el Editor de menú o aquí.' },
      { action: 'Generar una liquidación', steps: 'Elige proveedor y periodo, escoge el modelo de reparto y revisa el estado.' },
      { action: 'Registrar un pago', steps: 'Registra un pago en la bitácora; congela ese estado y actualiza el saldo.' },
    ],
  },
  {
    id: 'tables',
    group: 'admin',
    icon: 'lucide:armchair',
    badges: ['advanced'],
    title: 'Mesas',
    what: 'Distribuye tu salón en un plano visual y rastrea tickets por mesa.',
    how: 'Un registro de plano guarda las mesas (número, nombre, lugares, forma, posición) como documento de lienzo. Los tickets se ligan a un id de mesa (resuelto por escaneo, no una llave foránea rígida) y el diseño de Mesas en la caja rastrea las órdenes abiertas en el mapa.',
    do: [
      { action: 'Diseñar el salón', steps: 'Agrega mesas al lienzo y define lugares, forma y posición.' },
      { action: 'Usarlo en la caja', steps: 'Cambia el diseño a Mesas (Configuración General) para abrir tickets desde el mapa.' },
    ],
  },
  {
    id: 'menus',
    group: 'admin',
    icon: 'lucide:layout-list',
    badges: ['cloud'],
    title: 'Menús públicos (TinyMenu)',
    what: 'Crea y publica menús digitales — servidos en /menu con códigos QR, modo TV/kiosco y un diseñador de arrastrar y soltar.',
    how: 'Un negocio puede tener varios menús con nombre (desayuno, comida, temporada) con un horario semanal/por hora que elige el activo automáticamente. Los menús pueden ser plantillas basadas en el catálogo, un carrusel de PDF/PNG subido, o un diseño completo en lienzo (formas, texto, imágenes, artículos ligados al catálogo). Cada guardado crea una versión que puedes restaurar, y cada menú tiene un QR/enlace para compartir.',
    do: [
      { action: 'Crear un menú', steps: 'Agrega un menú con nombre y elige plantilla, subida o diseño en lienzo.' },
      { action: 'Programarlo', steps: 'Define el horario semanal y por hora para que el menú correcto aparezca solo.' },
      { action: 'Compartir', steps: 'Abre la tarjeta para el QR y copiar enlace; el modo TV vive en /menu/tv.' },
      { action: 'Restaurar una versión', steps: 'Explora los respaldos y restaura cualquier guardado anterior.' },
    ],
  },
  {
    id: 'receipt',
    group: 'admin',
    icon: 'lucide:printer',
    title: 'Configuración de recibo',
    what: 'Personaliza el recibo impreso/digital: logo, texto de encabezado y pie, despliegue de impuesto y una vista previa en vivo.',
    how: 'La configuración se guarda en el perfil de tu negocio y se aplica a cada recibo. Puedes mostrar el desglose de impuesto, agregar un aviso legal e incluir un QR de CFDI que enlaza al portal de facturación.',
    do: [
      { action: 'Agregar logo y texto', steps: 'Sube un logo y define las líneas de encabezado/subencabezado/pie.' },
      { action: 'Configurar el impuesto', steps: 'Activa la línea de impuesto y define la etiqueta de la tasa.' },
      { action: 'Mostrar el QR de CFDI', steps: 'Activa el QR de CFDI para que los clientes se autofacturen; míralo en la vista previa.' },
    ],
  },
  {
    id: 'cfdi',
    group: 'admin',
    icon: 'lucide:file-text',
    badges: ['cloud'],
    title: 'Portal CFDI',
    what: 'El portal de autofacturación (CFDI mexicano) donde los clientes convierten un ticket en factura.',
    how: 'Los recibos pueden llevar un QR de CFDI que abre una página pública; el cliente ingresa sus datos fiscales y se usa el IVA de la venta (extraído por línea al cobrar) para emitir la factura. Esta pestaña gestiona la configuración del portal.',
    do: [
      { action: 'Activar el portal', steps: 'Configura el CFDI aquí y activa el QR de CFDI en Configuración de recibo.' },
      { action: 'Ayudar a facturar', steps: 'El cliente escanea el QR, ingresa sus datos fiscales y descarga la factura.' },
    ],
  },
  {
    id: 'discounts',
    group: 'admin',
    icon: 'lucide:percent',
    badges: ['advanced'],
    title: 'Descuentos automáticos',
    what: 'Define las reglas de descuento (porcentaje o monto fijo) que los cajeros pueden aplicar en la caja.',
    how: 'Las reglas se guardan de forma central y se ofrecen en el control de descuento de la caja. Aplicar un descuento requiere PIN y, en modo estricto, requiere una anulación de gerente que queda registrada.',
    do: [
      { action: 'Crear una regla', steps: 'Agrega un descuento en porcentaje o fijo y ponle nombre.' },
      { action: 'Administrar reglas', steps: 'Edita o elimina reglas; los cambios aplican en la caja de inmediato.' },
    ],
  },
  {
    id: 'loyalty',
    group: 'admin',
    icon: 'lucide:star',
    badges: ['advanced'],
    title: 'Programa de lealtad',
    what: 'Configura lealtad por número de teléfono con recompensas recurrentes o de un solo uso.',
    how: 'La acumulación se liga a las ventas por un disparador de base de datos, así reenviar recibos nunca cuenta doble. Los cajeros vinculan un cliente en la caja por teléfono; las recompensas se definen aquí.',
    do: [
      { action: 'Crear un programa', steps: 'Elige recurrente o de un solo uso y define las reglas de recompensa.' },
      { action: 'Seguir a los miembros', steps: 'Los clientes acumulan automáticamente al vincularlos a las ventas en la caja.' },
    ],
  },
  {
    id: 'team',
    group: 'admin',
    icon: 'lucide:users',
    badges: ['cloud'],
    title: 'Equipo y PINs',
    what: 'Administra cajeros, sus PINs y sus roles (empleado / gerente / admin).',
    how: 'Agregar un cajero guarda un PIN cifrado de forma segura mediante un RPC del servidor; eliminarlo lo borra. Los roles rigen las restricciones de acceso opcionales, y todos los que pueden iniciar sesión se controlan en una sola lista de permitidos.',
    do: [
      { action: 'Agregar un cajero', steps: 'Escribe un nombre, define un PIN y elige un rol.' },
      { action: 'Cambiar un rol', steps: 'Usa el selector de rol para asignar empleado, gerente o admin.' },
      { action: 'Eliminar un cajero', steps: 'Borra el registro; su PIN se revoca.' },
    ],
  },
  {
    id: 'devices',
    group: 'admin',
    icon: 'lucide:tablet-smartphone',
    badges: ['cloud'],
    title: 'Dispositivos',
    what: 'Aprovisiona nuevas terminales POS e inspecciona datos de sincronización atorados sin entrar al panel de Supabase.',
    how: 'Agregar un dispositivo lo aprovisiona desde la app (opcionalmente con un correo de inicio de sesión personalizado). El inspector de sincronización pendiente (pide PIN) te deja revisar y descartar quirúrgicamente datos en cola si ocurre un error.',
    do: [
      { action: 'Agregar un dispositivo', steps: 'Usa el formulario; opcionalmente define un correo personalizado en vez del automático.' },
      { action: 'Arreglar un problema de sync', steps: 'Abre el inspector de sincronización pendiente, reingresa tu PIN y revisa o descarta elementos.' },
    ],
  },
  {
    id: 'tips',
    group: 'admin',
    icon: 'lucide:wallet',
    badges: ['advanced'],
    title: 'Bitácora de propinas',
    what: 'Controla las propinas cobradas y pagadas, separadas del ingreso.',
    how: 'Las propinas se tratan como pasivo en custodia con su propia bitácora — cobradas al pagar, reembolsables por línea y conciliadas en Analíticas para que nunca inflen la utilidad.',
    do: [
      { action: 'Revisar propinas', steps: 'Consulta las propinas cobradas del periodo y cualquier pago.' },
      { action: 'Registrar un pago', steps: 'Registra la distribución de propinas para que la bitácora cuadre.' },
    ],
  },
  {
    id: 'activity',
    group: 'admin',
    icon: 'lucide:history',
    badges: ['advanced', 'cloud'],
    title: 'Bitácora de actividad',
    what: 'Un registro de auditoría de eventos importantes: ventas, reembolsos, cambios de configuración, ediciones de menú, borrados de inventario y cortes.',
    how: 'Cada evento registrado guarda metadatos — incluidos los detalles de anulación de gerente (quién autorizó un reembolso/cancelación/gasto/descuento) cuando el modo estricto está activo — para rastrear acciones sensibles.',
    do: [
      { action: 'Revisar la actividad', steps: 'Desplázate o filtra el feed para encontrar un evento.' },
      { action: 'Auditar una anulación', steps: 'Abre una acción sensible para ver quién la autorizó.' },
    ],
  },
  {
    id: 'settings',
    group: 'admin',
    icon: 'lucide:settings',
    title: 'Configuración general',
    what: 'El centro de control: idioma, marca, diseño, tipo de negocio, seguridad, hardware y mantenimiento de la base de datos.',
    how: 'La configuración se guarda en el perfil del negocio (y se refleja localmente para un arranque/marca instantáneos). El Modo Avanzado desbloquea las pestañas más profundas; el modo de diseño y el tamaño de impresora son por dispositivo. El botón Actualizar esquema compara la versión de base de datos que espera la app con la del servidor y aplica SQL idempotente cuando hay actualización.',
    do: [
      { action: 'Cambiar el idioma', steps: 'Define el Idioma del Sistema en Inglés o Español — toda la app (y esta ayuda) lo sigue.' },
      { action: 'Activar el Modo Avanzado', steps: 'Actívalo para desbloquear Recetas, Inventario, Proveedores, Mesas y más.' },
      { action: 'Definir marca y diseño', steps: 'Sube un logo, elige color de marca y tema, y escoge el diseño de la caja.' },
      { action: 'Reforzar el acceso', steps: 'En "Seguridad y Accesos", activa las restricciones de panel y de acciones sensibles.' },
      { action: 'Actualizar la base de datos', steps: 'Si dice "Actualización disponible", ejecuta Actualizar esquema para aplicar las últimas migraciones.' },
    ],
  },
];

export const helpContent = { en, es };

// Group headings (rendered by HelpTab). Kept here so both languages stay together.
export const helpGroupLabels = {
  en: { register: 'Register', admin: 'Admin dashboard' },
  es: { register: 'Caja', admin: 'Panel de administración' },
};
