import postgres from 'postgres';

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method Not Allowed' });

  const { connectionString } = req.body;

  if (!connectionString || !connectionString.includes('postgresql://')) {
    return res.status(400).json({ error: 'Invalid PostgreSQL connection string.' });
  }

  // Connect to the user's provided database
  const sql = postgres(connectionString, { ssl: 'require' });

  // 1. Put the entire SQL dump directly into a string variable!
  const schemaQuery = `
    CREATE TABLE IF NOT EXISTS public.active_tickets (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text,
      items jsonb,
      cashier_id bigint,
      created_at timestamp with time zone DEFAULT now(),
      sentToBarista boolean,
      discount jsonb,
      savedSplitPayments jsonb,
      savedPaidProductIds jsonb,
      savedSplitMode text,
      savedNWays bigint,
      last_modified_by text
    );

    CREATE TABLE IF NOT EXISTS public.customers (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      phone character varying NOT NULL,
      visits bigint NOT NULL DEFAULT 0,
      created_at timestamp with time zone DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS public.expenses (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      amount numeric NOT NULL, 
      reason text,
      category text DEFAULT 'General',
      cashier_name text,
      created_at timestamp with time zone DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS public.inventory (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text NOT NULL UNIQUE,
      current_stock numeric DEFAULT 0,
      unit text,
      created_at timestamp with time zone DEFAULT now(),
      unit_cost numeric DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS public.inventory_logs (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      item_name text NOT NULL,
      qty_deducted numeric NOT NULL,
      deduction_type text NOT NULL,
      ticket_id text,
      created_at timestamp with time zone DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS public.activity_logs (
      id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
      created_at timestamp with time zone DEFAULT now(),
      cashier_name text,
      action_type text,
      description text,
      metadata jsonb
    );

    CREATE TABLE IF NOT EXISTS public.recipes (
      id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
      name text NOT NULL,
      linked_menu_item text,
      target_margin numeric DEFAULT 25.0,
      custom_price numeric,
      ingredients jsonb NOT NULL DEFAULT '[]'::jsonb,
      created_at timestamp with time zone DEFAULT now(),
      updated_at timestamp with time zone DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS public.sales (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at timestamp with time zone NOT NULL DEFAULT now(),
      total_amount numeric,
      payment_method text,
      items_sold jsonb,
      cashier_name text,
      status text DEFAULT 'paid',
      order_name text,
      refund_amount numeric DEFAULT 0,
      tip_amount numeric DEFAULT 0,
      splits jsonb
    );

    CREATE TABLE IF NOT EXISTS public.shop_settings (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at timestamp with time zone NOT NULL DEFAULT now(),
      menu_data jsonb
    );

    -- Robust Migration: Add 'category' to 'expenses' if it doesn't exist
    DO $$ 
    BEGIN 
      IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='expenses' AND column_name='category') THEN
        ALTER TABLE public.expenses ADD COLUMN category text DEFAULT 'General';
      END IF;
    END $$;

    -- SEED THE DATABASE
    INSERT INTO public.shop_settings (id, menu_data)
    VALUES (
      1, 
      '{"categories": {"Café": []}, "cashiers": [{"id": 1, "name": "Admin", "pin": "1234", "isAdmin": true}], "posSettings": {"name": "TinyPOS", "language": "en", "brandColor": "#f28b05", "isDarkMode": false, "autoLockMinutes": 5, "enableCorte": true, "ticketVisibility": "open"}, "receiptSettings": {"header": "TINY COFFEE BAR", "subheader": "Puebla, Mexico", "footer": "Thank you for your visit!", "logo": null, "enableTaxBreakdown": false, "taxRate": 16}, "loyaltySettings": {"isActive": false, "visitsRequired": 10, "rewardDescription": "tu próxima bebida GRATIS"}, "modifierGroups": {}, "discountRules": []}'::jsonb
    )
    ON CONFLICT (id) DO NOTHING;

    -- ==========================================
    -- ROW LEVEL SECURITY (RLS) & POLICIES
    -- ==========================================

    -- 1. Enable RLS on every table
    ALTER TABLE public.active_tickets ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.inventory_logs ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.shop_settings ENABLE ROW LEVEL SECURITY;

    -- 2. Create Policies for POS Hardware (Drop first to avoid 500 errors on re-run)
    DROP POLICY IF EXISTS "Hardware can access active_tickets" ON public.active_tickets;
    DROP POLICY IF EXISTS "Hardware can access customers" ON public.customers;
    DROP POLICY IF EXISTS "Hardware can access expenses" ON public.expenses;
    DROP POLICY IF EXISTS "Hardware can access inventory" ON public.inventory;
    DROP POLICY IF EXISTS "Hardware can access inventory_logs" ON public.inventory_logs;
    DROP POLICY IF EXISTS "Hardware can access activity_logs" ON public.activity_logs;
    DROP POLICY IF EXISTS "Hardware can access recipes" ON public.recipes;
    DROP POLICY IF EXISTS "Hardware can access sales" ON public.sales;
    DROP POLICY IF EXISTS "Hardware can access shop_settings" ON public.shop_settings;

    CREATE POLICY "Hardware can access active_tickets" ON public.active_tickets FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access customers" ON public.customers FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access expenses" ON public.expenses FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access inventory" ON public.inventory FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access inventory_logs" ON public.inventory_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access activity_logs" ON public.activity_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access recipes" ON public.recipes FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access sales" ON public.sales FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access shop_settings" ON public.shop_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
  `;

  try {
    // 2. Execute the string directly
    await sql.unsafe(schemaQuery);
    await sql.end();

    res.status(200).json({ success: true, message: 'Database structures created successfully!' });
  } catch (error) {
    await sql.end();
    console.error("Installation Error:", error);
    res.status(500).json({ success: false, error: error.message });
  }
}