// The 0.x → latest migration runs the full schema script against a live DB
// (all migrations + backfills). On Vercel's default ~10s budget this can time
// out, and the platform returns a non-JSON 500 the client can't parse. Bump the
// budget so the function can finish and return its own JSON. >10s needs Vercel Pro.
//
// To stay under the free-tier cap for the common case, an existing install
// sends its fromVersion; we then run ONLY the delta SQL (see _schemaDeltas.js)
// instead of the whole schema. The full script below is kept as the first-
// install / big-jump / unknown-version fallback.
import { deltasFrom } from './_schemaDeltas.js';

export const config = { maxDuration: 60 };

export default async function handler(req, res) {
  // 1. Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  // 2. We now expect the Management token and the Project Ref.
  //    fromVersion is optional — when present and recognized we apply only the
  //    delta; when absent/unknown we run the full schema.
  //
  //    The token comes from the HttpOnly `tinypos_mgmt_token` cookie set by
  //    /api/auth/callback (kept out of the URL and out of JS). We still accept
  //    it in the body as a fallback for any transitional caller.
  const { projectRef, fromVersion } = req.body;
  const cookie = req.headers.cookie || '';
  const cookieMatch = cookie.match(/(?:^|;\s*)tinypos_mgmt_token=([^;]+)/);
  const accessToken = cookieMatch ? decodeURIComponent(cookieMatch[1]) : req.body.accessToken;

  if (!accessToken || !projectRef) {
    return res.status(400).json({ error: 'Missing accessToken or projectRef. Please provide both.' });
  }

  // 3. YOUR EXACT SQL REMAINS UNTOUCHED
  const schemaQuery = `
    -- ==========================================
    -- EXTENSIONS
    -- ==========================================
    CREATE EXTENSION IF NOT EXISTS pgcrypto;

    -- ==========================================
    -- TABLES
    -- ==========================================

    CREATE TABLE IF NOT EXISTS public.active_tickets (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text,
      items jsonb,
      cashier_id bigint,
      created_at timestamp with time zone DEFAULT now(),
      discount jsonb,
      savedSplitPayments jsonb,
      savedPaidProductIds jsonb,
      savedSplitMode text,
      savedNWays bigint,
      last_modified_by text,
      loyalty_phone text,
      loyalty_stars_pending integer DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS public.customers (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      phone character varying NOT NULL UNIQUE,
      visits bigint NOT NULL DEFAULT 0,
      created_at timestamp with time zone DEFAULT now(),
      completed_at timestamp with time zone
    );

    CREATE TABLE IF NOT EXISTS public.expenses (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      amount numeric NOT NULL,
      reason text,
      category text DEFAULT 'General',
      payment_source text NOT NULL DEFAULT 'caja',
      cashier_name text,
      local_id uuid UNIQUE,
      created_at timestamp with time zone DEFAULT now()
    );
    -- Existing installs: the pocket an expense was paid from (caja/banco/dueno).
    -- Only 'caja' (petty cash) reduces the cash drawer Corte. See migration 028.
    ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS payment_source text NOT NULL DEFAULT 'caja';

    CREATE TABLE IF NOT EXISTS public.inventory (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text NOT NULL UNIQUE,
      current_stock numeric DEFAULT 0,
      unit text,
      created_at timestamp with time zone DEFAULT now(),
      unit_cost numeric DEFAULT 0,
      reorder_point numeric NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS public.inventory_logs (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      item_name text NOT NULL,
      qty_deducted numeric NOT NULL,
      deduction_type text NOT NULL,
      ticket_id text,
      unit_cost numeric DEFAULT 0,
      local_id uuid UNIQUE,
      created_at timestamp with time zone DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS public.activity_logs (
      id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
      created_at timestamp with time zone DEFAULT now(),
      cashier_name text,
      action_type text,
      description text,
      metadata jsonb
    );

    CREATE TABLE IF NOT EXISTS public.recipes (
      id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
      name text NOT NULL,
      linked_menu_item text,
      target_margin numeric DEFAULT 25.0,
      custom_price numeric,
      ingredients jsonb NOT NULL DEFAULT '[]'::jsonb,
      created_at timestamp with time zone DEFAULT now(),
      updated_at timestamp with time zone DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS public.sales (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at timestamp with time zone NOT NULL DEFAULT now(),
      total_amount numeric,
      tax_amount numeric DEFAULT 0,
      taxable_amount numeric DEFAULT 0,
      payment_method text,
      items_sold jsonb,
      cashier_name text,
      status text DEFAULT 'paid',
      order_name text,
      refund_amount numeric DEFAULT 0,
      tip_amount numeric DEFAULT 0,
      tip_refunded numeric DEFAULT 0,
      splits jsonb,
      items jsonb,
      discount jsonb,
      local_id uuid UNIQUE,
      ticket_id text,
      loyalty_phone text,
      loyalty_stars_awarded integer DEFAULT 0,
      loyalty_stars_redeemed integer DEFAULT 0,
      loyalty_program_type text,
      refunded_items jsonb
    );

    CREATE TABLE IF NOT EXISTS public.shop_settings (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at timestamp with time zone NOT NULL DEFAULT now(),
      menu_data jsonb
    );

    -- Secure PIN Storage (hashed via pgcrypto)
    CREATE TABLE IF NOT EXISTS public.cashier_pins (
      cashier_id bigint PRIMARY KEY,
      pin_hash text NOT NULL,
      created_at timestamp with time zone DEFAULT now()
    );

    -- ==========================================
    -- REFUND SAFETY CONSTRAINT
    -- ==========================================
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'refund_limit_check' AND table_name = 'sales'
      ) THEN
        ALTER TABLE public.sales ADD CONSTRAINT refund_limit_check CHECK (refund_amount <= total_amount);
      END IF;
    END $$;

    -- ==========================================
    -- ANALYTICS: backfill ticket_id on legacy sale logs so COGS attribution
    -- works for installs that predate ticket_id (migration 009). Only fills
    -- unambiguous matches; colliding timestamps stay NULL to avoid
    -- misattribution.
    -- ==========================================
    WITH log_matches AS (
      SELECT
        il.id AS log_id,
        (SELECT s.ticket_id
           FROM public.sales s
          WHERE s.created_at = il.created_at
            AND s.ticket_id IS NOT NULL
            AND s.ticket_id <> ''
          LIMIT 1) AS resolved_ticket_id,
        (SELECT COUNT(*)
           FROM public.sales s
          WHERE s.created_at = il.created_at
            AND s.ticket_id IS NOT NULL
            AND s.ticket_id <> '') AS match_count
      FROM public.inventory_logs il
      WHERE il.deduction_type = 'sale'
        AND (il.ticket_id IS NULL OR il.ticket_id = '')
    )
    UPDATE public.inventory_logs il
    SET ticket_id = lm.resolved_ticket_id
    FROM log_matches lm
    WHERE il.id = lm.log_id
      AND lm.match_count = 1;

    -- ==========================================
    -- TIPS LIABILITY: schema upgrade for existing installs + new ledger tables
    -- ==========================================
    ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS tip_refunded numeric DEFAULT 0;

    -- Per-line refund attribution: { "<lineIndex>": { qty, amountCents } }.
    -- Lets vendor settlement charge a refund to the exact product (and thus the
    -- exact vendor) returned, instead of spreading it proportionally. Null/absent
    -- means a legacy scalar refund — settlement falls back to proportional.
    ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS refunded_items jsonb;

    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'tip_refund_limit_check' AND table_name = 'sales'
      ) THEN
        ALTER TABLE public.sales ADD CONSTRAINT tip_refund_limit_check CHECK (tip_refunded <= tip_amount);
      END IF;
    END $$;

    -- Records each disbursement of pooled tips to staff. The liability
    -- (SUM(tip_amount - tip_refunded) on sales) decreases by SUM(amount) on
    -- tip_payouts. The shop should periodically pay this out to zero.
    CREATE TABLE IF NOT EXISTS public.tip_payouts (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      amount numeric NOT NULL CHECK (amount > 0),
      method text DEFAULT 'cash',
      recipient text,
      note text,
      cashier_name text,
      local_id uuid UNIQUE,
      created_at timestamp with time zone DEFAULT now()
    );

    -- Immutable audit ledger for every tip movement. INSERT-only; never updated.
    -- event_type: 'accrual' (sale tip), 'refund' (tip refunded to customer),
    --             'payout' (paid to staff), 'adjustment' (manual correction).
    -- delta_cents is signed: + increases liability (accrual), - decreases (refund/payout).
    CREATE TABLE IF NOT EXISTS public.tip_events (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      event_type text NOT NULL CHECK (event_type IN ('accrual','refund','payout','adjustment')),
      delta_cents numeric NOT NULL,
      sale_local_id uuid,
      payout_local_id uuid,
      reason text,
      actor text,
      local_id uuid UNIQUE,
      created_at timestamp with time zone DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_tip_events_created ON public.tip_events (created_at);
    CREATE INDEX IF NOT EXISTS idx_tip_events_type ON public.tip_events (event_type);

    ALTER TABLE public.tip_payouts ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.tip_events ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Hardware can access tip_payouts" ON public.tip_payouts;
    DROP POLICY IF EXISTS "Hardware can access tip_events" ON public.tip_events;
    CREATE POLICY "Hardware can access tip_payouts" ON public.tip_payouts FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access tip_events" ON public.tip_events FOR ALL TO authenticated USING (true) WITH CHECK (true);

    -- ==========================================
    -- SEED INITIAL SETTINGS
    -- ==========================================
    -- This path is the "Update Schema" repair for EXISTING stores, so the insert
    -- is a no-op for them (ON CONFLICT DO NOTHING). We intentionally seed NO
    -- cashiers and NO default PIN — the admin PIN is set by the owner during
    -- onboarding (SetupScreen), never hardcoded here.
    INSERT INTO public.shop_settings (id, menu_data)
    VALUES (
      1,
      '{"categories": {"Café": []}, "cashiers": [], "posSettings": {"name": "TinyPOS", "language": "en", "brandColor": "#f28b05", "isDarkMode": false, "autoLockMinutes": 5, "enableCorte": true, "ticketVisibility": "open", "pinCode": "", "strictAdminAccess": false, "strictRegisterOverrides": false}, "receiptSettings": {"header": "", "subheader": "", "footer": "", "logo": null, "enableTaxBreakdown": false, "taxRate": 16}, "loyaltySettings": {"isActive": false, "visitsRequired": 10, "rewardDescription": "tu próxima bebida GRATIS"}, "modifierGroups": {}, "discountRules": []}'::jsonb
    )
    ON CONFLICT (id) DO NOTHING;

    -- ==========================================
    -- ROW LEVEL SECURITY (RLS) & POLICIES
    -- ==========================================

    -- 1. Enable RLS on every table
    ALTER TABLE public.active_tickets ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.inventory_logs ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.shop_settings ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.cashier_pins ENABLE ROW LEVEL SECURITY;

    -- 2. Create Policies for POS Hardware (Drop first to avoid 500 errors on re-run)
    DROP POLICY IF EXISTS "Hardware can access active_tickets" ON public.active_tickets;
    DROP POLICY IF EXISTS "Hardware can access customers" ON public.customers;
    DROP POLICY IF EXISTS "Hardware can access expenses" ON public.expenses;
    DROP POLICY IF EXISTS "Hardware can access inventory" ON public.inventory;
    DROP POLICY IF EXISTS "Hardware can access inventory_logs" ON public.inventory_logs;
    DROP POLICY IF EXISTS "Hardware can access activity_logs" ON public.activity_logs;
    DROP POLICY IF EXISTS "Hardware can access recipes" ON public.recipes;
    DROP POLICY IF EXISTS "Hardware can access sales" ON public.sales;
    DROP POLICY IF EXISTS "Hardware can access shop_settings" ON public.shop_settings;
    DROP POLICY IF EXISTS "Hardware can access cashier_pins" ON public.cashier_pins;

    CREATE POLICY "Hardware can access active_tickets" ON public.active_tickets FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access customers" ON public.customers FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access expenses" ON public.expenses FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access inventory" ON public.inventory FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access inventory_logs" ON public.inventory_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access activity_logs" ON public.activity_logs FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access recipes" ON public.recipes FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access sales" ON public.sales FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access shop_settings" ON public.shop_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access cashier_pins" ON public.cashier_pins FOR ALL TO authenticated USING (true) WITH CHECK (true);

    -- ==========================================
    -- RPC FUNCTIONS
    -- ==========================================

    -- Secure PIN verification (compares against bcrypt hash)
    CREATE OR REPLACE FUNCTION verify_pin(p_cashier_id BIGINT, p_pin TEXT)
    RETURNS BOOLEAN AS $$
    DECLARE
        v_hash TEXT;
    BEGIN
        SELECT pin_hash INTO v_hash FROM public.cashier_pins WHERE cashier_id = p_cashier_id;
        IF v_hash IS NULL THEN RETURN FALSE; END IF;
        RETURN v_hash = crypt(p_pin, v_hash);
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;

    -- Upsert a cashier's bcrypt-hashed PIN. Called from Admin.jsx whenever a
    -- cashier is created or their PIN is rotated. SECURITY DEFINER so the
    -- function owns the hashing (the raw PIN never lingers anywhere outside
    -- this transaction, and clients don't need permission to write the table
    -- directly).
    -- search_path includes 'extensions' so pgcrypto's crypt() and gen_salt()
    -- resolve. Modern Supabase installs pgcrypto into the extensions schema,
    -- not public, and SECURITY DEFINER with a pinned path otherwise hides them.
    CREATE OR REPLACE FUNCTION public.set_cashier_pin(p_cashier_id BIGINT, p_pin TEXT)
    RETURNS VOID
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = public, extensions
    AS $$
    BEGIN
      IF p_pin IS NULL OR length(p_pin) = 0 THEN
        RAISE EXCEPTION 'PIN cannot be empty';
      END IF;
      INSERT INTO public.cashier_pins (cashier_id, pin_hash)
      VALUES (p_cashier_id, crypt(p_pin, gen_salt('bf')))
      ON CONFLICT (cashier_id) DO UPDATE SET pin_hash = EXCLUDED.pin_hash;
    END;
    $$;

    -- Delete a cashier's stored PIN hash. Pair with cashier removal so we
    -- don't leak hashes for users who no longer exist.
    CREATE OR REPLACE FUNCTION public.delete_cashier_pin(p_cashier_id BIGINT)
    RETURNS VOID
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = public, extensions
    AS $$
    BEGIN
      DELETE FROM public.cashier_pins WHERE cashier_id = p_cashier_id;
    END;
    $$;

    -- One-time backfill: every cashier in menu_data.cashiers that has a
    -- plaintext 'pin' but no row in cashier_pins gets one now. Idempotent —
    -- existing hashes are left alone (ON CONFLICT DO NOTHING). This patches
    -- installs where cashiers were added through Admin before set_cashier_pin
    -- existed.
    INSERT INTO public.cashier_pins (cashier_id, pin_hash)
    SELECT (c->>'id')::bigint, crypt(c->>'pin', gen_salt('bf'))
    FROM public.shop_settings ss,
         jsonb_array_elements(ss.menu_data->'cashiers') c
    WHERE ss.id = 1
      AND c->>'pin' IS NOT NULL
      AND c->>'id' IS NOT NULL
      AND NOT EXISTS (
        SELECT 1 FROM public.cashier_pins cp WHERE cp.cashier_id = (c->>'id')::bigint
      )
    ON CONFLICT (cashier_id) DO NOTHING;

    -- ==========================================
    -- MENU SPLIT: dedicated tables for categories, items, modifier groups,
    -- modifier options, item↔group links, and discount rules. Replaces the
    -- jsonb blobs that used to live under shop_settings.menu_data.
    -- Backfill at the bottom of this block copies existing menu_data into the
    -- new tables on first run; re-runs are no-ops (guarded by NOT EXISTS).
    -- After backfill the migrated keys are stripped from menu_data so there
    -- is one source of truth. The remaining keys (cashiers, posSettings,
    -- receiptSettings, loyaltySettings) stay on shop_settings.menu_data.
    -- ==========================================
    CREATE TABLE IF NOT EXISTS public.menu_categories (
      id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name        text NOT NULL UNIQUE,
      sort_order  int  NOT NULL DEFAULT 0,
      is_hidden   bool NOT NULL DEFAULT false,
      created_at  timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS public.menu_items (
      id               text PRIMARY KEY,
      category_id      bigint NOT NULL REFERENCES public.menu_categories(id) ON DELETE RESTRICT,
      name             text NOT NULL,
      base_price_cents int  NOT NULL DEFAULT 0,
      price_type       text NOT NULL DEFAULT 'fixed',
      emoji            text NOT NULL DEFAULT '',
      image_url        text,
      sort_order       int  NOT NULL DEFAULT 0,
      is_hidden        bool NOT NULL DEFAULT false,
      data             jsonb NOT NULL DEFAULT '{}'::jsonb,
      created_at       timestamptz NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_menu_items_category ON public.menu_items (category_id);
    -- Self-heal: image_url was added in migration 013, after some installs already had menu_items.
    ALTER TABLE public.menu_items ADD COLUMN IF NOT EXISTS image_url text;

    CREATE TABLE IF NOT EXISTS public.menu_modifier_groups (
      id             text PRIMARY KEY,
      name           text NOT NULL,
      allow_multiple bool NOT NULL DEFAULT false,
      is_hidden      bool NOT NULL DEFAULT false,
      sort_order     int  NOT NULL DEFAULT 0,
      data           jsonb NOT NULL DEFAULT '{}'::jsonb,
      created_at     timestamptz NOT NULL DEFAULT now()
    );
    -- Heals installs that ran an earlier draft of this migration.
    ALTER TABLE public.menu_modifier_groups ADD COLUMN IF NOT EXISTS allow_multiple bool NOT NULL DEFAULT false;
    ALTER TABLE public.menu_modifier_groups ADD COLUMN IF NOT EXISTS is_hidden bool NOT NULL DEFAULT false;

    -- ON UPDATE CASCADE: the group id is a slug derived from its display name,
    -- so renaming a group changes the id. Cascading keeps options + item links
    -- in sync without a multi-step migration.
    CREATE TABLE IF NOT EXISTS public.menu_modifier_options (
      id                text PRIMARY KEY,
      group_id          text NOT NULL REFERENCES public.menu_modifier_groups(id) ON UPDATE CASCADE ON DELETE CASCADE,
      name              text NOT NULL,
      price_delta_cents int  NOT NULL DEFAULT 0,
      sort_order        int  NOT NULL DEFAULT 0,
      data              jsonb NOT NULL DEFAULT '{}'::jsonb
    );
    CREATE INDEX IF NOT EXISTS idx_menu_modifier_options_group ON public.menu_modifier_options (group_id);

    CREATE TABLE IF NOT EXISTS public.menu_item_modifier_groups (
      item_id     text NOT NULL REFERENCES public.menu_items(id) ON UPDATE CASCADE ON DELETE CASCADE,
      group_id    text NOT NULL REFERENCES public.menu_modifier_groups(id) ON UPDATE CASCADE ON DELETE CASCADE,
      sort_order  int  NOT NULL DEFAULT 0,
      PRIMARY KEY (item_id, group_id)
    );

    -- FK self-heal: an earlier draft of 010 created these without ON UPDATE
    -- CASCADE, and CREATE TABLE IF NOT EXISTS won't touch existing constraints.
    -- Idempotent: drop + recreate with the correct action.
    ALTER TABLE public.menu_modifier_options
      DROP CONSTRAINT IF EXISTS menu_modifier_options_group_id_fkey;
    ALTER TABLE public.menu_modifier_options
      ADD CONSTRAINT menu_modifier_options_group_id_fkey
        FOREIGN KEY (group_id) REFERENCES public.menu_modifier_groups(id)
        ON UPDATE CASCADE ON DELETE CASCADE;

    ALTER TABLE public.menu_item_modifier_groups
      DROP CONSTRAINT IF EXISTS menu_item_modifier_groups_group_id_fkey;
    ALTER TABLE public.menu_item_modifier_groups
      ADD CONSTRAINT menu_item_modifier_groups_group_id_fkey
        FOREIGN KEY (group_id) REFERENCES public.menu_modifier_groups(id)
        ON UPDATE CASCADE ON DELETE CASCADE;

    ALTER TABLE public.menu_item_modifier_groups
      DROP CONSTRAINT IF EXISTS menu_item_modifier_groups_item_id_fkey;
    ALTER TABLE public.menu_item_modifier_groups
      ADD CONSTRAINT menu_item_modifier_groups_item_id_fkey
        FOREIGN KEY (item_id) REFERENCES public.menu_items(id)
        ON UPDATE CASCADE ON DELETE CASCADE;

    -- Public-menu hide split (migration 030): the public-menu RPCs key off a
    -- dedicated public flag, separate from is_hidden (which stays the
    -- Register/POS flag). Add the category column + backfill the public flag
    -- from is_hidden ONCE (guarded on first creation) so anything currently
    -- hidden stays hidden in both places until an owner changes it. Items use
    -- data->>'publicHidden' (no column) and round-trip via the residual spread.
    --
    -- MUST stay here, with the DDL: build_menu_snapshot() below is LANGUAGE sql,
    -- which Postgres parses and validates at CREATE time, and it selects
    -- c.public_hidden. Adding the column after that point makes the whole script
    -- fail on any DB that predates the column.
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'menu_categories'
          AND column_name = 'public_hidden'
      ) THEN
        ALTER TABLE public.menu_categories
          ADD COLUMN public_hidden bool NOT NULL DEFAULT false;
        UPDATE public.menu_categories SET public_hidden = true WHERE is_hidden = true;
        UPDATE public.menu_items
          SET data = jsonb_set(COALESCE(data, '{}'::jsonb), '{publicHidden}', 'true'::jsonb, true)
          WHERE is_hidden = true
            AND NOT (COALESCE(data, '{}'::jsonb) ? 'publicHidden');
      END IF;
    END $$;

    CREATE TABLE IF NOT EXISTS public.menu_discount_rules (
      id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name        text NOT NULL DEFAULT '',
      rule_type   text NOT NULL DEFAULT '',
      payload     jsonb NOT NULL DEFAULT '{}'::jsonb,
      is_active   bool NOT NULL DEFAULT true,
      sort_order  int  NOT NULL DEFAULT 0,
      created_at  timestamptz NOT NULL DEFAULT now()
    );

    -- Multi-vendor sales registry (migration 023). Catalog/reference data, so it
    -- mirrors menu_categories: client-generated text id, RLS TO authenticated.
    -- The item -> vendor link lives on menu_items.data jsonb ({ vendorId, vendorName }).
    CREATE TABLE IF NOT EXISTS public.vendors (
      id                 text PRIMARY KEY,
      name               text NOT NULL,
      contact            text NOT NULL DEFAULT '',
      commission_percent numeric NOT NULL DEFAULT 0,
      is_active          bool NOT NULL DEFAULT true,
      sort_order         int  NOT NULL DEFAULT 0,
      data               jsonb NOT NULL DEFAULT '{}'::jsonb,  -- per-vendor settings: { splitType: 'percentage' | 'cost' }
      created_at         timestamptz NOT NULL DEFAULT now()
    );

    ALTER TABLE public.menu_categories           ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.menu_items                ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.menu_modifier_groups      ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.menu_modifier_options     ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.menu_item_modifier_groups ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.menu_discount_rules       ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.vendors                   ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Hardware can access menu_categories"           ON public.menu_categories;
    DROP POLICY IF EXISTS "Hardware can access menu_items"                ON public.menu_items;
    DROP POLICY IF EXISTS "Hardware can access menu_modifier_groups"      ON public.menu_modifier_groups;
    DROP POLICY IF EXISTS "Hardware can access menu_modifier_options"     ON public.menu_modifier_options;
    DROP POLICY IF EXISTS "Hardware can access menu_item_modifier_groups" ON public.menu_item_modifier_groups;
    DROP POLICY IF EXISTS "Hardware can access menu_discount_rules"       ON public.menu_discount_rules;
    DROP POLICY IF EXISTS "Hardware can access vendors"                   ON public.vendors;

    CREATE POLICY "Hardware can access menu_categories"           ON public.menu_categories           FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access menu_items"                ON public.menu_items                FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access menu_modifier_groups"      ON public.menu_modifier_groups      FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access menu_modifier_options"     ON public.menu_modifier_options     FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access menu_item_modifier_groups" ON public.menu_item_modifier_groups FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access menu_discount_rules"       ON public.menu_discount_rules       FOR ALL TO authenticated USING (true) WITH CHECK (true);
    CREATE POLICY "Hardware can access vendors"                   ON public.vendors                   FOR ALL TO authenticated USING (true) WITH CHECK (true);

    -- Vendor payout ledger (migration 024). Records money actually paid to each
    -- vendor; each row freezes the settlement it was paid against in data.
    CREATE TABLE IF NOT EXISTS public.vendor_payouts (
      id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      vendor_id     text,
      vendor_name   text NOT NULL,
      period_from   date,
      period_to     date,
      owed_cents    numeric NOT NULL DEFAULT 0,
      amount        numeric NOT NULL,                   -- cents; negative = reversal
      method        text DEFAULT 'cash',
      note          text,
      cashier_name  text,
      data          jsonb NOT NULL DEFAULT '{}'::jsonb,  -- frozen statement: { items, totals, range, menuFallback }
      local_id      uuid UNIQUE,
      created_at    timestamptz NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_vendor_payouts_vendor  ON public.vendor_payouts (vendor_id);
    CREATE INDEX IF NOT EXISTS idx_vendor_payouts_created ON public.vendor_payouts (created_at);
    ALTER TABLE public.vendor_payouts ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Hardware can access vendor_payouts" ON public.vendor_payouts;
    CREATE POLICY "Hardware can access vendor_payouts" ON public.vendor_payouts FOR ALL TO authenticated USING (true) WITH CHECK (true);

    -- ==========================================
    -- MENU VERSIONS (migration 014): point-in-time snapshots + restore.
    -- Every menu write writes a snapshot; admins browse history and roll back.
    -- ==========================================
    CREATE TABLE IF NOT EXISTS public.menu_versions (
      id          bigserial PRIMARY KEY,
      created_at  timestamptz NOT NULL DEFAULT now(),
      snapshot    jsonb NOT NULL,
      reason      text NOT NULL DEFAULT 'auto',
      trigger_op  text
    );
    CREATE INDEX IF NOT EXISTS idx_menu_versions_created ON public.menu_versions (created_at DESC);
    ALTER TABLE public.menu_versions ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "menu_versions auth all" ON public.menu_versions;
    CREATE POLICY "menu_versions auth all" ON public.menu_versions FOR ALL TO authenticated USING (true) WITH CHECK (true);

    CREATE OR REPLACE FUNCTION public.build_menu_snapshot()
    RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
      SELECT jsonb_build_object(
        'categories', COALESCE((
          SELECT jsonb_object_agg(c.name, COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
              'id', i.id, 'name', i.name, 'basePrice', i.base_price_cents,
              'priceType', i.price_type, 'emoji', i.emoji, 'imageUrl', i.image_url,
              'isHidden', i.is_hidden,
              'allowedModifiers', COALESCE((
                SELECT jsonb_agg(l.group_id ORDER BY l.sort_order)
                FROM public.menu_item_modifier_groups l WHERE l.item_id = i.id
              ), '[]'::jsonb)
            ) || COALESCE(i.data, '{}'::jsonb) ORDER BY i.sort_order)
            FROM public.menu_items i WHERE i.category_id = c.id
          ), '[]'::jsonb)) FROM public.menu_categories c
        ), '{}'::jsonb),
        'categoryOrder', COALESCE((SELECT jsonb_agg(c.name ORDER BY c.sort_order) FROM public.menu_categories c), '[]'::jsonb),
        'hiddenCategories', COALESCE((SELECT jsonb_agg(c.name) FROM public.menu_categories c WHERE c.is_hidden), '[]'::jsonb),
        'publicHiddenCategories', COALESCE((SELECT jsonb_agg(c.name) FROM public.menu_categories c WHERE c.public_hidden), '[]'::jsonb),
        'modifierGroups', COALESCE((
          SELECT jsonb_object_agg(g.id, COALESCE((
            SELECT jsonb_agg(jsonb_build_object('id', o.id, 'name', o.name, 'price', o.price_delta_cents) || COALESCE(o.data, '{}'::jsonb) ORDER BY o.sort_order)
            FROM public.menu_modifier_options o WHERE o.group_id = g.id
          ), '[]'::jsonb)) FROM public.menu_modifier_groups g
        ), '{}'::jsonb),
        'modifierGroupSettings', COALESCE((
          SELECT jsonb_object_agg(g.id, jsonb_build_object('allowMultiple', g.allow_multiple, 'isHidden', g.is_hidden)) FROM public.menu_modifier_groups g
        ), '{}'::jsonb),
        'discountRules', COALESCE((SELECT jsonb_agg(r.payload ORDER BY r.sort_order) FROM public.menu_discount_rules r), '[]'::jsonb)
      );
    $$;
    REVOKE ALL ON FUNCTION public.build_menu_snapshot() FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION public.build_menu_snapshot() TO authenticated;

    CREATE OR REPLACE FUNCTION public.prune_menu_versions()
    RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
      WITH
        keep_manual AS (SELECT id FROM public.menu_versions WHERE reason <> 'auto'),
        keep_recent AS (SELECT id FROM public.menu_versions WHERE created_at > now() - interval '7 days'),
        keep_daily  AS (
          SELECT DISTINCT ON (date_trunc('day', created_at)) id
          FROM public.menu_versions WHERE created_at > now() - interval '30 days'
          ORDER BY date_trunc('day', created_at), created_at DESC
        ),
        keep_weekly AS (
          SELECT DISTINCT ON (date_trunc('week', created_at)) id
          FROM public.menu_versions WHERE created_at > now() - interval '1 year'
          ORDER BY date_trunc('week', created_at), created_at DESC
        ),
        keep AS (
          SELECT id FROM keep_manual UNION SELECT id FROM keep_recent
          UNION SELECT id FROM keep_daily UNION SELECT id FROM keep_weekly
        )
      DELETE FROM public.menu_versions WHERE id NOT IN (SELECT id FROM keep);
    $$;
    REVOKE ALL ON FUNCTION public.prune_menu_versions() FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION public.prune_menu_versions() TO authenticated;

    CREATE OR REPLACE FUNCTION public.snapshot_menu(p_reason text DEFAULT 'auto', p_trigger_op text DEFAULT NULL)
    RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
    DECLARE v_snap jsonb; v_last jsonb; v_id bigint;
    BEGIN
      v_snap := public.build_menu_snapshot();
      SELECT snapshot INTO v_last FROM public.menu_versions ORDER BY id DESC LIMIT 1;
      IF v_last IS NOT NULL AND v_last = v_snap AND p_reason = 'auto' THEN RETURN NULL; END IF;
      INSERT INTO public.menu_versions (snapshot, reason, trigger_op)
        VALUES (v_snap, COALESCE(p_reason,'auto'), p_trigger_op) RETURNING id INTO v_id;
      PERFORM public.prune_menu_versions();
      RETURN v_id;
    END $$;
    REVOKE ALL ON FUNCTION public.snapshot_menu(text, text) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION public.snapshot_menu(text, text) TO authenticated;

    CREATE OR REPLACE FUNCTION public.restore_menu_version(p_version_id bigint)
    RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
    DECLARE v_snap jsonb; v_pre bigint; v_cats int := 0; v_items int := 0;
    BEGIN
      SELECT snapshot INTO v_snap FROM public.menu_versions WHERE id = p_version_id;
      IF v_snap IS NULL THEN RAISE EXCEPTION 'menu_versions row % not found', p_version_id; END IF;
      v_pre := public.snapshot_menu('restore-target', 'before-restore-of-' || p_version_id);

      DELETE FROM public.menu_item_modifier_groups;
      DELETE FROM public.menu_modifier_options;
      DELETE FROM public.menu_modifier_groups;
      DELETE FROM public.menu_items;
      DELETE FROM public.menu_categories;
      DELETE FROM public.menu_discount_rules;

      WITH ordered AS (
        SELECT key, ord FROM jsonb_array_elements_text(COALESCE(v_snap->'categoryOrder','[]'::jsonb))
          WITH ORDINALITY AS o(key, ord)
      )
      INSERT INTO public.menu_categories (name, sort_order, is_hidden, public_hidden)
      SELECT k, COALESCE((SELECT ord FROM ordered WHERE key=k)::int, 1000),
             (COALESCE(v_snap->'hiddenCategories','[]'::jsonb) ? k),
             (COALESCE(v_snap->'publicHiddenCategories','[]'::jsonb) ? k)
      FROM jsonb_object_keys(COALESCE(v_snap->'categories','{}'::jsonb)) AS k;
      GET DIAGNOSTICS v_cats = ROW_COUNT;

      INSERT INTO public.menu_items
        (id, category_id, name, base_price_cents, price_type, emoji, image_url, sort_order, is_hidden, data)
      SELECT
        item->>'id', mc.id,
        COALESCE(item->>'name',''),
        COALESCE((item->>'basePrice')::int, 0),
        COALESCE(item->>'priceType','fixed'),
        COALESCE(item->>'emoji',''),
        NULLIF(item->>'imageUrl',''),
        (it.ord - 1)::int, COALESCE((item->>'isHidden')::bool, false),
        (item - 'id' - 'name' - 'basePrice' - 'priceType' - 'emoji' - 'imageUrl' - 'isHidden' - 'allowedModifiers' - 'category')
      FROM jsonb_each(COALESCE(v_snap->'categories','{}'::jsonb)) AS cat(key, value)
      JOIN public.menu_categories mc ON mc.name = cat.key
      CROSS JOIN LATERAL jsonb_array_elements(cat.value) WITH ORDINALITY AS it(item, ord)
      WHERE item->>'id' IS NOT NULL;
      GET DIAGNOSTICS v_items = ROW_COUNT;

      INSERT INTO public.menu_modifier_groups (id, name, allow_multiple, is_hidden, sort_order)
      SELECT key, key,
             COALESCE((v_snap->'modifierGroupSettings'->key->>'allowMultiple')::bool, false),
             COALESCE((v_snap->'modifierGroupSettings'->key->>'isHidden')::bool, false),
             ((row_number() OVER (ORDER BY key)) - 1)::int
      FROM jsonb_object_keys(COALESCE(v_snap->'modifierGroups','{}'::jsonb)) AS key;

      INSERT INTO public.menu_modifier_options (id, group_id, name, price_delta_cents, sort_order, data)
      SELECT opt->>'id', grp.key, COALESCE(opt->>'name',''),
             COALESCE((opt->>'price')::int, (opt->>'price_delta_cents')::int, 0),
             (o.ord - 1)::int,
             (opt - 'id' - 'name' - 'price' - 'price_delta_cents')
      FROM jsonb_each(COALESCE(v_snap->'modifierGroups','{}'::jsonb)) AS grp(key, value)
      CROSS JOIN LATERAL jsonb_array_elements(grp.value) WITH ORDINALITY AS o(opt, ord)
      WHERE opt->>'id' IS NOT NULL;

      INSERT INTO public.menu_item_modifier_groups (item_id, group_id, sort_order)
      SELECT item->>'id', m.mod_key, (m.ord - 1)::int
      FROM jsonb_each(COALESCE(v_snap->'categories','{}'::jsonb)) AS cat(key, value)
      CROSS JOIN LATERAL jsonb_array_elements(cat.value) AS item
      CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(item->'allowedModifiers','[]'::jsonb))
                         WITH ORDINALITY AS m(mod_key, ord)
      WHERE EXISTS (SELECT 1 FROM public.menu_items mi WHERE mi.id = item->>'id')
        AND EXISTS (SELECT 1 FROM public.menu_modifier_groups mg WHERE mg.id = m.mod_key);

      INSERT INTO public.menu_discount_rules (name, rule_type, payload, is_active, sort_order)
      SELECT COALESCE(rule->>'name',''), COALESCE(rule->>'type',''), rule,
             COALESCE((rule->>'isActive')::bool, true), (r.ord - 1)::int
      FROM jsonb_array_elements(COALESCE(v_snap->'discountRules','[]'::jsonb))
           WITH ORDINALITY AS r(rule, ord);

      RETURN jsonb_build_object('restored_from', p_version_id, 'previous_snapshot_id', v_pre,
                                'inserted_categories', v_cats, 'inserted_items', v_items);
    END $$;
    REVOKE ALL ON FUNCTION public.restore_menu_version(bigint) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION public.restore_menu_version(bigint) TO authenticated;

    DO $menu_split$
    DECLARE
      v_menu     jsonb;
      v_order    jsonb;
      v_hidden   jsonb;
      v_items_in int := 0;
    BEGIN
      IF EXISTS (SELECT 1 FROM public.menu_categories) THEN RETURN; END IF;

      SELECT menu_data INTO v_menu FROM public.shop_settings WHERE id = 1;
      IF v_menu IS NULL THEN RETURN; END IF;

      -- Safety net: archive the raw legacy JSONB as a menu_versions row BEFORE
      -- attempting to migrate. If the migrator's shape assumptions miss
      -- anything, this row is the recovery surface. The menu_versions table
      -- has to exist already (created earlier in this install run via
      -- migration 014). If it doesn't (older installs running the function
      -- standalone), the CREATE TABLE IF NOT EXISTS above guarantees it.
      BEGIN
        INSERT INTO public.menu_versions (snapshot, reason, trigger_op)
          VALUES (v_menu, 'pre-jsonb-strip', 'install_split_menu_data');
      EXCEPTION WHEN undefined_table THEN
        -- menu_versions not created yet on this run; ignore. Strip is gated
        -- on v_items_in > 0 below, so data is still safe.
        NULL;
      END;

      v_order  := COALESCE(v_menu->'categoryOrder',    '[]'::jsonb);
      v_hidden := COALESCE(v_menu->'hiddenCategories', '[]'::jsonb);

      -- categories: sort_order = position in categoryOrder if listed, else 1000+
      WITH ordered AS (
        SELECT key, ord
        FROM jsonb_array_elements_text(v_order) WITH ORDINALITY AS o(key, ord)
      )
      INSERT INTO public.menu_categories (name, sort_order, is_hidden)
      SELECT k,
             COALESCE((SELECT ord FROM ordered WHERE key = k)::int, 1000),
             (v_hidden ? k)
      FROM jsonb_object_keys(COALESCE(v_menu->'categories','{}'::jsonb)) AS k
      ON CONFLICT (name) DO NOTHING;

      -- items
      INSERT INTO public.menu_items (id, category_id, name, base_price_cents, price_type, emoji, sort_order, is_hidden, data)
      SELECT
        item->>'id',
        mc.id,
        COALESCE(item->>'name', ''),
        COALESCE((item->>'basePrice')::int, 0),
        COALESCE(item->>'priceType', 'fixed'),
        COALESCE(item->>'emoji', ''),
        (it.ord - 1)::int,
        COALESCE((item->>'isHidden')::bool, false),
        (item - 'id' - 'name' - 'basePrice' - 'priceType' - 'emoji' - 'isHidden' - 'allowedModifiers' - 'category')
      FROM jsonb_each(COALESCE(v_menu->'categories','{}'::jsonb)) AS cat(key, value)
      JOIN public.menu_categories mc ON mc.name = cat.key
      CROSS JOIN LATERAL jsonb_array_elements(cat.value) WITH ORDINALITY AS it(item, ord)
      WHERE item->>'id' IS NOT NULL
      ON CONFLICT (id) DO NOTHING;
      GET DIAGNOSTICS v_items_in = ROW_COUNT;

      -- modifier groups; allow_multiple/is_hidden live in menu_data.modifierGroupSettings[key]
      INSERT INTO public.menu_modifier_groups (id, name, allow_multiple, is_hidden, sort_order)
      SELECT key, key,
             COALESCE((v_menu->'modifierGroupSettings'->key->>'allowMultiple')::bool, false),
             COALESCE((v_menu->'modifierGroupSettings'->key->>'isHidden')::bool, false),
             ((row_number() OVER (ORDER BY key)) - 1)::int
      FROM jsonb_object_keys(COALESCE(v_menu->'modifierGroups','{}'::jsonb)) AS key
      ON CONFLICT (id) DO NOTHING;

      -- modifier options
      INSERT INTO public.menu_modifier_options (id, group_id, name, price_delta_cents, sort_order, data)
      SELECT
        opt->>'id',
        grp.key,
        COALESCE(opt->>'name', ''),
        COALESCE((opt->>'priceDelta')::int, (opt->>'price_delta_cents')::int, 0),
        (o.ord - 1)::int,
        (opt - 'id' - 'name' - 'priceDelta' - 'price_delta_cents')
      FROM jsonb_each(COALESCE(v_menu->'modifierGroups','{}'::jsonb)) AS grp(key, value)
      CROSS JOIN LATERAL jsonb_array_elements(grp.value) WITH ORDINALITY AS o(opt, ord)
      WHERE opt->>'id' IS NOT NULL
      ON CONFLICT (id) DO NOTHING;

      -- item ↔ modifier-group links (skip orphans where either side missing)
      INSERT INTO public.menu_item_modifier_groups (item_id, group_id, sort_order)
      SELECT item->>'id', m.mod_key, (m.ord - 1)::int
      FROM jsonb_each(COALESCE(v_menu->'categories','{}'::jsonb)) AS cat(key, value)
      CROSS JOIN LATERAL jsonb_array_elements(cat.value) AS item
      CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(item->'allowedModifiers','[]'::jsonb))
                         WITH ORDINALITY AS m(mod_key, ord)
      WHERE EXISTS (SELECT 1 FROM public.menu_items         mi WHERE mi.id = item->>'id')
        AND EXISTS (SELECT 1 FROM public.menu_modifier_groups mg WHERE mg.id = m.mod_key)
      ON CONFLICT DO NOTHING;

      -- discount rules
      INSERT INTO public.menu_discount_rules (name, rule_type, payload, is_active, sort_order)
      SELECT
        COALESCE(rule->>'name',''),
        COALESCE(rule->>'type',''),
        rule,
        COALESCE((rule->>'isActive')::bool, true),
        (r.ord - 1)::int
      FROM jsonb_array_elements(COALESCE(v_menu->'discountRules','[]'::jsonb))
           WITH ORDINALITY AS r(rule, ord);

      -- Strip migrated keys from menu_data ONLY if the items migration
      -- actually produced rows. If v_items_in = 0 the JSONB shape didn't
      -- match the migrator and stripping would erase the only copy that
      -- exists. Leaving the legacy keys in place means loadMenu() still
      -- sees empty tables (the new source of truth), but recovery is
      -- trivial — the legacy data is still queryable in menu_data and in
      -- the menu_versions 'pre-jsonb-strip' snapshot above.
      IF v_items_in > 0 THEN
        UPDATE public.shop_settings
        SET menu_data = menu_data
                        - 'categories'
                        - 'categoryOrder'
                        - 'hiddenCategories'
                        - 'modifierGroups'
                        - 'modifierGroupSettings'
                        - 'discountRules'
        WHERE id = 1;
      END IF;
    END
    $menu_split$;

    -- Loyalty trigger: fires AFTER INSERT on sales, exactly once per sale.
    -- Idempotent by construction — sales upserts use onConflict: local_id, so retries
    -- don't fire INSERT triggers on conflict. Behavior:
    --   1. ACCRUE: customers.visits += loyalty_stars_awarded (clamped at 0).
    --   2. REDEEM: customers.visits -= loyalty_stars_redeemed (clamped at 0).
    --      Net change per sale = awarded - redeemed.
    --   3. SINGLE-MODE LOCKOUT: if customer.completed_at IS NOT NULL, suppress accrual
    --      (frozen customers can't earn more stars; redemption still works).
    --   4. FREEZE: if loyalty_program_type = 'single' AND redemption occurred,
    --      set customers.completed_at = now() to lock the customer out of future accrual.
    --      Admin "Reset stars" clears completed_at to start a fresh campaign.
    CREATE OR REPLACE FUNCTION public.award_loyalty_visits()
    RETURNS TRIGGER AS $$
    DECLARE
      v_awarded integer := COALESCE(NEW.loyalty_stars_awarded, 0);
      v_redeemed integer := COALESCE(NEW.loyalty_stars_redeemed, 0);
      v_completed timestamp with time zone;
      v_net integer;
    BEGIN
      IF NEW.loyalty_phone IS NULL OR (v_awarded = 0 AND v_redeemed = 0) THEN
        RETURN NEW;
      END IF;

      SELECT completed_at INTO v_completed FROM public.customers WHERE phone = NEW.loyalty_phone;

      IF v_completed IS NOT NULL AND v_awarded > 0 THEN
        v_awarded := 0;
      END IF;

      v_net := v_awarded - v_redeemed;

      INSERT INTO public.customers (phone, visits)
      VALUES (NEW.loyalty_phone, GREATEST(0, v_net))
      ON CONFLICT (phone) DO UPDATE
        SET visits = GREATEST(0, public.customers.visits + v_net);

      IF NEW.loyalty_program_type = 'single' AND v_redeemed > 0 THEN
        UPDATE public.customers SET completed_at = now() WHERE phone = NEW.loyalty_phone;
      END IF;

      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;

    DROP TRIGGER IF EXISTS trg_award_loyalty ON public.sales;
    CREATE TRIGGER trg_award_loyalty
      AFTER INSERT ON public.sales
      FOR EACH ROW
      EXECUTE FUNCTION public.award_loyalty_visits();

    -- ==========================================
    -- PUBLIC LIVE MENU: sanitized read-only RPC for the customer-facing page.
    -- Internal/operational fields (item data jsonb, inventory refs, cost) never
    -- leave the server. EXECUTE granted to anon so visitors only need the anon
    -- key — no service role, no extra auth.
    -- ==========================================
    -- Self-heal: ensure menu_items.image_url (migration 013) exists before
    -- the resolver below references it. Safe on installs that already added it.
    ALTER TABLE public.menu_items ADD COLUMN IF NOT EXISTS image_url text;

    -- ==========================================
    -- MENUS + SCHEDULES (migration 015): multi-menu support with time-of-day
    -- and date-range scheduling. The existing catalog becomes an implicit
    -- kind='live' row, with other kinds (pdf/image/designed) layered on top.
    -- Resolver picks the active menu server-side so TV mode + customer phone
    -- always agree.
    -- ==========================================
    CREATE TABLE IF NOT EXISTS public.menus (
      id          bigserial PRIMARY KEY,
      name        text NOT NULL,
      kind        text NOT NULL DEFAULT 'live'
                  CHECK (kind IN ('live','pdf','image','designed')),
      priority    int  NOT NULL DEFAULT 0,
      is_active   bool NOT NULL DEFAULT true,
      data        jsonb NOT NULL DEFAULT '{}'::jsonb,
      created_at  timestamptz NOT NULL DEFAULT now()
    );
    CREATE UNIQUE INDEX IF NOT EXISTS uniq_menus_live
      ON public.menus ((1)) WHERE kind = 'live';
    ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "menus auth all" ON public.menus;
    CREATE POLICY "menus auth all" ON public.menus FOR ALL TO authenticated USING (true) WITH CHECK (true);

    INSERT INTO public.menus (name, kind, priority, is_active)
    SELECT 'Menú principal', 'live', 0, true
    WHERE NOT EXISTS (SELECT 1 FROM public.menus WHERE kind = 'live');

    CREATE TABLE IF NOT EXISTS public.menu_schedules (
      id             bigserial PRIMARY KEY,
      menu_id        bigint NOT NULL REFERENCES public.menus(id) ON DELETE CASCADE,
      days_of_week   int  NOT NULL DEFAULT 0,
      start_time     time,
      end_time       time,
      start_date     date,
      end_date       date,
      created_at     timestamptz NOT NULL DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS idx_menu_schedules_menu ON public.menu_schedules (menu_id);
    ALTER TABLE public.menu_schedules ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "menu_schedules auth all" ON public.menu_schedules;
    CREATE POLICY "menu_schedules auth all" ON public.menu_schedules FOR ALL TO authenticated USING (true) WITH CHECK (true);

    CREATE OR REPLACE FUNCTION public.shop_timezone()
    RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
      SELECT COALESCE(
        (SELECT menu_data->'posSettings'->>'timezone' FROM public.shop_settings WHERE id = 1),
        'UTC'
      );
    $$;
    REVOKE ALL ON FUNCTION public.shop_timezone() FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION public.shop_timezone() TO anon, authenticated;

    CREATE OR REPLACE FUNCTION public.schedule_matches(
      p_days int, p_start_time time, p_end_time time,
      p_start_date date, p_end_date date, p_local timestamp
    ) RETURNS bool LANGUAGE sql IMMUTABLE AS $$
      SELECT
        (p_start_date IS NULL OR p_local::date >= p_start_date)
        AND (p_end_date IS NULL OR p_local::date <= p_end_date)
        AND (
          COALESCE(p_days, 0) = 0
          OR (COALESCE(p_days, 0) & (1 << (EXTRACT(isodow FROM p_local)::int - 1))) <> 0
        )
        AND (
          (p_start_time IS NULL AND p_end_time IS NULL)
          OR (p_start_time IS NOT NULL AND p_end_time IS NOT NULL AND p_start_time <= p_end_time
              AND p_local::time >= p_start_time AND p_local::time < p_end_time)
          OR (p_start_time IS NOT NULL AND p_end_time IS NOT NULL AND p_start_time > p_end_time
              AND (p_local::time >= p_start_time OR p_local::time < p_end_time))
          OR (p_start_time IS NOT NULL AND p_end_time IS NULL AND p_local::time >= p_start_time)
          OR (p_start_time IS NULL AND p_end_time IS NOT NULL AND p_local::time < p_end_time)
        );
    $$;

    -- Per-item availability (migration 018). Pure read of inventory state.
    -- Tolerates malformed refs by returning true — better to show than to
    -- hide on bad data.
    CREATE OR REPLACE FUNCTION public.menu_item_available(p_item_id text)
    RETURNS bool LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
    DECLARE
      v_data jsonb; v_mode text; v_short_id bigint;
    BEGIN
      SELECT data INTO v_data FROM public.menu_items WHERE id = p_item_id;
      IF v_data IS NULL THEN RETURN true; END IF;
      v_mode := COALESCE(v_data->>'inventoryMode', 'none');
      IF v_mode IN ('warehouse', 'standard') THEN
        BEGIN v_short_id := NULLIF(v_data->>'linkedWarehouseId','')::bigint;
        EXCEPTION WHEN OTHERS THEN RETURN true; END;
        IF v_short_id IS NULL THEN RETURN true; END IF;
        RETURN COALESCE((SELECT current_stock > 0 FROM public.inventory WHERE id = v_short_id), true);
      END IF;
      IF v_mode = 'recipe' THEN
        DECLARE v_rid uuid;
        BEGIN
          BEGIN v_rid := NULLIF(v_data->>'linkedRecipeId','')::uuid;
          EXCEPTION WHEN OTHERS THEN RETURN true; END;
          IF v_rid IS NULL THEN RETURN true; END IF;
          RETURN NOT EXISTS (
            SELECT 1 FROM public.recipes r,
                 LATERAL jsonb_array_elements(COALESCE(r.ingredients,'[]'::jsonb)) AS ing(val)
            WHERE r.id = v_rid
              AND COALESCE(
                    (SELECT current_stock FROM public.inventory
                      WHERE id = (CASE WHEN (ing.val->>'id') ~ '^[0-9]+$' THEN (ing.val->>'id')::bigint ELSE NULL END)),
                    0
                  ) < (CASE WHEN (ing.val->>'qty') ~ '^-?[0-9]+(\.[0-9]+)?$' THEN (ing.val->>'qty')::numeric ELSE 0 END)
          );
        END;
      END IF;
      RETURN true;
    END $$;
    REVOKE ALL ON FUNCTION public.menu_item_available(text) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION public.menu_item_available(text) TO anon, authenticated;

    CREATE OR REPLACE FUNCTION public.get_active_menu(p_now timestamptz DEFAULT now())
    RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public STABLE AS $$
    DECLARE
      v_tz text; v_local timestamp;
      v_menu_id bigint; v_kind text; v_name text; v_data jsonb; v_shop jsonb;
    BEGIN
      v_tz := public.shop_timezone();
      v_local := (p_now AT TIME ZONE v_tz)::timestamp;

      SELECT m.id, m.kind, m.name, m.data INTO v_menu_id, v_kind, v_name, v_data
      FROM public.menus m
      WHERE m.is_active = true
        AND (
          NOT EXISTS (SELECT 1 FROM public.menu_schedules s WHERE s.menu_id = m.id)
          OR EXISTS (
            SELECT 1 FROM public.menu_schedules s
            WHERE s.menu_id = m.id
              AND public.schedule_matches(s.days_of_week, s.start_time, s.end_time,
                                          s.start_date, s.end_date, v_local)
          )
        )
      ORDER BY m.priority DESC, m.created_at DESC LIMIT 1;

      IF v_menu_id IS NULL THEN
        SELECT m.id, m.kind, m.name, m.data INTO v_menu_id, v_kind, v_name, v_data
        FROM public.menus m WHERE m.kind = 'live' LIMIT 1;
      END IF;

      v_shop := jsonb_build_object(
        'name',        COALESCE((SELECT menu_data->'posSettings'->>'name'       FROM public.shop_settings WHERE id = 1), 'Menu'),
        'brand_color', COALESCE((SELECT menu_data->'posSettings'->>'brandColor' FROM public.shop_settings WHERE id = 1), '#f28b05'),
        'language',    COALESCE((SELECT menu_data->'posSettings'->>'language'   FROM public.shop_settings WHERE id = 1), 'es'),
        'timezone',    v_tz
      );

      IF v_kind = 'live' OR v_kind = 'designed' THEN
        RETURN jsonb_build_object(
          'menu', jsonb_build_object('id', v_menu_id, 'kind', v_kind, 'name', v_name, 'data', v_data),
          'shop', v_shop,
          'categories', COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
              'id', c.id, 'name', c.name, 'sort_order', c.sort_order,
              'items', COALESCE((
                SELECT jsonb_agg(jsonb_build_object(
                  'id', i.id, 'name', i.name, 'price_cents', i.base_price_cents,
                  'price_type', i.price_type, 'emoji', i.emoji, 'image_url', i.image_url,
                  'sort_order', i.sort_order,
                  'available', public.menu_item_available(i.id),
                  'roast_date', i.data->>'roastDate', 'whatsapp_url', i.data->>'whatsappUrl',
                  'modifier_group_ids', COALESCE((
                    SELECT jsonb_agg(l.group_id ORDER BY l.sort_order)
                    FROM public.menu_item_modifier_groups l
                    JOIN public.menu_modifier_groups g ON g.id = l.group_id
                    WHERE l.item_id = i.id AND g.is_hidden = false
                  ), '[]'::jsonb)
                ) ORDER BY i.sort_order)
                FROM public.menu_items i WHERE i.category_id = c.id
                  AND COALESCE((i.data->>'publicHidden')::boolean, false) = false
              ), '[]'::jsonb)
            ) ORDER BY c.sort_order)
            FROM public.menu_categories c WHERE c.public_hidden = false
          ), '[]'::jsonb),
          'modifier_groups', COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
              'id', g.id, 'name', g.name, 'allow_multiple', g.allow_multiple,
              'options', COALESCE((
                SELECT jsonb_agg(jsonb_build_object(
                  'id', o.id, 'name', o.name, 'price_delta_cents', o.price_delta_cents
                ) ORDER BY o.sort_order)
                FROM public.menu_modifier_options o WHERE o.group_id = g.id
              ), '[]'::jsonb)
            ) ORDER BY g.sort_order)
            FROM public.menu_modifier_groups g WHERE g.is_hidden = false
          ), '[]'::jsonb)
        );
      ELSE
        RETURN jsonb_build_object(
          'menu', jsonb_build_object('id', v_menu_id, 'kind', v_kind, 'name', v_name, 'data', v_data),
          'shop', v_shop,
          'categories', '[]'::jsonb,
          'modifier_groups', '[]'::jsonb
        );
      END IF;
    END $$;
    REVOKE ALL ON FUNCTION public.get_active_menu(timestamptz) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION public.get_active_menu(timestamptz) TO anon, authenticated;

    CREATE OR REPLACE FUNCTION public.get_public_menu()
    RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
      SELECT public.get_active_menu(now());
    $$;
    REVOKE ALL ON FUNCTION public.get_public_menu() FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION public.get_public_menu() TO anon, authenticated;

    -- Per-menu deep link (migration 017): /menu?m=<id> renders that specific
    -- menu regardless of schedule. Inactive or unknown id falls back to the
    -- catalog so stale QRs still render something.
    CREATE OR REPLACE FUNCTION public.get_menu_by_id(p_id bigint)
    RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public STABLE AS $$
    DECLARE
      v_tz text;
      v_menu_id bigint; v_kind text; v_name text; v_data jsonb; v_shop jsonb;
    BEGIN
      v_tz := public.shop_timezone();
      SELECT m.id, m.kind, m.name, m.data INTO v_menu_id, v_kind, v_name, v_data
      FROM public.menus m WHERE m.id = p_id AND m.is_active = true LIMIT 1;
      IF v_menu_id IS NULL THEN
        SELECT m.id, m.kind, m.name, m.data INTO v_menu_id, v_kind, v_name, v_data
        FROM public.menus m WHERE m.kind = 'live' LIMIT 1;
      END IF;
      v_shop := jsonb_build_object(
        'name', COALESCE((SELECT menu_data->'posSettings'->>'name' FROM public.shop_settings WHERE id = 1), 'Menu'),
        'brand_color', COALESCE((SELECT menu_data->'posSettings'->>'brandColor' FROM public.shop_settings WHERE id = 1), '#f28b05'),
        'language', COALESCE((SELECT menu_data->'posSettings'->>'language' FROM public.shop_settings WHERE id = 1), 'es'),
        'timezone', v_tz
      );
      IF v_kind = 'live' OR v_kind = 'designed' THEN
        RETURN jsonb_build_object(
          'menu', jsonb_build_object('id', v_menu_id, 'kind', v_kind, 'name', v_name, 'data', v_data),
          'shop', v_shop,
          'categories', COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
              'id', c.id, 'name', c.name, 'sort_order', c.sort_order,
              'items', COALESCE((
                SELECT jsonb_agg(jsonb_build_object(
                  'id', i.id, 'name', i.name, 'price_cents', i.base_price_cents,
                  'price_type', i.price_type, 'emoji', i.emoji, 'image_url', i.image_url,
                  'sort_order', i.sort_order,
                  'available', public.menu_item_available(i.id),
                  'roast_date', i.data->>'roastDate', 'whatsapp_url', i.data->>'whatsappUrl',
                  'modifier_group_ids', COALESCE((
                    SELECT jsonb_agg(l.group_id ORDER BY l.sort_order)
                    FROM public.menu_item_modifier_groups l
                    JOIN public.menu_modifier_groups g ON g.id = l.group_id
                    WHERE l.item_id = i.id AND g.is_hidden = false
                  ), '[]'::jsonb)
                ) ORDER BY i.sort_order)
                FROM public.menu_items i WHERE i.category_id = c.id
                  AND COALESCE((i.data->>'publicHidden')::boolean, false) = false
              ), '[]'::jsonb)
            ) ORDER BY c.sort_order)
            FROM public.menu_categories c WHERE c.public_hidden = false
          ), '[]'::jsonb),
          'modifier_groups', COALESCE((
            SELECT jsonb_agg(jsonb_build_object(
              'id', g.id, 'name', g.name, 'allow_multiple', g.allow_multiple,
              'options', COALESCE((
                SELECT jsonb_agg(jsonb_build_object(
                  'id', o.id, 'name', o.name, 'price_delta_cents', o.price_delta_cents
                ) ORDER BY o.sort_order)
                FROM public.menu_modifier_options o WHERE o.group_id = g.id
              ), '[]'::jsonb)
            ) ORDER BY g.sort_order)
            FROM public.menu_modifier_groups g WHERE g.is_hidden = false
          ), '[]'::jsonb)
        );
      ELSE
        RETURN jsonb_build_object(
          'menu', jsonb_build_object('id', v_menu_id, 'kind', v_kind, 'name', v_name, 'data', v_data),
          'shop', v_shop,
          'categories', '[]'::jsonb, 'modifier_groups', '[]'::jsonb
        );
      END IF;
    END $$;
    REVOKE ALL ON FUNCTION public.get_menu_by_id(bigint) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION public.get_menu_by_id(bigint) TO anon, authenticated;

    -- ==========================================
    -- STORAGE: menu-assets bucket for item photos (v0.2) and future menu media.
    -- Public read so the customer page can <img src=...> directly; writes
    -- gated to authenticated (admins).
    -- ==========================================
    INSERT INTO storage.buckets (id, name, public)
    VALUES ('menu-assets', 'menu-assets', true)
    ON CONFLICT (id) DO UPDATE SET public = true;

    DROP POLICY IF EXISTS "menu-assets public read" ON storage.objects;
    DROP POLICY IF EXISTS "menu-assets auth insert" ON storage.objects;
    DROP POLICY IF EXISTS "menu-assets auth update" ON storage.objects;
    DROP POLICY IF EXISTS "menu-assets auth delete" ON storage.objects;

    CREATE POLICY "menu-assets public read" ON storage.objects
      FOR SELECT TO public
      USING (bucket_id = 'menu-assets');
    CREATE POLICY "menu-assets auth insert" ON storage.objects
      FOR INSERT TO authenticated
      WITH CHECK (bucket_id = 'menu-assets');
    CREATE POLICY "menu-assets auth update" ON storage.objects
      FOR UPDATE TO authenticated
      USING (bucket_id = 'menu-assets')
      WITH CHECK (bucket_id = 'menu-assets');
    CREATE POLICY "menu-assets auth delete" ON storage.objects
      FOR DELETE TO authenticated
      USING (bucket_id = 'menu-assets');

    -- ==========================================
    -- STORAGE: menu bucket for short-URL redirect HTML files.
    -- Each shop uploads a tiny m.html that meta-refreshes to the long
    -- /menu?u=…&k=… URL. Public read so any visitor can hit the short
    -- link; writes gated to authenticated (admins).
    -- ==========================================
    INSERT INTO storage.buckets (id, name, public)
    VALUES ('menu', 'menu', true)
    ON CONFLICT (id) DO UPDATE SET public = true;

    DROP POLICY IF EXISTS "menu public read" ON storage.objects;
    DROP POLICY IF EXISTS "menu auth insert" ON storage.objects;
    DROP POLICY IF EXISTS "menu auth update" ON storage.objects;

    CREATE POLICY "menu public read" ON storage.objects
      FOR SELECT TO public
      USING (bucket_id = 'menu');
    CREATE POLICY "menu auth insert" ON storage.objects
      FOR INSERT TO authenticated
      WITH CHECK (bucket_id = 'menu');
    CREATE POLICY "menu auth update" ON storage.objects
      FOR UPDATE TO authenticated
      USING (bucket_id = 'menu')
      WITH CHECK (bucket_id = 'menu');

    -- Atomic inventory deduction (prevents race conditions)
    DROP FUNCTION IF EXISTS deduct_inventory(BIGINT, NUMERIC);
    CREATE OR REPLACE FUNCTION deduct_inventory(item_id BIGINT, qty NUMERIC)
    RETURNS TABLE (
      out_id BIGINT,
      out_name TEXT,
      out_current_stock NUMERIC
    ) AS $$
    BEGIN
      RETURN QUERY
      UPDATE public.inventory AS inv
      SET current_stock = inv.current_stock - qty
      WHERE inv.id = item_id AND inv.current_stock >= qty
      RETURNING inv.id, inv.name, inv.current_stock;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;

    -- Idempotent inventory deduction, keyed on the originating
    -- inventory_logs.local_id. The raw deduct_inventory above double-counts stock
    -- on a slow link (a replay, or a checkout that committed then timed out and
    -- was requeued, decrements twice). This variant claims each log's deduction
    -- exactly once via a dedup table, so any number of retries with the same
    -- local_id decrement at most once. The old function is kept for app versions
    -- that still call it.
    CREATE TABLE IF NOT EXISTS public.inventory_deductions_applied (
      local_id uuid PRIMARY KEY,
      applied_at timestamptz NOT NULL DEFAULT now()
    );
    ALTER TABLE public.inventory_deductions_applied ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Authenticated can access inventory_deductions_applied" ON public.inventory_deductions_applied;
    CREATE POLICY "Authenticated can access inventory_deductions_applied" ON public.inventory_deductions_applied
      FOR ALL TO authenticated USING (true) WITH CHECK (true);

    DROP FUNCTION IF EXISTS public.deduct_inventory_log(uuid, bigint, numeric);

    CREATE OR REPLACE FUNCTION public.deduct_inventory_log(p_local_id uuid, p_item_id bigint, p_qty numeric)
    RETURNS TABLE (
      out_id bigint,
      out_name text,
      out_current_stock numeric,
      out_applied boolean,
      out_found boolean
    ) AS $$
    DECLARE
      v_rows integer;
      v_exists boolean;
    BEGIN
      SELECT EXISTS (SELECT 1 FROM public.inventory WHERE id = p_item_id) INTO v_exists;
      IF NOT v_exists THEN
        RETURN QUERY SELECT p_item_id, NULL::text, NULL::numeric, false, false;
        RETURN;
      END IF;

      INSERT INTO public.inventory_deductions_applied (local_id)
      VALUES (p_local_id)
      ON CONFLICT (local_id) DO NOTHING;
      GET DIAGNOSTICS v_rows = ROW_COUNT;

      IF v_rows = 0 THEN
        RETURN QUERY
          SELECT inv.id, inv.name, inv.current_stock, false, true
          FROM public.inventory AS inv
          WHERE inv.id = p_item_id;
        RETURN;
      END IF;

      RETURN QUERY
        UPDATE public.inventory AS inv
        SET current_stock = inv.current_stock - p_qty
        WHERE inv.id = p_item_id AND inv.current_stock >= p_qty
        RETURNING inv.id, inv.name, inv.current_stock, true, true;
      -- Insufficient stock: release the claim so a later replay (after a
      -- restock) can still apply this deduction instead of it being lost.
      IF NOT FOUND THEN
        DELETE FROM public.inventory_deductions_applied WHERE local_id = p_local_id;
      END IF;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;

    -- Mirror image of the deduction, for stock coming BACK (refund return, rolled
    -- back checkout). Same dedup table, same claim-once rule, so a replayed queue
    -- entry or a double tap can never inflate stock (migration 037).
    CREATE OR REPLACE FUNCTION public.restock_inventory_log(p_local_id uuid, p_item_id bigint, p_qty numeric)
    RETURNS TABLE (
      out_id bigint,
      out_name text,
      out_current_stock numeric,
      out_applied boolean,
      out_found boolean
    ) AS $$
    DECLARE
      v_rows integer;
    BEGIN
      INSERT INTO public.inventory_deductions_applied (local_id)
      VALUES (p_local_id)
      ON CONFLICT (local_id) DO NOTHING;
      GET DIAGNOSTICS v_rows = ROW_COUNT;

      IF v_rows = 0 THEN
        RETURN QUERY
          SELECT inv.id, inv.name, inv.current_stock, false, true
          FROM public.inventory AS inv
          WHERE inv.id = p_item_id;
        RETURN;
      END IF;

      RETURN QUERY
        UPDATE public.inventory AS inv
        SET current_stock = inv.current_stock + p_qty
        WHERE inv.id = p_item_id
        RETURNING inv.id, inv.name, inv.current_stock, true, true;

      IF NOT FOUND THEN
        RETURN QUERY SELECT p_item_id, NULL::text, NULL::numeric, false, false;
      END IF;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;

    -- ==========================================
    -- ROAST / PRODUCTION LOT TRACEABILITY (migration 035). A "lot" is one
    -- received/produced batch of a lot-tracked item, carrying a made_date
    -- (roast/production) and a received_date (arrival) which differ when
    -- roasting is outsourced. inventory.track_lots flags participating items;
    -- it is set true automatically when an item is a Transform target. Link key
    -- is item_name (inventory.name is UNIQUE) so rows round-trip local<->cloud.
    -- ==========================================
    ALTER TABLE public.inventory
      ADD COLUMN IF NOT EXISTS track_lots boolean NOT NULL DEFAULT false;

    CREATE TABLE IF NOT EXISTS public.inventory_lots (
      id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      item_name     text NOT NULL,
      lot_code      text,
      made_date     date,
      received_date date,
      qty_received  numeric NOT NULL DEFAULT 0,
      qty_remaining numeric NOT NULL DEFAULT 0,
      unit          text,
      unit_cost     numeric DEFAULT 0,
      source_name   text,
      notes         text,
      local_id      uuid UNIQUE,
      created_at    timestamptz DEFAULT now()
    );
    CREATE INDEX IF NOT EXISTS inventory_lots_item_made_idx
      ON public.inventory_lots (item_name, made_date);
    ALTER TABLE public.inventory_lots ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Authenticated can access inventory_lots" ON public.inventory_lots;
    CREATE POLICY "Authenticated can access inventory_lots" ON public.inventory_lots
      FOR ALL TO authenticated USING (true) WITH CHECK (true);

    -- ==========================================
    -- FIFO LOT DRAW-DOWN (migration 036). One row per lot a sale drew from:
    -- lot_id -> the sales that consumed it, ticket_id -> the lot(s) it used.
    -- Additive; stock stays owned by inventory.current_stock.
    -- ==========================================
    CREATE TABLE IF NOT EXISTS public.lot_consumptions (
      id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      lot_id             uuid,
      lot_code           text,
      item_name          text,
      qty                numeric NOT NULL DEFAULT 0,
      ticket_id          text,
      deduction_local_id uuid,
      created_at         timestamptz DEFAULT now(),
      local_id           uuid UNIQUE
    );
    CREATE INDEX IF NOT EXISTS lot_consumptions_lot_idx    ON public.lot_consumptions (lot_id);
    CREATE INDEX IF NOT EXISTS lot_consumptions_ticket_idx ON public.lot_consumptions (ticket_id);
    ALTER TABLE public.lot_consumptions ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Authenticated can access lot_consumptions" ON public.lot_consumptions;
    CREATE POLICY "Authenticated can access lot_consumptions" ON public.lot_consumptions
      FOR ALL TO authenticated USING (true) WITH CHECK (true);

    -- ==========================================
    -- APP USERS: unified allowlist for who may sign into this tinypos.
    -- NOTE: this block deliberately avoids ALL references to the auth schema
    -- (no FK to auth.users, no trigger on auth.users, no backfill SELECT
    -- against auth.users). Some Supabase project configurations restrict
    -- those operations via the Management API and the install partially
    -- failed under v0.1. The claim-or-bootstrap logic now lives in an RPC
    -- the client calls on every sign-in.
    -- ==========================================
    CREATE TABLE IF NOT EXISTS public.app_users (
      id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      email        text NOT NULL UNIQUE,
      role         text NOT NULL DEFAULT 'employee',
      auth_user_id uuid UNIQUE,
      provider     text,
      created_by   uuid,
      created_at   timestamptz NOT NULL DEFAULT now(),
      disabled_at  timestamptz
    );
    CREATE INDEX IF NOT EXISTS idx_app_users_email_lower ON public.app_users (lower(email));

    -- SECURITY DEFINER so the admin-check policy doesn't recurse into itself.
    CREATE OR REPLACE FUNCTION public.is_app_admin(p_user_id uuid)
    RETURNS boolean
    LANGUAGE sql
    SECURITY DEFINER
    STABLE
    SET search_path = public
    AS $$
      SELECT EXISTS (
        SELECT 1 FROM public.app_users
        WHERE auth_user_id = p_user_id
          AND role = 'admin'
          AND disabled_at IS NULL
      );
    $$;

    ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Users can read own row"        ON public.app_users;
    DROP POLICY IF EXISTS "Users can read pending row"    ON public.app_users;
    DROP POLICY IF EXISTS "Users can claim pending row"   ON public.app_users;
    DROP POLICY IF EXISTS "Admins can read all"           ON public.app_users;
    DROP POLICY IF EXISTS "Admins can insert"             ON public.app_users;
    DROP POLICY IF EXISTS "Admins can update"             ON public.app_users;
    DROP POLICY IF EXISTS "Admins can delete"             ON public.app_users;

    CREATE POLICY "Users can read own row" ON public.app_users
      FOR SELECT TO authenticated
      USING (auth_user_id = auth.uid());

    CREATE POLICY "Admins can read all" ON public.app_users
      FOR SELECT TO authenticated USING (public.is_app_admin(auth.uid()));
    CREATE POLICY "Admins can insert" ON public.app_users
      FOR INSERT TO authenticated WITH CHECK (public.is_app_admin(auth.uid()));
    CREATE POLICY "Admins can update" ON public.app_users
      FOR UPDATE TO authenticated
      USING (public.is_app_admin(auth.uid()))
      WITH CHECK (public.is_app_admin(auth.uid()));
    CREATE POLICY "Admins can delete" ON public.app_users
      FOR DELETE TO authenticated USING (public.is_app_admin(auth.uid()));

    -- Replaces the prior trigger on auth.users. Called by the client on
    -- every successful sign-in. SECURITY DEFINER so it can write to
    -- app_users regardless of caller's RLS context — the body is the only
    -- self-write surface area available to authenticated users.
    --
    -- Behavior:
    --   1. If a pending row (auth_user_id IS NULL) matches the caller's JWT
    --      email, link it to auth.uid().
    --   2. If the caller's email is @device.tinypos.com and no row exists
    --      for them, insert one with role='device'.
    --   3. If app_users has no admin row at all, promote the caller to
    --      admin (the first-user bootstrap).
    --   4. Return the caller's effective row (or NULL if still not on the
    --      list and bootstrap conditions didn't apply).
    CREATE OR REPLACE FUNCTION public.claim_or_bootstrap_app_user()
    RETURNS public.app_users
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = public
    AS $$
    DECLARE
      v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
      v_uid   uuid := auth.uid();
      v_row   public.app_users%ROWTYPE;
    BEGIN
      IF v_email = '' OR v_uid IS NULL THEN
        RETURN NULL;
      END IF;

      -- 1. Claim a pending row matching this email if one exists.
      UPDATE public.app_users
         SET auth_user_id = v_uid
       WHERE auth_user_id IS NULL
         AND lower(email) = v_email
         AND disabled_at IS NULL
      RETURNING * INTO v_row;

      IF FOUND THEN RETURN v_row; END IF;

      -- 2. Device email auto-add.
      IF v_email LIKE '%@device.tinypos.com' THEN
        INSERT INTO public.app_users (email, role, auth_user_id, provider)
        VALUES (v_email, 'device', v_uid, 'email')
        ON CONFLICT (email) DO UPDATE
          SET auth_user_id = EXCLUDED.auth_user_id
          WHERE public.app_users.auth_user_id IS NULL
        RETURNING * INTO v_row;
        IF v_row.id IS NOT NULL THEN RETURN v_row; END IF;
      END IF;

      -- 3. First-admin bootstrap when nobody is home yet.
      IF NOT EXISTS (SELECT 1 FROM public.app_users WHERE role = 'admin' LIMIT 1) THEN
        INSERT INTO public.app_users (email, role, auth_user_id, provider, created_by)
        VALUES (v_email, 'admin', v_uid, 'email', v_uid)
        ON CONFLICT (email) DO UPDATE
          SET auth_user_id = EXCLUDED.auth_user_id, role = 'admin'
        RETURNING * INTO v_row;
        RETURN v_row;
      END IF;

      -- 4. Caller already has a claimed row — return it.
      SELECT * INTO v_row
      FROM public.app_users
      WHERE auth_user_id = v_uid AND disabled_at IS NULL
      LIMIT 1;
      RETURN v_row;
    END;
    $$;
    GRANT EXECUTE ON FUNCTION public.claim_or_bootstrap_app_user() TO authenticated;

    -- ==========================================
    -- SCHEMA META — version stamp the install just landed.
    -- When the JS APP_SCHEMA_VERSION differs from value here the General
    -- Settings tab surfaces "Update available." Bump this literal AND
    -- src/utils/schemaVersion.js in the same commit on any schema change.
    -- ==========================================
    -- ==========================================
    -- CFDI PORTAL (migration 039)
    -- ==========================================
    -- CFDI portal RPCs (schema 1.6, step 1 of the security lockdown).
    --
    -- WHY
    -- Migrations 031/033 gave the \`anon\` role blanket RLS policies so the public
    -- CFDI portal (PublicCFDI.jsx, opened from the QR code printed on every
    -- receipt) could find a ticket and record a factura request:
    --
    --   sales                 SELECT + UPDATE  USING (true)
    --   active_tickets        SELECT           USING (true)
    --   fiscal_profiles       SELECT + INSERT + UPDATE  USING (true)
    --   cfdi_global_periods   SELECT           USING (true)
    --
    -- The anon key is public by design (it ships inside the receipt QR and the
    -- menu link), so those policies let anyone who has seen one receipt read the
    -- whole sales history — totals, cashier names, loyalty phone numbers — read
    -- and rewrite every customer's fiscal data (RFC, razón social, email: personal
    -- data under the LFPDPPP), and UPDATE any column of any sale.
    --
    -- WHAT THIS DOES
    -- Replaces that direct table access with two SECURITY DEFINER functions that
    -- are the portal's entire surface:
    --
    --   cfdi_lookup_ticket(p_ref)    -- one ticket, only the fields the page shows
    --   cfdi_request_invoice(p_ref, ...) -- upsert the fiscal profile + flag ONE sale
    --
    -- Both require the caller to already hold the ticket reference from their own
    -- receipt. Neither can enumerate, and cfdi_request_invoice writes exactly two
    -- columns (fiscal_profile_id, cfdi_status) on exactly one row.
    --
    -- The anon table policies themselves are dropped in the next migration (040),
    -- once the portal shipped here is live — dropping them first would break the
    -- portal for customers mid-deploy.

    -- ---------------------------------------------------------------------------
    -- Base CFDI schema guards.
    -- The full from-scratch script in api/install.js never carried the CFDI
    -- tables (they only ever shipped as deltas 0.9/1.0), so a brand-new install
    -- has no fiscal_profiles at all and the functions below would have nothing to
    -- run against. These are the same idempotent statements as deltas 0.9/1.0,
    -- minus the anon policies, so first installs and upgrades converge.
    -- ---------------------------------------------------------------------------
    CREATE TABLE IF NOT EXISTS public.fiscal_profiles (
      id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
      rfc text NOT NULL UNIQUE,
      razon_social text NOT NULL,
      regimen_fiscal text NOT NULL,
      uso_cfdi text NOT NULL,
      cp text NOT NULL,
      email text NOT NULL,
      created_at timestamp with time zone DEFAULT now(),
      updated_at timestamp with time zone DEFAULT now()
    );
    ALTER TABLE public.fiscal_profiles ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.fiscal_profiles;
    CREATE POLICY "Enable all for authenticated users" ON public.fiscal_profiles
      FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

    ALTER TABLE public.sales
      ADD COLUMN IF NOT EXISTS cfdi_status text DEFAULT 'none' CHECK (cfdi_status IN ('none', 'requested', 'issued', 'reopened', 'canceled')),
      ADD COLUMN IF NOT EXISTS cfdi_folio text,
      ADD COLUMN IF NOT EXISTS fiscal_profile_id uuid REFERENCES public.fiscal_profiles(id);

    ALTER TABLE public.active_tickets
      ADD COLUMN IF NOT EXISTS cfdi_status text DEFAULT 'none' CHECK (cfdi_status IN ('none', 'requested', 'issued', 'reopened', 'canceled')),
      ADD COLUMN IF NOT EXISTS cfdi_folio text,
      ADD COLUMN IF NOT EXISTS fiscal_profile_id uuid REFERENCES public.fiscal_profiles(id);

    CREATE INDEX IF NOT EXISTS idx_sales_cfdi_status ON public.sales(cfdi_status) WHERE cfdi_status != 'none';
    CREATE INDEX IF NOT EXISTS idx_active_tickets_cfdi_status ON public.active_tickets(cfdi_status) WHERE cfdi_status != 'none';

    CREATE TABLE IF NOT EXISTS public.cfdi_global_periods (
      period text PRIMARY KEY,
      business_name text,
      summary jsonb,
      closed_at timestamp with time zone DEFAULT now()
    );
    ALTER TABLE public.cfdi_global_periods ADD COLUMN IF NOT EXISTS summary jsonb;
    ALTER TABLE public.cfdi_global_periods ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.cfdi_global_periods;
    CREATE POLICY "Enable all for authenticated users" ON public.cfdi_global_periods
      FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

    -- ---------------------------------------------------------------------------
    -- Shared resolver: ticket reference -> the one row it names.
    -- Mirrors the three lookups PublicCFDI.jsx used to do client-side:
    --   1. a uuid  -> sales.local_id   (links from OrdersTab / PNG receipts)
    --   2. any ref -> sales.ticket_id  (the original activeTicket.id, as text)
    --   3. digits  -> active_tickets.id (ticket still open at the register)
    -- Returns the sale id (bigint), whether it is a paid sale, and the row.
    -- ---------------------------------------------------------------------------
    CREATE OR REPLACE FUNCTION public.cfdi_resolve_ticket(
      p_ref text,
      OUT o_id bigint,
      OUT o_is_paid boolean,
      OUT o_row jsonb
    )
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = public
    STABLE
    AS $$
    DECLARE
      v_is_uuid boolean := p_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
    BEGIN
      o_id := NULL; o_is_paid := NULL; o_row := NULL;
      IF p_ref IS NULL OR length(p_ref) = 0 THEN
        RETURN;
      END IF;

      IF v_is_uuid THEN
        SELECT s.id, true, to_jsonb(s) INTO o_id, o_is_paid, o_row
        FROM public.sales s WHERE s.local_id = p_ref::uuid LIMIT 1;
      END IF;

      IF o_id IS NULL THEN
        SELECT s.id, true, to_jsonb(s) INTO o_id, o_is_paid, o_row
        FROM public.sales s WHERE s.ticket_id = p_ref LIMIT 1;
      END IF;

      IF o_id IS NULL AND p_ref ~ '^[0-9]{1,18}$' THEN
        SELECT t.id, false, to_jsonb(t) INTO o_id, o_is_paid, o_row
        FROM public.active_tickets t WHERE t.id = p_ref::bigint LIMIT 1;
      END IF;
    END;
    $$;

    -- ---------------------------------------------------------------------------
    -- cfdi_lookup_ticket — everything the portal needs, in one call.
    --
    -- Returns ONLY the fields PublicCFDI.jsx renders. Deliberately withheld from
    -- the anon caller: cashier_name, loyalty_phone / loyalty_* columns, splits,
    -- payment_method, refund columns, local_id, and every other sale in the table.
    -- The fiscal profile comes back only as a prefill for the profile already
    -- attached to this very ticket — there is no lookup by RFC any more.
    -- ---------------------------------------------------------------------------
    CREATE OR REPLACE FUNCTION public.cfdi_lookup_ticket(p_ref text)
    RETURNS jsonb
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = public
    STABLE
    AS $$
    DECLARE
      v_id bigint; v_is_paid boolean; v_row jsonb;
      v_profile jsonb := NULL;
      v_global jsonb := NULL;
      v_period text;
    BEGIN
      SELECT o_id, o_is_paid, o_row INTO v_id, v_is_paid, v_row
      FROM public.cfdi_resolve_ticket(p_ref);

      IF v_id IS NULL THEN
        RETURN jsonb_build_object('found', false);
      END IF;

      IF (v_row->>'fiscal_profile_id') IS NOT NULL THEN
        SELECT to_jsonb(f) - 'created_at' - 'updated_at' INTO v_profile
        FROM public.fiscal_profiles f
        WHERE f.id = (v_row->>'fiscal_profile_id')::uuid;
      END IF;

      -- Factura Global block. The period is derived in the SHOP's timezone; the
      -- page used to derive it from the visitor's browser clock, which disagreed
      -- for customers abroad on the first/last day of a month.
      IF v_is_paid AND (v_row->>'created_at') IS NOT NULL THEN
        v_period := to_char(
          ((v_row->>'created_at')::timestamptz AT TIME ZONE public.shop_timezone()), 'YYYY-MM');
        SELECT jsonb_build_object('period', g.period, 'business_name', g.business_name)
        INTO v_global
        FROM public.cfdi_global_periods g WHERE g.period = v_period;
      END IF;

      RETURN jsonb_build_object(
        'found', true,
        'ticket', jsonb_build_object(
          'id',                v_id,
          'is_paid',           v_is_paid,
          'created_at',        v_row->>'created_at',
          'cfdi_status',       COALESCE(v_row->>'cfdi_status', 'none'),
          'cfdi_folio',        v_row->>'cfdi_folio',
          'fiscal_profile_id', v_row->>'fiscal_profile_id',
          'order_name',        v_row->>'order_name',
          'ticket_id',         v_row->>'ticket_id',
          'items',             COALESCE(v_row->'items', '[]'::jsonb),
          'total_amount',      v_row->'total_amount'
        ),
        'profile', v_profile,
        'global_period', v_global
      );
    END;
    $$;

    -- ---------------------------------------------------------------------------
    -- cfdi_request_invoice — record a factura request for ONE ticket.
    --
    -- Enforces server-side what the page enforced client-side (and what the anon
    -- UPDATE policy enforced not at all):
    --   * the ref must resolve to a PAID sale (an open ticket can't be invoiced)
    --   * its month must not already be closed into a Factura Global
    --   * its cfdi_status must be 'none' or 'reopened' (a requested/issued/
    --     canceled ticket is read-only to the customer)
    --   * only fiscal_profile_id and cfdi_status are ever written
    -- Returns { ok, cfdi_status, fiscal_profile_id } or { ok:false, reason }.
    -- ---------------------------------------------------------------------------
    CREATE OR REPLACE FUNCTION public.cfdi_request_invoice(
      p_ref text,
      p_rfc text,
      p_razon_social text,
      p_regimen_fiscal text,
      p_uso_cfdi text,
      p_cp text,
      p_email text
    )
    RETURNS jsonb
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = public
    AS $$
    DECLARE
      v_id bigint; v_is_paid boolean; v_row jsonb;
      v_status text; v_period text; v_closed boolean;
      v_rfc text := upper(btrim(COALESCE(p_rfc, '')));
      v_profile_id uuid;
    BEGIN
      SELECT o_id, o_is_paid, o_row INTO v_id, v_is_paid, v_row
      FROM public.cfdi_resolve_ticket(p_ref);

      IF v_id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'not_found');
      END IF;
      IF NOT v_is_paid THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'not_paid');
      END IF;

      v_status := COALESCE(v_row->>'cfdi_status', 'none');
      IF v_status NOT IN ('none', 'reopened') THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'not_editable', 'cfdi_status', v_status);
      END IF;

      v_period := to_char(
        ((v_row->>'created_at')::timestamptz AT TIME ZONE public.shop_timezone()), 'YYYY-MM');
      SELECT EXISTS (SELECT 1 FROM public.cfdi_global_periods g WHERE g.period = v_period)
      INTO v_closed;
      -- A reopened request is an explicit admin override, so it survives the close.
      IF v_closed AND v_status = 'none' THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'global_closed', 'period', v_period);
      END IF;

      -- Same validation the form does, enforced where it counts.
      IF v_rfc !~ '^[A-ZÑ&]{3,4}[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]$' THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'invalid_rfc');
      END IF;
      IF btrim(COALESCE(p_razon_social, '')) = ''
         OR btrim(COALESCE(p_regimen_fiscal, '')) = ''
         OR btrim(COALESCE(p_uso_cfdi, '')) = ''
         OR COALESCE(p_cp, '') !~ '^[0-9]{5}$'
         OR COALESCE(p_email, '') !~ '^[^[:space:]@]+@[^[:space:]@]+\\.[^[:space:]@]+$' THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'invalid_fields');
      END IF;

      INSERT INTO public.fiscal_profiles (rfc, razon_social, regimen_fiscal, uso_cfdi, cp, email)
      VALUES (v_rfc, btrim(p_razon_social), btrim(p_regimen_fiscal), btrim(p_uso_cfdi),
              btrim(p_cp), btrim(p_email))
      ON CONFLICT (rfc) DO UPDATE SET
        razon_social   = EXCLUDED.razon_social,
        regimen_fiscal = EXCLUDED.regimen_fiscal,
        uso_cfdi       = EXCLUDED.uso_cfdi,
        cp             = EXCLUDED.cp,
        email          = EXCLUDED.email,
        updated_at     = now()
      RETURNING id INTO v_profile_id;

      UPDATE public.sales
      SET fiscal_profile_id = v_profile_id,
          cfdi_status = 'requested'
      WHERE id = v_id;

      RETURN jsonb_build_object(
        'ok', true,
        'cfdi_status', 'requested',
        'fiscal_profile_id', v_profile_id
      );
    END;
    $$;

    -- The portal is the only anon caller; the POS itself (authenticated) keeps its
    -- direct table access. cfdi_resolve_ticket is an internal helper — the two
    -- public entry points call it as their definer-owner, so anon needs no grant
    -- on it. (Migration 041 revokes the implicit anon/authenticated grants that
    -- Supabase adds to every new function; these explicit ones are what survive.)
    REVOKE ALL ON FUNCTION public.cfdi_resolve_ticket(text) FROM PUBLIC, anon, authenticated;
    REVOKE ALL ON FUNCTION public.cfdi_lookup_ticket(text) FROM PUBLIC;
    REVOKE ALL ON FUNCTION public.cfdi_request_invoice(text, text, text, text, text, text, text) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION public.cfdi_lookup_ticket(text) TO anon, authenticated;
    GRANT EXECUTE ON FUNCTION public.cfdi_request_invoice(text, text, text, text, text, text, text) TO anon, authenticated;

    -- Close the anon key's direct table access (schema 1.6, step 2).
    --
    -- Step 1 (migration 039) gave the public CFDI portal cfdi_lookup_ticket and
    -- cfdi_request_invoice. With the portal on those RPCs, the blanket anon
    -- policies from migrations 031/033 have no caller left, and every one of them
    -- was a hole: the anon key is printed inside the QR code on every receipt, so
    -- "anon can SELECT sales USING (true)" meant anyone holding a receipt could
    -- read the whole sales history (totals, cashier names, loyalty phone numbers),
    -- UPDATE any column of any sale, and read or rewrite every customer's fiscal
    -- data — RFC, razón social, email: personal data under the LFPDPPP.
    --
    -- Two of the fiscal_profiles policies were written without TO anon, so they
    -- applied to PUBLIC (every role). Dropping them costs the POS nothing: the
    -- "Enable all for authenticated users" policy on that table is untouched.
    --
    -- ORDER MATTERS: this must not reach a project whose deployed frontend still
    -- queries these tables with the anon key, or the portal dies for customers
    -- mid-deploy. It ships in the same 1.6 release as the RPCs and the rewritten
    -- PublicCFDI.jsx.

    -- Sales: the portal's read + "set cfdi_status" write.
    DROP POLICY IF EXISTS "CFDI portal can read sales" ON public.sales;
    DROP POLICY IF EXISTS "CFDI portal can update cfdi on sales" ON public.sales;

    -- Active tickets: the portal's "is this ticket still open?" read.
    DROP POLICY IF EXISTS "CFDI portal can read active_tickets" ON public.active_tickets;

    -- Fiscal profiles: lookup by RFC, insert, and refresh of an existing RFC.
    DROP POLICY IF EXISTS "CFDI portal can update fiscal_profiles" ON public.fiscal_profiles;
    DROP POLICY IF EXISTS "Enable insert for anon" ON public.fiscal_profiles;
    DROP POLICY IF EXISTS "Enable select for anon by rfc or id" ON public.fiscal_profiles;

    -- Global periods: the "already in the Factura Global" legend, now returned by
    -- cfdi_lookup_ticket.
    DROP POLICY IF EXISTS "CFDI portal can read global periods" ON public.cfdi_global_periods;

    -- Policies are only half of it. Supabase grants anon table privileges up front,
    -- and RLS then decides which rows those privileges reach — so leaving the GRANT
    -- in place would keep the door on its hinges for any future policy that says
    -- USING (true) by accident. The portal needs no table privilege at all: its two
    -- functions are SECURITY DEFINER and run as their owner.
    REVOKE ALL ON TABLE public.sales               FROM anon;
    REVOKE ALL ON TABLE public.active_tickets      FROM anon;
    REVOKE ALL ON TABLE public.fiscal_profiles     FROM anon;
    REVOKE ALL ON TABLE public.cfdi_global_periods FROM anon;

    -- NOTE (not fixed here): order_fulfillment carries "KDS anon read" and
    -- "KDS anon update" policies, both USING (true). They are not created by this
    -- repo's install script — they belong to the kitchen-display app sharing this
    -- project — so removing them here would break that app. Same exposure, same
    -- anon key; it needs the same RPC treatment on the KDS side.

    CREATE TABLE IF NOT EXISTS public.schema_meta (
      key text PRIMARY KEY,
      value text NOT NULL,
      updated_at timestamptz NOT NULL DEFAULT now()
    );
    ALTER TABLE public.schema_meta ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Authenticated can read schema_meta" ON public.schema_meta;
    CREATE POLICY "Authenticated can read schema_meta" ON public.schema_meta
      FOR SELECT TO authenticated USING (true);

    INSERT INTO public.schema_meta (key, value, updated_at)
    VALUES ('schema_version', '1.6', now())
    ON CONFLICT (key) DO UPDATE
      SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at;
  `;

  // 3b. Pick the SQL to run. An existing install one-or-more versions behind
  //     runs only its delta (small + fast, stays under Hobby's ~10s cap); a
  //     first install / unknown / gapped version runs the full script above.
  //     deltasFrom() returns '' when already current, null to force full.
  const delta = fromVersion ? deltasFrom(fromVersion) : null;
  if (delta === '') {
    return res.status(200).json({ success: true, message: 'Already up to date.', mode: 'noop' });
  }
  const query = delta || schemaQuery;
  const mode = delta ? 'delta' : 'full';

try {
    // 4. Send the SQL directly to Supabase's Management API
    const response = await fetch(
      `https://api.supabase.com/v1/projects/${projectRef}/database/query`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ query }),
      }
    );

    // 5. Handle the API Response
    const data = await response.json().catch(() => ({}));

    if (!response.ok) {
      console.error("Supabase API Error:", data);
      return res.status(response.status).json({ 
        success: false, 
        error: data.message || 'Failed to execute query on Supabase.' 
      });
    }

    // 6. Success!
    return res.status(200).json({ success: true, message: 'Database installed successfully!', mode });

  } catch (error) {
    console.error("Installation network/server failed:", error);
    return res.status(500).json({ success: false, error: 'Internal Server Error' });
  }
}
